### ISSUE TITLE
auth - incorrect error behavior if user provides invalid email

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1057]
"During sign up, if there is an error in the email address and 'create account' is clicked, the user is taken from the sign up window to an error page instead of just getting a suggested correct email address. See attached screenshot.

This may be a change in the code as we did not see this earlier in the week."

If we can't suggest a correct email address, can't we at least do the shake action on the email field and tell the user that it is an invalid email?

https://trello-attachments.s3.amazonaws.com/52ea92c7ccdaf8415b8cab3a/5318fef232c51afc5a538935/de45af779effa8d4a15b483d8c4c052d/email-error.jpg

https://trello.com/c/aDSNsEI2

**Comment by DFurnes** [comment]
"If we can't suggest a correct email address, can't we at least do the shake action on the email field and tell the user that it is an invalid email?"

That should be the expected behavior. Looking into why this isn't working.

**Comment by DFurnes** [comment]
We're being somewhat intentionally lenient in what we refuse so that we don't accidentally refuse a real email address by mistake (since the email spec is [kinda crazy](http://rumkin.com/software/email/rules.php)), so right now we're really just checking for whether the string matches a `___@___.___` type of pattern. I'll add in a check to disallow double periods.

**Comment by mikefantini** [comment]
@DFurnes awesome that fix makes sense
