### ISSUE TITLE
Login redirect to legacy app

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#1060]
When a desitination parameter is present during login, the system should also look for  the "legacy" key to determine whether or not to redirect to the old pool.  We should have it use the referrer value for the redirect uri value.

`http://beta.dosomething.org/user/login?destination=node/1234&legacy`

**Comment by mshmsh5000** [comment]
So
1. Beta user/login needs to respect "destination"
2. Varnish needs to switch pools on "legacy"
3. Need to confirm that "legacy" is sufficiently unique -- e.g., that no existing URL aliases contain "legacy"

**Comment by desmondmorris** [comment]
@mshmsh5000 I was just thinking that the switch would happen on the app side, not varnish.  So if the GET param "legacy" is present during a destination redirect

**Comment by aaronschachter** [comment]
In beta, we'll have campaign nodes that act as dummy placeholders for live legacy campaigns, to make search way easier.

This should take care of the system "determin[ing] whether or not to redirect to the old pool".  However, we need to write the signup record into the legacy app in order for the node to function properly.  While we're at it, we may as well write the signup for the dummy node into the beta signups table, so the dummy node will appear in the user's signups on the profile.

We'd need to tweak the legacy and beta apps as follows:
- If you navigate to a live campaign, redirect to user/login with `?destination=[beta-nid]&legacy` where beta-nid is the corresponding beta nid for this campaign.  We can just hardcore this per 3 or 4 campaigns that will be live.
- In beta app, upon user login, if legacy is passed in query string, write signups to both DB's if they don't exist.  In theory this should happen before the global redirect bounces you out to the legacy app, but we'll to test to be sure.

**Comment by mshmsh5000** [comment]
@desmondmorris "legacy" will only reach the beta app if varnish knows to direct it there.

<pre>/user/login?destination=node/1234&amp;legacy</pre>

will get passed to the beta app because `/user` gets directed there. After you submit, what happens? 
1. POST goes to beta app because you're POSTing to `/user/login`
2. Beta app does a drupal_goto() to '/node/1234'
3. ?

or, if 'legacy' is encoded into the destination URL, like

<pre>/user/login?destination=%2Fnode%2F1234%26legacy</pre>

(or something like that)
1. POST goes to beta app because you're POSTing to `/user/login`
2. Beta app does a drupal_goto() to '/node/1234&amp;legacy'
3. Varnish sees 'legacy' and directs to legacy app.

This is clearly not what you're thinking, so let me know the alternative.

**Comment by desmondmorris** [comment]
@mshmsh5000 this totally makes sense.  I was just being dense.  Thanks for the break down

**Comment by angaither** [comment]
Closing.

**Comment by aaronschachter** [comment]
Redirects are handled via the `dosomething_legacy` and `dosomething_beta` modules in each repo.
