### ISSUE TITLE
action page (plan it) - PDFs should download automatically

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1372]
Currently we're hosting PDFs in a drop box account and allowing users to download them from drop box.

Ideally we'd just download the PDFs automatically rather than having them open up a new window.

Examples:
- /campaigns/flyer-away
- /campaigns/comics-rescue
- /campaigns/cell-phones-survivors
- /campaigns/realprincess
- /campaigns/13-gallon-challenge
- /campaigns/flyer-away
- /campaigns/school-standstill

**Comment by barryclark** [comment]
@mikefantini The problem here is just that the link we're using isn't the actual file itself, it's a link to the Dropbox or Google Drive page for the file. 

However you can link directly to the file...
- https://www.dropbox.com/help/201/en
- https://productforums.google.com/forum/#!msg/drive/lH_O_XwGJ_0/BfSHqC0P3rUJ

Let me know if either of those solutions work well enough. The bigger solution would be to open up cloud space for these files, with a admin UI for the campaigns team to be able to go in, upload and grab the link. (although ultimately this is basically what Dropbox already is)

cc @aaronschachter

**Comment by aaronschachter** [comment]
There's an item in the latest Campaign FFA for attaching file downloads to the Campaign node itself... which is also a relatively simple solution to implement.

**Comment by barryclark** [comment]
Sweet, let's close this then @mikefantini?

**Comment by mikefantini** [comment]
yeah this just came from the desire to attach file downloads for these posters, etc. we captured it in the FFA.

@barryclark you want to close this out and open up a new one for the feature in the FFA?

**Comment by barryclark** [comment]
Sounds good, thanks @mikefantini
