### ISSUE TITLE
zendesk error on second submission

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1388]
as an auth user, signed up for Comeback Clothes, I send a question to Zendesk, and then I send a second question in to Zendesk.

When I go to send a second question I get this error message:
![image](https://f.cloud.github.com/assets/6330971/2445652/d6833f42-ae77-11e3-883c-6c53314cf146.png)

**Comment by aaronschachter** [comment]
Complete guess but I wonder if this is occurring because the API won't allow for creating a 2nd ticket with the same subject, and is expecting us to update the existing ticket instead.

**Comment by aaronschachter** [comment]
Nope, not the case, it's creating new tickets.  Will try testing with a diff user / campaign combo but so far can't replicate on a test campaign.

![screen shot 2014-03-26 at 1 41 52 pm](https://f.cloud.github.com/assets/1236811/2528301/3c564002-b50e-11e3-8755-8b79efc22447.png)

**Comment by aaronschachter** [comment]
yes i'm talking to myself in this thread. recreated the error locally using email `aschachter+zendesk@dosomething.org` on comeback clothes but could not recreate using `aschachter@dosomething.org`

![screen shot 2014-03-26 at 2 24 23 pm](https://f.cloud.github.com/assets/1236811/2528852/f5d766b4-b513-11e3-91ca-146a3a102bcb.png)

**Comment by aaronschachter** [comment]
Ok, it happens on the 2nd time with a new account, and if you're submitting immediately after you submit the 1st.  The error is occurring on "Users create is not valid".  It seems that this is occurring because there's a lag in getting the result back from the `$client->search` method.

The first todo here is to add a try / catch statement to this guy `$client->users()->create($new_user);` to prevent the crazy white background / red error message guy.

The 2nd thing may be to just create a corresponding Zendesk user upon user registration, to avoid potential lag issues.  Then it would just happen for existing users.
