### ISSUE TITLE
Move SOLR configs in settings.php

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#1566]
In efforts to make this codebase more portable, specifically for use with the affiliates, it  is necessary that all external services be configurable from settings.php.  This way we are not reliant on settings stashed in the DB.

The biggest concern is the connection settings for SOLR right now.  When we spin a new instance with a dump from production/staging, the instance attempts to connect to the production solr instance.

@blisteringherb @mshmsh5000 thoughts?

**Comment by desmondmorris** [comment]
I just saw that the we are shipping a default localhost configuration, so this may mitigate this issue.  Still will love to hear what you guys think

**Comment by aaronschachter** [comment]
@blisteringherb @desmondmorris Going thru old issues - is this one still valid?

**Comment by blisteringherb** [comment]
All of the Solr settings are either in environment variables, settings.php or both.  The issue is that the apachesolr environments.inc file defines the host, port, and path, and while those are set to use variables, they do end up cached in the db.  Clearing cache should fix the issue, but if not, we might to implement something more heavy handed to make sure it's always using the right solr urls.
