### ISSUE TITLE
11 Facts - error on production (beta)

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1571]
On production I get the "The website encountered an unexpected error. Please try again later." error message when going to https://beta.dosomething.org/content/11-facts-about-tsunamis (or any other 11 facts pages).

Page looks fine on staging.

cc: @julielorch 

![image](https://cloud.githubusercontent.com/assets/6330971/2551757/fc810662-b691-11e3-8d32-3975127c0d3b.png)

**Comment by aaronschachter** [comment]
Need to remove the `field_video` 11 facts preprocess.

from the EntityMetadataWrapperException: Unknown data property field_video. in EntityStructureWrapper->getPropertyInfo() (line 335 of /var/www/beta.dosomething.org/releases/20140327203603/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).

I deleted the field instance on production last night, because we don't need it. This is what's causing the error on production and not on stage.
