### ISSUE TITLE
Campaign Finder - "show more" pagination

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1729]
Include a "Show More" button if there are more campaign results, when the user clicks it should populate an additional 12 campaigns.

**Comment by mikefantini** [comment]
updated above... should be showing an additional 12 campaigns when user selects "Show More"

**Comment by mikefantini** [comment]
from the mocks: https://cloud.githubusercontent.com/assets/6331017/2639003/0fb53452-bebb-11e3-9fc1-fd254387ca83.jpg

**Comment by mikefantini** [comment]
@julielorch before we get to "Show More" shouldn't we be displaying 12 results (9 when no filters are selected) not 8? If you select Education, you can see that it limits the view to 8 and would then need pagination when really we should show 12 before requiring pagination.

(In the case of Education we'll need pagination regardless, but still we'd need to show 12 results, and then by showing more show all of them rather than just showing 8).

**Comment by barryclark** [comment]
We decided to stick with 8 results. :sun_with_face:
