### ISSUE TITLE
Campaign Finder - filters not responsive on IE8/XP

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1758]
When attempting to click a cause while running the website on Internet Explorer 8 on Windows XP, the links didn't do anything. They didn't change the campaigns shown below or even highlight when clicked.

https://trello.com/c/dOjwXb7D

**Comment by angaither** [comment]
WHO CARES 
http://windows.microsoft.com/en-us/windows/end-support-help

**Comment by mikefantini** [comment]
@barryclark @Bladt your call; it was my understanding that we were still aiming to support XP users

**Comment by weerd** [comment]
So, while IE8 sucks and all, sometimes.... just sometimes... since it's less forgiving than modern browsers, it can actually highlight (in it's own cryptic way) that there's something wrong with the most basic things in the code. As such is the case with this issue. Turns out the HTML markup was a bit off, and modern browsers just kinda patch it up for you, but it's best to write it correctly to avoid future unexpected bugs. 

Fixing it, and need to adjust the JS a bit to relate to the new markup. Just wanted to explain a bit more regarding the why :smirk:

**Comment by weerd** [comment]
@mikefantini @barryclark fix has been pushed to stage. I just tried it (stage) on BrowserStack and works well :)

**Comment by barryclark** [comment]
:beers:
