### ISSUE TITLE
Sources line spacing

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1790]
- [ ] Numbers should either be superscript and smaller or same size and on the same flat line with the source content. 

![screen shot 2014-04-14 at 6 45 53 pm](https://cloud.githubusercontent.com/assets/6550604/2701789/c3546aa8-c426-11e3-81f4-3995693dbdff.png)
- [x] Please remove some of the spacing above the source section / below the content in STEP ONE: KNOW IT

![screen shot 2014-04-14 at 6 48 41 pm](https://cloud.githubusercontent.com/assets/6550604/2701801/fff8c59e-c426-11e3-9d09-6f8f4552ed09.png)
- [x] Add a little bit of space after each source for readibility

**Comment by tjrosario** [comment]
@lkpttn Since the smallest font size is 13px, we can make the superscript be inline with the content.  Any objections on this proposed design?  Created space between the superscript and content, else it looks pretty tight.  Open to other suggestions.
![image](https://cloud.githubusercontent.com/assets/1566749/4310253/b8d3fb04-3ea4-11e4-884f-b2789d15f2c1.png)

**Comment by lkpttn** [comment]
Looks good, no objections.

**Comment by weerd** [comment]
Yeah, this sounds good to me. Chat w/ @DFurnes too, cause the styles for it might affect somewhere else too and he might know better if it affects anything else :)
