### ISSUE TITLE
Group Campaign -> dosomething_mbp request

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1984]
A transactional request needs to be made to the Message Broker system when a user signs up for a Group Campaign (campaign_group) that triggers:
- A transactional email message via Mandrill
- A Mailchimp interest group assignment

Fields needed for the payload:
- first_name
- uid
- email
- mailchimp_grouping_id
- mailchimp_group_name
- campaign_title
- campaign_link
- transactional_email_copy

Related issues:
https://github.com/DoSomething/dosomething/issues/1932
https://github.com/DoSomething/dosomething/issues/1895
https://github.com/DoSomething/message-broker/issues/55

**Comment by aaronschachter** [comment]
@DeeZone The `dosomething_signup_get_mbp_params` should either conditionally check for node type, or shoudl be split out into 2 separate functions.  Because the two payloads share a few variables, perhaps it makes sense to conditionally add the fields per type within this one function e.g. 

pseudo code:

```
$params = array(
  'email' => email
  'uid' => uid,
  'campaign_title' => $title
  etc...
); 
if ($node->type == 'campaign') {
  $params[step_one'] = field_step_one;
  $params[step_two'] = field_step_two;
}
elseif ($node->type == 'campaign_group') {
  $params[field_transactional_email'] = field_transactional_email;
}
```

You'll also see that `dosomething_signup_mbp_request` is set up to now only pass through the `campaign_signup` for campaigns only, so we'll need to add another case for a `campaign_group_signup`
