### ISSUE TITLE
Deployments not always reverting features

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1986]
Ran ds build stage, and features are overridden.

![screen shot 2014-05-06 at 11 17 37 am](https://cloud.githubusercontent.com/assets/1236811/2891352/b1a44906-d531-11e3-84e6-9208005011a4.png)

**Comment by angaither** [comment]
When there is no version number, it's pulling in the 'enabled' arg instead of the module name to revet.

```
DoSomething Campaign Group     dosomething_campaign_group     Enabled                   Overridden
 DoSomething Search             dosomething_search             Enabled                   Overridden
 DoSomething Settings           dosomething_settings           Enabled   7.x-1.0         Overridden
 DoSomething User               dosomething_user               Enabled   7.x-1.1         Overridden
vagrant@dev:/vagrant/html$ drush fl | grep 'Overridden' | awk '{print ($(NF-2))}'
dosomething_campaign_group
dosomething_search
Enabled
Enabled

```

**Comment by aaronschachter** [comment]
This is still occurring upon push to stage today.

![screen shot 2014-05-14 at 7 50 55 am](https://cloud.githubusercontent.com/assets/1236811/2972758/3878530a-db77-11e3-804d-f4ba1e462785.png)

**Comment by aaronschachter** [comment]
Logging into stage to revert via drush:

```
dosomething@staging:/var/www/beta.dosomething.org/current/html$ drush -y fr dosomething_campaign_group
Reverted dosomething_campaign_group.field_base.                      [ok]
Reverted dosomething_campaign_group.field_instance.                  [ok]
Reverted dosomething_campaign_group.variable.                        [ok]
dosomething@staging:/var/www/beta.dosomething.org/current/html$ 
```

Something up with the `ds build` script?

**Comment by aaronschachter** [comment]
Still occurs.  Pushed changes to add an instance of `field_primary_cause` to the `fact_page` node type.  The overrides are appearing in Strongarm.  Doesn't break things, but re-opening because this is a bug.

![screen shot 2014-05-27 at 3 50 10 pm](https://cloud.githubusercontent.com/assets/1236811/3096786/2d6d9c16-e5d8-11e3-9d86-d7c464daeca4.png)

**Comment by aaronschachter** [comment]
Same has occurred in adding a new field to Static Content per v0.2.69. Mostly around these variable defiintions / field_group sequences.

![screen shot 2014-05-29 at 12 32 08 pm](https://cloud.githubusercontent.com/assets/1236811/3120244/dc2bca08-e74e-11e3-9193-420cffaf34da.png)

**Comment by aaronschachter** [comment]
Our features are still overridden on production. I'd like to vote for changing our ds script to just `drush -y fra --force` to avoid manual intervention by devs upon every deployment.

**Comment by sergiitk** [comment]
Additionaly, I would also apply `--status=enabled` do [`drush fl`](https://github.com/DoSomething/dosomething/blob/dev/bin/ds#L168):
`drush fl --status=enabled | grep 'Overridden' | awk '{print ($(NF-3))}' | xargs -i drush fr {} --force -y`

It's unlikely that disabled feature is overridden, but still.

**Comment by aaronschachter** [comment]
What seems to happen in "Needs Review" is that a field base will be reverted, creating the tables (in this instance `field_created_by`), but then whatever reason the field instance is not reverted, so the field doesn't exist in the Campaign node.  I'm not sure what sets it to "Needs Review" vs Overridden but my suspicion is that a regular drush -y fra would fix this scenario.  QA was broken, ran a drush -y fra and QA is back.

**Comment by sergiitk** [comment]
Here's some more shell black magic
`drush fl --status=enabled | awk '$(NF-1) == "Overridden"  {print $(NF-3)}' | xargs -n1 drush -y fr --force`

**Comment by sergiitk** [comment]
On the other hand, i'd rather use `drush -y fra` instead. Reasoning:
- It follows module dependencies
- Without `--force` argument (simply `drush -y fra`) it's already reverts overridden features only:
  `--force Force revert even if Features assumes components' state are default.`
- `drush fl | grep ...` command eventually passes input to `awk` to determine a module name.
  It is very unsafe, its column number is not fixed.
  
  The command is trying to determine it relatively from the end `$(NF-3)` because from the start a column, containing module name (like `dosomething_campaign_group`) number may vary (due to feature title with spaces that considered as separate columns: "DoSomething Campaign GroupPrimary" is 3 columns).
  
  Moreover, even looking from end is not safe. A string may contain a status with space (like "Need review": 2 columns, but 1 expected) or even ASCII color sequences. All these are treated as separate columns by `awk`.
