### ISSUE TITLE
[Campaign Template] - More Facts About not showing up on action page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2036]
On production link to "More Facts" modal is not appearing (content there, link just not being rendered in Know It): https://www.dosomething.org/node/955/edit

**Comment by weerd** [comment]
So this turned out to be a really weird issue. I pulled in @angaither to take a look and we both tried a bunch of stuff but no luck. The `$modals['more_facts']` vars seems to be getting `unset` but we have no idea how or where...

@aaronschachter wanna take a crack at it?

This campaign https://www.dosomething.org/campaigns/pb-jam-slam definitely has _more facts_ but nothing getting output.

PS> Once you figure this out, gimme a holla cause it hurt my brain and I'm curious to know what the crap is going on!?!

**Comment by aaronschachter** [comment]
@blisteringherb This seems related to the modal template changes... any thoughts?
