### ISSUE TITLE
[Signup Data Form] - Old Person Modal Inconsistency 

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2159]
When an old person clicks on "Click here to order your Thumb Socks" the modal they get is visually inconsistent with other modals (i.e. no black bar at the top, no close button).

While you can close by clicking outside of the modal, this isn't evident to the user.

Would be great to see what it looks like with existing banner or normal banner with no text (although this may look weird). Are those are only two options? Could we alternatively hardcode a header in so that we don't have to add an additional field to the node?

@barryclark not sure if this is a bender or fender task. cc: @aaronschachter 

![image](https://cloud.githubusercontent.com/assets/6330971/2997511/0e348700-dd00-11e3-9dae-d5f041177d26.png)

**Comment by mikefantini** [comment]
pls update trello card when closed (just move to "To Be Verified" column https://trello.com/c/EicR38gQ

**Comment by aaronschachter** [comment]
This would be a bender task. Makes the code a little more complicated to keep a banner in, so kept it this super simple way for now (besides, since when do we care about old people?)

The two options for a headline would be to use existing Signup Data Modal header, or just have a standard "Sorry you'er old header". Or no headline, but I agree it won't look good with the dark header without any text.

**Comment by mikefantini** [comment]
going to think about this a bit more and consult with April... not a launch blocker we'll keep it as is for now.

**Comment by barryclark** [comment]
Not sure this matters toooo much. Any thoughts @dfurnes?

**Comment by DFurnes** [comment]
I just tried making the "x" on the modal gray rather than toggleable white/black as a test, and it seems to work okay. See DoSomething/neue#282 for some screenshots. If you guys think that looks okay, that'd solve the issue of the white "x" not showing up when we don't have a banner here.

/cc @crystalruthbell
