### ISSUE TITLE
Bug: Comeback Clothes confirmation page is viewable to anon users

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2163]
Minor bug. An anonymous user is able to hit Comeback Clothes reportback confirmation page without being logged in / signed up / reporting back. 

https://www.dosomething.org/node/362/confirmation

There's no harm in this but it still shouldn't be accessible.  Seems this only happens for comeback clothes, which means there must be a reportback for uid = 0.  This doesn't harm anything either but worth investigating how many reportbacks exist for uid = 0, and if they were created long ago (or recently - scary)

**Comment by aaronschachter** [comment]
Updated issue title - need to investigate instances of reportbacks where uid = 0 in prod data and see if this is replicable.

**Comment by angaither** [comment]
There is one reportback with UID of 0
This record was added before remote address was stored, so it set the UID to 0
![](http://cl.ly/image/3w3S2I3O2g26/Screen%20Shot%202014-05-19%20at%2010.58.24%20AM.png)

To fix, go into the mobile commons log and check to update the uid to match the drupal uid

**Comment by jonuy** [comment]
The last of the 4 pictures attached to that report back and the quantity and why_participated data seems to come from this person: https://secure.mcommons.com/profiles/166504057

I can't seem to find a drupal uid that matches someone with that number though. I'm guessing this indicates a bug where drupal accounts are created for mobile users, but it doesn't seem like it's happened for anyone else but this one person.

Either way, since no drupal account's been created for this person, how do you want to handle it?

**Comment by angaither** [comment]
Checked current beta app and legacy app, and yeah, there's no users with that phone number.
We will need to create a drupal user for this person. 
@jonuy do you have additional info about the person?

**Comment by jonuy** [comment]
@angaither Unfortunately, no. Just the phone number.

**Comment by aaronschachter** [comment]
The bad news here is that since then we've received some more anonymous reportbacks: https://www.dosomething.org/node/362/reportbacks?uid=0&mail=&flagged=0 but this should be fixed now by #2529 

The good news is that the Comeback Clothes confirmation page is NOT visible to anonymous users since https://github.com/DoSomething/dosomething/commit/671cc6bacd76892d4bde55e17a1bd33ef36ac883, which closes this issue.
