### ISSUE TITLE
iPad report back confirmation page is not loading

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2173]
User is getting some other page on the old app. Its all in this video, just jump to 6:45

**Removing link to user testing video. - Barry**

**Comment by aaronschachter** [comment]
This may because the user was testing on a day (4/30/3014) before these varnish rules were put into place: https://github.com/DoSomething/ServerConfig/pull/21

I tried to reportback on Supermarket Stakeout via the web.  First reportback form submit, I got an "website not found" error but I think it was because the internet died for me. Because on the 2nd submit it worked fine. Will test again with diff user, but can anyone else replicate?

Update: think the "website not found" was a fluke / internet connection. Works fine when testing with a 2nd user. if no one else can replicate, this should be closed.
