### ISSUE TITLE
Reportback: Flag as invalid

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2395]
`flagged_reportback` Flag for the Reportback Entity itself, to be used to exclude the Reportback from overall count.

Should use a confirmation form to allow editors to mark reason(s) for flagging, and also potentially provide a description for any more context.

**Comment by aaronschachter** [comment]
@mikefantini Per our conversation at standup this morning, do you want to list out a few values for a "Flagged reason" dropdown? Do we want to also add an additional textarea for editors to provide any more info?

**Comment by mikefantini** [comment]
@aaronschachter instead of a drop down could we do check boxes? I could see different content being flagged for multiple reasons and us wanting to treat content flagged for different reasons differently.

For instance, values that make sense:
- inappropriate
- irrelevant
- unrealistic output (open to better name... basically this is the b.s. category)

Rules that would make sense:
- for all tags - remove quantity from output quantity sum 
- for inappropriate and irrelevant - don't display images in the gallery
- for inappropriate - remove image from database

I think for now getting the check boxes set up and having the rule that if flagged, remove quanitity from output quantity sum makes sense.

Also in terms of text area that probably wouldn't hurt to start. Not sure how much people will use it but we can always remove if people aren't using it cause I could definitely see it being useful.

**Comment by aaronschachter** [comment]
Per convo I had with @mikefantini last week, I think it would make sense to have the Delete Files functionality as a separate dropdown (#2517), something like "Delete reportback files".. as a means to make it more of a conscious decision, and prevent editors from deleting files by mistake.
