### ISSUE TITLE
[SMS game] - weird redirect for campaigns/bully-text-0 on staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2401]
Deluca created http://staging.beta.dosomething.org/node/1229/edit so that we can put the SMS template through user testing.

However the view url (http://staging.beta.dosomething.org/campaigns/bully-text-0) is re-directing to http://staging.beta.dosomething.org/campaigns/sms-game-fun-great-success

This makes it hard to write proper content and impossible to put on usertesting.com

**Comment by aaronschachter** [comment]
Fixed this. when I created SMS Game Fun Great Success node at first, I created it with title "Bully Text" . 

when I changed the name to SMS Great Fun, our settings to automatically create redirects upon title changes created the redirect from "campaigns/bully-text-0" to the Great Fun game.

![screen shot 2014-06-02 at 2 35 25 pm](https://cloud.githubusercontent.com/assets/1236811/3152376/61d2b2fc-ea8d-11e3-953d-e2497e0cc148.png)

Fixed by deleting the url alias.
