### ISSUE TITLE
Reportback Form: Check for logged in user upon submit

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2443]
Nami just found an issue with PBJ where some of the report backs have no user attached. (e.g. https://www.dosomething.org/reportback/2976)

All of the report backs: https://www.dosomething.org/node/955/reportbacks?uid=&mail=&page=1

You can see at 17:21 today 4 report backs came in, that look like by the created/updated timestamps they may be updates to existing report backs? There's no users associated with any of them. 

PBJ is closing today, so we're expecting to get a LOT of report backs right now. 

---

[Frugs card](https://trello.com/c/FsbMuZIr/1176-pb-jam-slam-report-backs-w-o-uid)

**Comment by aaronschachter** [comment]
FYI - All the created/update will display as the same value because its currently just displaying the columns on the `dosomething_reportback` table and not updates to the `dosomething_reportback_files` table. e.g. https://www.dosomething.org/node/362/reportbacks?uid=1176550&mail=

**Comment by aaronschachter** [comment]
If this continues to happen, more files will be added to that one reportback 2976, the system will treat anonymous reportback submissions as updates to the reportback entity for uid = 0 nid = 955.  Not sure if https://github.com/DoSomething/dosomething/issues/1628 is related.

**Comment by aaronschachter** [comment]
i replicated by adding a reportback file to the uid = 0 reportback as follows:
- Signed in and loaded PBJ
- in a separate browser tab, sign out.
- go back to first open tab and submit a reportback
- you'll get a access denied error (because you're not allowed to see a campaign-campaign confirmation page unless you're signed in)
- as an admin, confirm a reportback has been created or updated for uid 0 for the node submitted.

This can be avoided by adding a check into the reportback_form submit function to make the user is signed in.

Pseudo code:

```
function dosomething_reportback_form_submit() {

if (!user_is_logged_in()) {
  drupal_set_message("Please sign in").
  return;
}

// Save reportback 

}
```

**Comment by aaronschachter** [comment]
Updated issue description.

**Comment by aaronschachter** [comment]
Confirmed this fixed on stage.
