### ISSUE TITLE
Make Drupal run faster on Vagrant  - Workflow?

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2444]
Based on **Make Drupal run faster on Vagrant** workflow section:

```
Workflow

Now you have two directories, with two different uses:

dosomething (Or whatever you called your GitHub repo when you cloned it): Use this to manage Vagrant.
dosomething-mount: Use this to write your code, manage git, etc.
```

During a `ds build --install` the following was displayed:

```
https://github.com/DoSomething/dosomething/wiki/Building-your-local-environment
[default] Unmounting SSHFS for `../dosomething-mount`
umount: ../dosomething-mount: not currently mounted
[default] Mounting SSHFS for `/var/www/vagrant` to `../dosomething-mount`
```

Currently my `dosomething-mount` is empty but everything else in the VB appears to be happy including http://localhost:8888. Searching HipChat it appears others were struggling with the workflow as well. What's the current setup to get to the point of being able to make pull requests?

Should `dosomething-mount` exist before `ds build --install`?

**Comment by aaronschachter** [comment]
I followed the steps on the page and I do see the repo files within my `dosomething-mount` directly.  

When i am in it and `git status`, it displays a ton of files as changed within the DS theme,  provision and scripts folders: https://gist.github.com/aaronschachter/9cdf3e007ac984de7014

The usual `dosomething` directory did not show any changes, and when I'd modify files, they'd show up as expected when I would `git status`.

**Comment by aaronschachter** [comment]
@DeeZone When i followed the steps in the [wiki page](https://github.com/DoSomething/dosomething/wiki/Make-Drupal-run-faster-on-Vagrant#create-mount-point) my `dosomething-mount` does exist before the install.

**Comment by aaronschachter** [comment]
Also, @mshmsh5000 not sure if you get this too, but when I run drush commands I get:

```
Directory /home/vagrant/.drush exists, but is not writable. Please   [error]
check directory permissions.
```

**Comment by deezone** [comment]
@mshmsh5000 Relative to @aaronschachter git comment, in my case:

```
[~/sites/dosomething-vagrant/dosomething-mount] $ git status
fatal: Not a git repository (or any of the parent directories): .git
```

```
~/sites/dosomething-vagrant/dosomething] $ git status
# On branch master
# Your branch is ahead of 'upstream/master' by 986 commits.
#
nothing to commit (working directory clean)
```

**Comment by DFurnes** [comment]
I was running into similar issues where `dosomething-mount` was not synced with my `dosomething` directory (and changes made in `dosomething-mount` were not being reflected on my localhost).

I (stupidly, perhaps) was thinking this was a conflict where it was still using the old non-SSHFS Vagrant configuration so tried a `vagrant destroy && vagrant up` in hopes of clearing that up. Now, both `dosomething-mount` and `/var/www/vagrant` are empty and my localhost doesn't respond. :(

Going to see if I can copy someone else's box to at least get back to where I was before.

**Comment by deezone** [comment]
@DFurnes Ah good point, I too did a `vagrant destroy && vagrant up``in the hopes of starting from scratch. The difference being`vagrant ssh`and`http://localhost:8888` are happy but I'm hesitant to start working out of:

```
dosomething (Or whatever you called your GitHub repo when you cloned it): Use this to manage Vagrant.
```

**Comment by DFurnes** [comment]
Update – Matt helped me out with some troubleshooting, after downgrading to Vagrant 1.5.4 and running another `vagrant destroy && vagrant plugin update && vagrant up`, everything looks to be working great. So if you're running Vagrant 1.6+, give that a try. :)

**Comment by deezone** [comment]
I'm running:

```
[~] $ vagrant -v
Vagrant 1.4.2
```

upgraded to:

```
[~] $ vagrant -v
Vagrant 1.5.4
```

and...
 :fireworks:  it worked! :fireworks:

**Comment by aaronschachter** [comment]
I am a lot closer, I just can't get of the Paraneue JS to run on my site, blocking me from working on anything modal and making my local a bit broken looking.

Even when I pull down from staging, I still get jQuery not found errors.  When I attempt to run `ds grunt` from within `/var/www/vagrant` I get this output: https://gist.github.com/aaronschachter/a6ade16b963bb3847fc9

I also get that output ^^ after running a `ds build` as well.

Theming issues aside here's how I got a lot closer:
- I was running Vagrant 1.3.5, so I've upgraded to 1.5.4.
- Removed my dsomething-mount for a fresh run through
- Ran a vagrant destroy and followed the steps again in the Make Vagrant faster wiki.
- Set up Sublime to open up from the command line (https://www.sublimetext.com/docs/2/osx_command_line.html) in order to open up the dosomething-mount directory, since it didn't show up when I went to Open a folder
- Changes are showing up in git status as expected

**Comment by aaronschachter** [comment]
@mshmsh5000 Where is the proper directory to run `ds pull stage`?  It doesn't seem to work for me anymore for files. I've tried from both `/vagrant` and `/var/www/vagrant` while being ssh'd in.

The error returned is:

ssh: connect to host staging.beta.dosomething.org port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]
Could not rsync from                                                 [error]
dosomething@staging.beta.dosomething.org:/var/www/beta.dosomething.org/current/html//
to /var/www/vagrant/html/

**Comment by deezone** [comment]
@aaronschachter 
- Run `ds build / pull` from `/var/www/vagrant`. 
- make sure you're running the specific version of Vagrant:

```
[~] $ vagrant -v
Vagrant 1.5.4
```

As newer and older version do not work based on @DFurnes and I's experiece detailed above.
- Confirm that your key is installed with `$ ssh-add -L` as your ssh connection error sounds like you've lost it. A common issue in the past for some of us. We had to keep re-adding with `$ ssh-add`.

**Comment by DFurnes** [comment]
@aaronschachter It looks like your Vagrant box didn't run Salt correctly, perhaps? It seems like the command-line utilities for Bower and Grunt are missing from looking at the log you posted.

I forget how to  trigger Salt manually, but try running a `npm install -g bower && npm install -g grunt-cli` and run `ds grunt` again. If that doesn't help, you can also run the following in the paraneue_dosomething directory on your own machine, rather than in the VM, to compile assets manually:

``` sh
npm install -g bower  # install Bower
bower update  # install Bower dependencies listed in bower.json
npm install -g grunt-cli   # install Grunt CLI
npm install   # install NPM dependencies for this project
grunt build # run Grunt build task to compile SCSS & JS
```

**Comment by aaronschachter** [comment]
So.. somehow I lost the vagrant-salt plugin. Back in action.
