### ISSUE TITLE
[Campaign Close] Entity reference on campaign node

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#2450]
When we have multiple campaign closes we need a way to determine which campaign run is the active run. 

We also need a way to view the past campaign closed references.

My recommendation is to have the campaign run keep the date that the campaign closes and both the campaign & the campaign run to have a [reverse reference](https://drupal.org/project/cer). 

This way each year the campaign lead is only making a new campaign run and doesn't have to worry about last year's node.

**Comment by aaronschachter** [comment]
One thought along this path could be that possibly in order to set the campaign's state to closed, an editor selects the relevant Campaign Run node from a new Closed Run Entity Reference field. That way, you can't actually close the campaign without setting the proper close run. Refs #https://github.com/DoSomething/dosomething/issues/2377#issuecomment-45218325

I haven't used https://drupal.org/project/cer ... would it only be for the sake of preventing editorial errors of selecting the references?
