### ISSUE TITLE
[SMS game] - weird right bumper of awkward space on Android

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2461]
Appears when the user clicks into the first name field. Watch this video at 5:35. 

**removed link to user video - Barry**

Not seeing it on my iPhone 5.

**Comment by weerd** [comment]
@mikefantini I tried testing this on Julie's android as well as a slew of android phones via Browserstack and could not replicate it. It may have been fixed during some update of mine or maybe when Dave updated the default page stuff and need to make some changes to the page structure. Otherwise not sure. Closing this for now. If it shows up again lets create a new issue ;)
