### ISSUE TITLE
[Campaign] Allow markdown in "After Copy" field

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2474]
To be more consistent with other fields in the "Do It" section of the campaign node, add the capacity for using markdown in the "After Copy" text area field to match the other text area items in that fieldset. Also will help with consistent tag output in the template.

**Comment by aaronschachter** [comment]
@weerd asked me to write up some documentation on how to do this.  
- We'll need to change the text format setting on the After Copy field through the Campaign Content Type's "Manage fields" UI -- this makes the change in the database.  
- After making that change, we need update the `dosomething_campaign` feature -- which applies the change into our codebase.

Here goes:
1. Run `drush -y fr dosomething_campaign` as a safety mechanism to make sure your DB and code are in sync.  The "FR" stands for features revert, so any overrides in your database to the `dosomething_campaign` feature (which there really shouldn't be anyway) will be reverted to whatever our exportables are set to in the feature code. 
2. Navigate to the Campaign's field list: http://dev.dosomething.org:8888/admin/structure/types/manage/campaign/fields
3. Edit the After Copy:
   http://dev.dosomething.org:8888/admin/structure/types/manage/campaign/fields/field_post_step_copy
4. Change the setting from plain text to filtered text.
5. Save
6. We should now have an "overridden" feature, where the field definition in the database does not match the definition in the code, since we've made a change to the field's text format.  To confirm, navigate to: http://dev.dosomething.org:8888/admin/structure/features/dosomething_campaign.  There should be an  overrides, tab where you can see the differences in text_format value.  If there are not, clear the cache and then confirm you see an overrides tab after.
7. Next, run `drush fu dosomething_campaign`. the FU actually stands for Features Update.  What this does is update the `dosomething_campaign` feature's files with the overrides present in the database.  This is why we reverted the feature in step 1 to begin with, to make sure the only change we're going to update is our text format change made in step 4/5.
8. Upon completion, a `git status` should show changes to the `dosomething_campaign` code.  There should no longer be an "Overrides" tab in the Features UI for Dosomsething Campaign.
9. Commit the code and revel in having taken a step closer to the dark side.
10. Will like need to make changes to the tpl now, filtered text is stored as an array.  Will want to output something like `print $after_copy['safe_value']` instead of `print $after_copy`

**Comment by weerd** [comment]
![joined the dark side](http://www.stargroup1.com/sites/default/files/uploads/the-dark-side1.jpg)
