### ISSUE TITLE
Campaign Runs - Report backs should be attached to campaign signups (?)

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2523]
This issue is not confirmed for build yet, but serves as a placeholder for discussion.

@aaronschachter's notes here: https://gist.github.com/aaronschachter/cf17cb60d820a6f02c5c

**Comment by aaronschachter** [comment]
The history here is that while we have a singular table of reportbacks for both web and mobile, we do not have a table that stores both mobile and web signups.

If there was one, it would make sense to associate reportbacks with signups.  We would then be only storing signups per campaign run, vs. needing to worry about the run for both signup and reportback tables.  This also makes for clean querying: wanting to find all users who signed up but did not reportback could happen within the single signups table.

Suggested course of action:
- For each mobile signup, create a record in signup table
- Update reportbacks to track what signup it belongs to

**Comment by angaither** [comment]
don't think we are going this route, closing (cc @aaronschachter)

**Comment by aaronschachter** [comment]
Makes sense not to re-engineer this in Phoenix if nothing is broken -- we do go this route in the Northstar API via the Campaign Activity object returned in `users/_id/:id/campaigns`. 

One thing to keep in mind if/when we ever look to support multiple Campaign Runs in Northstar -- it could be tricky since the current Phoenix process for archiving a Campaign updates the Campaign id of all of its Signups and Reportbacks to the closed Campaign Run id.
