### ISSUE TITLE
[Campaigns] Redirect Loop Error

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2583]
So Daniel brought this up to me earlier, but when you look up what seems to be either an unpublished or old campaign, you're given a redirect loop error. The campaign we were looking at was this. https://www.dosomething.org/campaigns/fight-fire-cookies
![campaigns bug](https://cloud.githubusercontent.com/assets/7773483/3314688/66d31978-f6f3-11e3-9239-3b5231e892f3.png)

**Comment by aaronschachter** [comment]
That's weird. Viewing this as an admin, this message is displayed:

> Oops, looks like this request tried to create an infinite loop. We do not allow such things here. We are a professional website!

Searching for this text in the repo is not giving me any results...

**Comment by apatheticslacker** [comment]
@aaronschachter Is the error message this? I got that as well when I was signed in. 
![infinite loop](https://cloud.githubusercontent.com/assets/7773483/3314819/cd419fa8-f6f4-11e3-9550-130db28e646e.png)

**Comment by aaronschachter** [comment]
Yep that's it.  It's being set by the Redirect module (hence not finding it in our repo)

http://drupal.stackexchange.com/questions/54813/path-alias-creates-redirect-loop-or-redirects-to-the-front-page

Labelling as a Bender task.

**Comment by aaronschachter** [comment]
This is another instance where a redirect has been created to itself, most likely because an editor changed the title from A to B, and then changed it back to A again (the system is configured to create alias redirects upon any title change)

![screen shot 2014-07-01 at 5 03 30 pm](https://cloud.githubusercontent.com/assets/1236811/3449245/72857430-0163-11e4-940f-cbcc7090912e.png)

I've manually deleted the redirect entry and this is no longer happening.
