### ISSUE TITLE
[SMS game] - if field_solution_support has copy it should be output

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2634]
Regardless of whether field_fact_solution or field_solution_copy is filled out, if field_solution_support is filled out it should appear on the view.

cc: @aaronschachter

**Comment by aaronschachter** [comment]
Related trello card: https://trello.com/c/W0mpUlPC

**Comment by mikefantini** [comment]
The only logic on whether to display one or the other pertains to field_fact_solution and field_solution_copy where we are only meant to display field_solution_copy if field_fact_solution is left blank.

This logic does not pertain to field_solution_support.

Another related trello card is https://trello.com/c/GTdAgTgE

**Comment by weerd** [comment]
Ok. We should probably update the descriptive text for the fields as well.

Description for **Solution Statement** field:
`"If you are not using a fact above, use this field. This is information that shows that the call to action is what to do to solve the issue. "`

Description for **Supporting Statement on the Solution**:
`"If you need more clarification on the solution statement. (i.e., "Last year, teens who got thumb socks were less likely to text and drive and more likely to ask others to stop.") "`

Which is why the logic implies that the statement only applies to the **Solution Statement** and not the **Solution Fact** which is a different field.

I can update the template logic. @aaronschachter is the description text available in the module for me to update that as well or just in the DB?

The description should probably read:
`"If you need more clarification on the solution fact or the solution statement. (i.e., "Last year, teens who got thumb socks were less likely to text and drive and more likely to ask others to stop.")"`

**Comment by aaronschachter** [comment]
You'll need to update the help text via features. Use the "Manage fields" for the Campaign content type for each field description you want to edit, and then run `drush fu dosomething_campaign` to update the feature files, and then add with git.

Before you make any changes though, run `drush -y fr dosomething_campaign` to make sure there are no unexpected overrides in your database that you'll be exporting when you run the `drush fu` command.
