### ISSUE TITLE
Add 2 column thumbnail gallery to static content pages

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#2646]
Hey all - we need this second gallery type to be available on the static content pages. I'm really excited because there are some great use cases for it...press page especially!

As a reference - sometimes QBs will use the standard gallery AND this gallery, the standard gallery OR this gallery, neither gallery or multiples of either. @mikefantini you had some toggling ideas? 

Holler with any questions!

**Comment by joolaay** [comment]
@barryclark there are 3 static content pages waiting on this. Can we get it assigned to a bender soon? cc  @mikefantini

**Comment by barryclark** [comment]
@tjrosario Did you already port the thumbnail gallery (I'm assuming that's the social gallery) into neue. Any update on the ETA of that? cc @DFurnes

**Comment by mikefantini** [comment]
hey sorry late to the game on this.. 

@julielorch so the way we have this set up now on campaign runs is that a user selects which type of gallery they want to display. Currently the options are Press, Celeb Mention, and Celeb in Action. Celeb Mention is the one that gets put into the two column display.

Does this "Celeb Mention" distinction work for you or are there any other gallery types you'd like to add that would have the two gallery display rule? 

We should maybe also then come up with gallery type distinctions for the existing galleries we have. Perhaps we could just set this as "General" for now rather than adding a ton of gallery types.

To get this set up on static content, we would also then need to add the "Klout Gallery" group it seems like. Although we may want to re-think that. @aaronschachter and @angaither will definitely have better ideas for implementing this than I can suggest.

Originally I was arguing for just the ability to indicate whether the gallery display should be two column or three which just seemed like the easiest to roll out across the site. I get why we want to store some things more specifically (i.e. Press) but worry, as we're potentially seeing now, that this could get overwhelming quickly.

**Comment by aaronschachter** [comment]
Meeting w @julielorch and @mikefantini:

We need to add a `field_gallery_style` field added to the `field_gallery`, which determines how a Gallery will be rendered (2 column or 3 column, or whatever styles we want).

The Gallery Type (Press, Celeb Mention, Action) is more around categorizing the type of data we're displaying.  We don't need to worry about it for Static Content -- it's a data point specific to the type of galleries we're creating within a Campaign Run node.

**Comment by aaronschachter** [comment]
@julielorch @mikefantini what should the options read as for the Gallery Style select list?

**Comment by mikefantini** [comment]
@aaronschachter let's go with:
- three column
- short three column
- two column

**Comment by aaronschachter** [comment]
Just to confirm: "three column" is the standard style that's applied now right?

Because none of these galleries will have a `field_gallery_style` value present, I suggest we build this such that if a value is not set, it defaults to "three column", assuming that's the style we currently have site-wide.  

So, we actually only need two options to choose from in the select list: the "short three column" and "two column".  Does that make sense?

**Comment by aaronschachter** [comment]
Also if we need any help text for this field, can you pls provide.

**Comment by joolaay** [comment]
Looks good to me. Help text "This gallery defaults to the standard row of three squares. For a row of three short rectangles, please use 'short three column'. For a row of two small squares with text to the side, please use 'two column'. Any questions, see Julie."

**Comment by mikefantini** [comment]
closing this as this is more of the parent issue for reference
