### ISSUE TITLE
Create Active Campaigns Endpoint

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2772]
The real-time dashboard crew would like an endpoint to get the currently active campaign nids.

@aaronschachter suggests to "configure a Views resource for services, and return the view that powers /campaigns" 
or
@blisteringherb 
"morgan said possibly just querying SOLR directly"... "use the view thats configured via apachesolr_views module (which i think is just an add on to the Views UI) or possibly just query solr directly."

**Comment by aaronschachter** [comment]
Any objections to just defining this as **GET** `api/v1/campaigns` ?

**Comment by deezone** [comment]
@aaronschachter @blisteringherb Does it make sense to add the "Services Views" https://www.drupal.org/project/services_views module to allow the use of views in service endpoints? I've created the view on my local, could it be as simple as pointing the view to a service entry?

**Comment by aaronschachter** [comment]
It's definitely a possible way we can implement it., that's what i was thinking along the first suggestion i had made in the comment above.. but we rarely use views on the site -- really only for /campaigns, which is where I hesitate on adding another module into the mix for just this single purpose....

I'd be tempted for us to create our own endpoint (The Drupalize me videos have great tutorials on this) and then use [views_get_view](https://api.drupal.org/api/views/views.module/function/views_get_view/7) to return the contents from it... whats the timeframe for getting this up and running?  If the main reason is for the dashboard, i lean toward us implementing our own resource vs adding the module (only because we don't use views anywhere else)

**Comment by deezone** [comment]
Currently the dash board project is using a scraping script of the front page of the production site to get the info they need. This takes care of their immediate needs but I think it would be a good idea to create a more robust solution for the long term. No rush but there's a need.

I'm guessing you're referring to the Drupalize me video: http://drupalize.me/videos/writing-custom-services-resource? If not, please provide a URL.

**Comment by aaronschachter** [comment]
Yip that's the video / series.

**Comment by deezone** [comment]
I'm working on building this. Expect a review request tomorrow (Friday). Interesting stuff!

**Comment by aaronschachter** [comment]
Closed by https://github.com/DoSomething/dosomething/pull/2974
