### ISSUE TITLE
[Global] Apply fallback images for callout arrows in IE8

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2814]
IE8 doesn't support `background-size` property, so the arrows on callouts aren't showing up. We need to provide some fallback images for IE8.

**Comment by weerd** [comment]
Seems like this is still a thing:

![image](https://cloud.githubusercontent.com/assets/105849/11311215/6820058c-8f9c-11e5-9880-cb618b4d388b.png)

@mikefantini @DFurnes not sure how much we care since IE8... but we're #global now...

**Comment by DFurnes** [comment]
IE 8 accounts for 0.31% of our traffic since August 1st according to Google Analytics. Personally, I don't think this is worth fixing.

**Comment by weerd** [comment]
@namimody any insight on global numbers w/ IE8? I vote to close as well, but wanted to just double-check!

**Comment by namimody** [comment]
@weerd as of June 2015:

Did some research on IE8 and while currently only 1.02% of sessions are on IE8 or below, the most reliable looking source I could find noted IE8 still has 16.04% of the global market share (desktop only). There are a couple of other sources that suggested worldwide usage was much less (around 3%), but these seem far less reliable. Because of this, I think we should continue to test on IE8 (esp for the likes of AGG) and then reevaluate DS site traffic a couple of months after the single site launch.

Current Traffic:
13.5% of all sessions since January have been on IE
Of those, about 75,300 were on IE8 or below. 62,000 were on IE8.
In total, 1.02% of sessions were on IE8 or below.
Global Browser Market Share:

**April 2015 (and seemingly the most reliable source):**
IE has 55.83% of the global market, and IE8 has 16.04% of the global market (desktop only).
In October, IE11 passed IE8 to become the world's most popular browser (largely due to Windows XP losing market share -- users on this OS can't upgrade past IE8).

**May 2015:**
Notes worldwide IE8 usage at 3.45%, but "other" at 19.85% without explanation. Not sure what would fill that....

**June 2015:**
Has IE8 usage hovering around 3%.
In May 2015, around 15% was attributed to "other" and in June that fell to 10%, but without explanation.

**Comment by weerd** [comment]
hmmm, alright. Good to know! Thanks for all the info @namimody :+1:

**Comment by namimody** [comment]
Sure thing @weerd!

I say we hold on this -- feel free to close. I'll put a reminder on my cal to look at GA at the beginning of Jan in case the single site has drastically changed traffic sources.

**Comment by weerd** [comment]
Righty-o!

**Comment by namimody** [comment]
Hello! Since Nov 8th, a hot .22% of traffic is coming from IE8. Not to worry :)
