### ISSUE TITLE
Automating Campaign Scholarships on /scholarships

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2825]
@angaither:

We want to make it so that /scholarships automatically updates our campaign specific scholarships.

Ideally for the "Campaign Scholarships" section it would pull in:
- hero image
- campaign title
- call to action
- link

for any campaigns that are active AND have a value set for field_scholarship_amount

I know you had worked on a prototype that did something similar. Thoughts on implementing that for realz? Otherwise that content will constantly be out of date.

cc: @julielorch @aaronschachter

**Comment by aaronschachter** [comment]
The prototype has been moved into a block which can be embedded into Static Content -- so this is pretty close to being done, it just needs to be themed.  

If we want it to look like the typical campaign block, using `campaign-block.tpl.php` -- changing the block to output those templates instead of a row may be all that's left to do. cc @angaither

**Comment by mikefantini** [comment]
@aaronschachter when you say "typical campaign block" you mean like we have on the finder and grouped campaigns?

**Comment by aaronschachter** [comment]
Yep thats what i was referring to.  I'm not sure if we use them on the Reportback Confirmation page too.. but can check.

**Comment by mikefantini** [comment]
Yeah we don't right now but we probably should.

I'm down for using this block again on on this page as well. @crystalruthbell do you have thoughts on this? Depending on what campaign specific scholarships we have live at any given time it may mess with your preferred # of campaigns for this block.
