### ISSUE TITLE
Technical Debt: refactor logo overriding.

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#2827]
Use drupal `logo` theme feature.
Reference: PR #2824

**Comment by mshmsh5000** [comment]
The reason to use `ASSET_PATH` here would be if we were concerned about versioning and asset caching: If the logo were something that could change often, then we'd prefer `ASSET_PATH` because that provides a built-in cache invalidation mechanism (the path changes with the version bump).

I don't think that's the case for `logo`; typically, we should be setting this once for each affiliate.

**Comment by angaither** [comment]
If we do this with the drupal `logo` we cannot set the default logo in neue. The actual logo file would need to be added to Paraneue.  this means that the logo cannot be served through the CDN. 
Unfortunately, the default logo path is set in core 

```
1465       // Generate the path to the logo image.
1466       if ($cache[$theme]['toggle_logo']) {
1467         if ($cache[$theme]['default_logo']) {
1468           $cache[$theme]['logo'] = file_create_url(dirname($theme_object->filename) . '/logo.png');
1469         }
```

We would have a logo in neue and a logo in paraneue. 

cc @DFurnes @aaronschachter

**Comment by mshmsh5000** [comment]
The default logo will be able to get served through Akamai once we integrate the [CDN](https://www.drupal.org/project/cdn) module or similar logic that allows us to specify a separate URL for assets. So don't worry specifically about CDN integration here.
