### ISSUE TITLE
User creation via Drupal Service

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2888]
When a user account is imported via a CSV supplied file (niche.com) a Drupal user account needs to be created via a service call to: `/user` (admin based user creation) or `/user/register` (anonymous user creation). The following needs to be available for the cURL call to work:
- [x] add a `source` field to user accounts that will be set when a user account is created via a service call rather than a typical user triggered form registration. 
- [x] Add a functionality to the custom resource to format the expected `source` field value to avoid the craziness that's seen in other standard service calls. An example being an anonymous user registration which requires:

```
{
  "field_first_name": {
    "und": {
      "0":{
        "value":"first"
      }
    }
  },
  "pass": "testpass",
  "mail": "test1@test.com",
  "field_birthdate": {
    "und": {
      "0":{
        "value": {
          "date": "06/06/1999"
        }
      }
    }
  }
}
```

**Comment by deezone** [comment]
@aaronschachter Thoughts on the `source` field being added to user accounts?

**Comment by aaronschachter** [comment]
I'm not opposed, we could potentially store this information as serialized data in the `data` property on the User as well, but creating a new field would be useful if we wanted to query.

**Comment by aaronschachter** [comment]
I'd name it something like User Registration Source... because naming it something too general like "Source" will be super confusing with regards to the Fact Sources field.

**Comment by mshmsh5000** [comment]
+1 on adding a Source field. Will come in all kinds of handy. And a no-brainer when we're talking about MongoDB.

**Comment by aaronschachter** [comment]
@DeeZone Open for discussion but re: the data in the User Registration Source, we may want to store this as a text field to make it easier. Maybe it just defaults to NULL for web registrations, since this field will be NULL for all Users to begin with.  And could get to set to something like `import_niche` for this batch, and `import_[source_name]` for other batch imports.  @angaither @mshmsh5000 thoughts?

**Comment by DFurnes** [comment]
+1 to using human-readable strings.

**Comment by aaronschachter** [comment]
@DeeZone Re the 2nd item, enabling `create` will not resolve this, `create` and `register` both call the same endpoint `_user_resource_create` which submits the User Register form. Since the `field_user_registration` will not be added to the registration form, this default Services endpoint won't cut it for us.  I believe our best bet here may to create a custom resource, which would resolve the 3rd item as well.

**Comment by aaronschachter** [comment]
Assigning to myself.  @DeeZone will keep you posted.

**Comment by deezone** [comment]
Huge thanks for all your effort on this item! Thanks also for your input on items 2 & 3 as it would have taken some head bang in my part before coming to your suggested custom resource solution. I've updated the issue description to match your input.

Ideally I can finish up all the parts in the Message Broker apps leading up to and after the user creation call and meet you in the middle if you're willing to take on the  custom resource build?

**Comment by aaronschachter** [comment]
The custom resource build is already done @DeeZone via #2894 .  Documentation for the custom resource is here: https://github.com/DoSomething/dosomething/wiki/API#users
