### ISSUE TITLE
School Finder endpoint CORS issue

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#3133]
The school finder endpoint isn't set to allow cross-origin access from our site, so we're getting errors on making AJAX requests. Two potential fixes that come to mind:
1. Set `Access-Control-Allow-Origin` on the [lofi-schools app](https://github.com/desmondmorris/lofi).
2. Put the API behind Varnish and set `Access-Control-Allow-Origin` header there. Side benefit of taking some load off the API for repeat requests.

/cc @mshmsh5000 @blisteringherb 

Related JIRA issue: [INF-42](https://jira.dosomething.org/browse/INF-42)

**Comment by blisteringherb** [comment]
Putting Varnish in front might be the quicker/easier lift and I agree there would be an added benefit to adding some caching.  I'm not sure where this app lives at the moment though.

**Comment by DFurnes** [comment]
@blisteringherb It's on Heroku. I can add you to the app if you have an account with them.

**Comment by blisteringherb** [comment]
I've added the changes to Varnish, but unfortunately it looks like Heroku doesn't support Varnish because it's using AWS's Elastic Load Balancer that changes IPs dynamically, and Varnish requires that you only have one IP.  https://discussion.heroku.com/t/proxying-heroku-app-with-varnish/123.  

I'm going to give adding this header to the lofi schools app a go so we can try to get this solved.

**Comment by DFurnes** [comment]
I think this is all working now. @blisteringherb Safe to close?
