### ISSUE TITLE
improvements to search results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3209]
Here are a few examples of searches that don't return ideal results
- when searching for "apply scholarships", /scholarships should be my first result, not 20th
- when searching for "Nancy Lublin", top results should be /about/our-team
- when searching for "donate", /donate should be one of the top results
- when searching for "animal testing", bully text shows up and displays this content, even though the term "test" isn't anywhere on the campaign page

![image](https://cloud.githubusercontent.com/assets/6330971/4723920/f1d94230-594b-11e4-88c2-57dc39d1449f.png)

I think one thing we may want to consider is removing the boosts for campaigns and instead have all page types be weighted equally.

**Comment by blisteringherb** [comment]
As I'm going through the examples it looks like the content itself may need to be tweaked to be more relevant in the search results.  I'll make notes as I go through on what I'm seeing and we can experiment with making changes.
-  when searching for "apply scholarships", /scholarships should be my first result, not 20th
  - The word "apply" doesn't appear at all on the /scholarship pages, so boosting by word proximity isn't working very well here.  We might want add something about applying on this page.  I've added a large boost to phrases that have terms within two words of each other which puts the FAQ page at the top because it has a question, "How do I apply for a scholarship?"  https://www.dosomething.org/about/faq
-  when searching for "Nancy Lublin", top results should be /about/our-team
-  when searching for "donate", /donate should be one of the top results
-  when searching for "animal testing", bully text shows up and displays this content, even though the term "test" isn't anywhere on the campaign page
  - For these three, removing the boosts to campaigns seems to fix the issue.  One thing we could do is to add some faceting so that users can filter the search if they're looking for campaigns.

**Comment by mikefantini** [comment]
All of these ones look good with one exception:

now when searching for Nancy Lublin the only result is Heart on your Sleeve

thoughts @blisteringherb?

**Comment by mikefantini** [comment]
this is resolved now
