### ISSUE TITLE
Campaign: Hide 'show end date' checkbox

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#326]

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to prototype GraphQL endpoints so that clients can make more specific requets for the type of info they want to receive.](https://trello.com/c/hTEYT9Q4/136-as-a-dev-i-want-to-prototype-graphql-endpoints-so-that-clients-can-make-more-specific-requets-for-the-type-of-info-they-want-to-)
