### ISSUE TITLE
remove data-validate='zip' attribute on address collection for international sites

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3329]
![image](https://cloud.githubusercontent.com/assets/6330971/4924160/b97cdd26-6520-11e4-909c-74c59445286c.png)

**Comment by DFurnes** [comment]
@mikefantini Removing `data-validate` on the zip code field will stop it from trying to validate based on US zip code rules. If UPS validation is failing, we'll need to remove that too.

**Comment by barryclark** [comment]
@sergii-tkachenko This seems like a really quick one to tackle when you're working on Canada schools/address functionality. Holler if you have any questions. 

Thanks @DFurnes!

**Comment by sergiitk** [comment]
@barryclark  Ok, I will fix this.

**Comment by aaronschachter** [comment]
@sergii-tkachenko I am still experiencing this error on the Canada site, on https://canada.dosomething.org/node/1227.

![screen shot 2014-11-06 at 4 49 14 pm](https://cloud.githubusercontent.com/assets/1236811/4944564/e4696c8c-65fe-11e4-8b4d-5c1b0a97456a.png)

I think that https://github.com/DoSomething/dosomething/issues/3344 will fix anyway though.. because we shoudln't have any validation at all

**Comment by aaronschachter** [comment]
Wait, I had to turn off the JS setting :smile:

**Comment by sergiitk** [comment]
Ups, forgot to do it by myself.
