### ISSUE TITLE
Admin interface to set message template values

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3464]
There are six common email template areas defined in the mb-general-v1-0 Mandrill template: https://mandrillapp.com/templates/code?id=mb-general-v1-0.
- *|SUBJECT|* (template setting)
- *|FROM|* (template setting)
- *|PREVIEW_LINE|*
- *|LOGO_LINK|*
- *|BANNER|*
- *|BODY|*
- *|TAG_LINE|*
- *|FOOTER|*

**UPDATE**
- create `dosomething_mbp_message_config` table to administer settings.
- include values as `merge_vars` in message request $params sent to `message_broker_producer`.
- use default values set in `/admin/config/services/dosomething-mbp` in the case where a `merge_var entry is not provided in $params in a`message_broker_producer_request()`.

**ORIGINAL**
- **In the case of core "Welcome (no approval required)" and "Password recovery" messages**
  The *|BODY|* and _|SUBJECT|\_ merge_var values will be by default defined by the admin configuration settings at `admin/config/people/accounts`. Updating the settings through the `admin/config/people/accounts` interface or through the `dosomething_mbp` admin interface will be the same. 
  - Both use the same system variable values. 
  - Both will support token replacement based on values supplied in the `dosomethng_mbp_request()` `$params` values which are translated to `$payload['merge_var'] values.
- **In the case of additional transaction type (`$source`), ie Campaign Signup and Campaign Reportback**
  - All `merge_var` values defined above will be maintained through an admin interface in `dosomething_mbp`.
  - System variables will store settings - prefix 
    - "`dosomething_mbp_transaction_<name>_subject`"
    - "`dosomething_mbp_transaction_<name>_from`"
    - etc.
  - each setting will support token replacement based on values supplied in the `dosomethng_mbp_request()` `$params` values which are translated to `$payload['merge_var'] values.

**Comment by aaronschachter** [comment]
@DeeZone I recommend we use a datatable defined in `dosomething_mbp` or `dosomething_settings` instead of numerous system `dosomething_mbp_transaction_<name>_subject"` variables.  I think it's going to be a lot cleaner, especially as we want to add more and more messaging (e.g. Just today its come up about wanting a Donation Form transactional).  

Sample schema:

dosomething_mbp_messages
- name
- subject
- fid_banner (Use a file upload widget)
- body

Then won't some variables always be global?  Like the sender, footer, link, etc?  For those, it makes sense to use the system variables on the module `system_settings_form`.

**Comment by aaronschachter** [comment]
Actually... couldnt it make sense to add these content-related fields to the existing `message_broker_producer_productions` table?

**Comment by deezone** [comment]
@aaronschachter I'm  going with the `dosomething_mbp_message_config` table as the `message_broker_producer_productions` table does not always involve  a transactional email message. The `merge_var` values are specific to email transactionals and what DoSomething.org's needs are.

Thanks for the input.

**Comment by deezone** [comment]
Do you think the "Welcome (no approval required)" and "Password recovery" message values via `admin/config/people/accounts` should be ignored in favour of values in the  `dosomething_mbp_message_config` table? Perhaps there should be a relationship maintained between the two?

**Comment by aaronschachter** [comment]
Yes, I think we should just create entries in the table and not use any of the default core stuff -- keep it all in one place.  It would make sense that the entries in the table have the same names that correspond to the entries in the `message_broker_producer_productions` table (which is why I thought it could work to add the fields there).  I'd imagine you'd never have an entry in the MBP Messages table that doesnt' exist in the Productions.

**Comment by deezone** [comment]
No longer relevant due to change in dev plans to support affiliate transactional messaging via Message Broker. New issue: https://github.com/DoSomething/dosomething/issues/3523
