### ISSUE TITLE
Settings: Markdown allowed tags

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#358]
Should only allow for `<ul>`and `<a>` tags.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to support multiple values for email/mobile field per user so that if a user has more than one active email, they are all associated with their northstar id.](https://trello.com/c/g1sRHPmC/140-as-a-dev-i-want-to-support-multiple-values-for-email-mobile-field-per-user-so-that-if-a-user-has-more-than-one-active-email-they)
