### ISSUE TITLE
In IE8, the user is unable to change photo.

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3866]
IE8/Windows 7 - I uploaded an image, was presented with the option to edit photo, but then nothing happens.

Seemed to work in IE9

**Comment by weerd** [comment]
So there is no edit window in IE8 and IE9 because they don't support the File API, so it defaults to the basic fallback implementation. Is the issue specifically for IE10? Otherwise this is the expected behavior in IE8 & IE9. 

I might be confused and could use some further clarification on this one.

**Comment by mikefantini** [comment]
@weerd so it looks like users are presented with the option to "change photo" after they have uploaded one in IE8 but it isn't working.

It seems like it's working on IE9.

Need to run but want to document what I've found so far.

**Comment by weerd** [comment]
Confirmed. Acting weird in IE8 on second click to change picture. Investigating!
