### ISSUE TITLE
Change photo button should pull up a file input and change the photo in the modal

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#3896]
When a user clicks on the change photo button, they should be able to select a file and the new file should pop into the modal and the new file should be submitted with the reportback. 

Need to investigate how we are going to update the reportback form with the new file selected since there are security issues involved changing the value of a file field on the fly.

**Comment by mikefantini** [comment]
we may want to prioritize this one a bit higher once we're on this milestone.

If the user goes to add an image, crops the image, and then selects done and then decides they want to change their photo they can't.

This is because clicking edit photo doesn't actually pull up the OS file system but instead just pulls up the modal.

I think I'm ok to launch with this working like this but it's probably something we should work on sooner rather than later after launch.

cc: @barryclark 

related trello issue: https://trello.com/c/e16Mc7lv

**Comment by sbsmith86** [comment]
@mikefantini @barryclark 

Two quick fixes could be
 1) When a user hits edit photo the modal opens, then they can click the "change photo" button which closes the modal, but there is no button to upload a new file. So we can just hide the edit photo button and reveal the "add photo" button when the click "change photo" in the modal.

2) Have the edit photo button pull up the file dialog, i just felt this was weird making the use re-upload a photo if they just wanted to edit the crop. 

Thoughts?

**Comment by mikefantini** [comment]
@sbsmith86 i think we keep it as is for now and just get this issue done of having the change photo link open up the file dialog. I think that will pretty sufficiently fix the issue.

But let's get this thing launched first and then tackle that (and by that, I mean this issue)!
