### ISSUE TITLE
Ability to edit crop after you see crop preview

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3915]

**Comment by barryclark** [comment]
Ref #3886

**Comment by sbsmith86** [comment]
This issue and #3891 should be fixed with the following pull request: https://github.com/DoSomething/dosomething/pull/3923

This pull requests makes various updates so that: 
- If a user uploads an image, fills out a caption, and clicks the "done" button, they see an edit button that allows them to edit the crop before submitting the whole form.
- If a user closes out of the modal without hitting the done button (by clicking outside of the modal, clicking the "change photo" button, or clicking the "x" button in the modal), they do not see a preview image but they still see the "add another photo button" so that they can re-upload and edit their photo.

@barryclark @mikefantini @weerd
