### ISSUE TITLE
PHP Notice Undefined #title

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4029]
@deadlybutter I think this is related to your preprocessing.

Notice: Undefined index: #title in theme_date_combo() (line 375 of /var/www/beta.dosomething.org/releases/20150220123716/html/profiles/dosomething/modules/contrib/date/date.theme).

**Comment by itsjoekent** [comment]
Looks like its probably either this line or the one after, https://github.com/DoSomething/dosomething/commit/e4a9634dbb1166bcc0b87db841e1e94f898d5415#diff-c7b97e9742cba6f342dab82a5fd21e64R281

~~after I get my vagrant back up and running ill test it out~~

**Comment by itsjoekent** [comment]
So the issue is this line, commenting it out fixes the problem  

https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/includes/form.inc#L282

The problem is, if you do that, this happens (this is why the variable was being unset) 

![screen shot 2015-02-23 at 3 29 46 pm](https://cloud.githubusercontent.com/assets/897368/6336485/eed904bc-bb70-11e4-9d6f-fc171fb6289e.png)

**Comment by aaronschachter** [comment]
Setting the `'#title'` to an empty string doesn't work?

**Comment by itsjoekent** [comment]
Welp. I feel like an idiot.
