### ISSUE TITLE
Signup Count helper variable

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4051]
Refs #3899

Create a helper variable to store the Campaign's current Signup count, to avoid running a live SQL count query every time we need it.

Per Hipchat convo with @mshmsh5000 the best solution would be:
- Upon campaign signup, increment the count variable for the campaign
- Schedule cron to refresh the variable for each campaign 2x a day, in order to fix any potential race conditions that could have borked the calculation

This incrementing / cron job implementation should also done for the Sum Quantity variable in #3899

**Comment by mshmsh5000** [comment]
Could also consider incrementing directly in Redis, since there's [a straightforward way to do that](http://redis.io/commands/INCR). The count could be incremented & referenced in Redis, and occasionally reset from the calculated total, which could be in MySQL.

One benefit from this is that a spike in signups won't cause a bunch of contention as this one row gets locked and written -- those will all be Redis INCR calls, much more scalable.

**Comment by sbsmith86** [comment]
@aaronschachter Do we need to do this one before #4288 ? That issue is really just for optimizely testing at the moment.

**Comment by aaronschachter** [comment]
@sbsmith86 responded in this thread https://github.com/DoSomething/dosomething/commit/dcf78e5f1dc363d9251761a60cd0ce623cc2d7e3

**Comment by angaither** [comment]
OKAY. after much IRL discussion today the goal for this is
.5 @joshcusano will add an `nid` row to the `overall.overall` table
1. Expose an endpoint from the Dashboard get this number DoSomething/dashboards/issues/37
2. Have a cron job run 1/day to (around noon) to get the updated number
3. Save that number as a local variable 

This number is the most accurate, since it's the de-duped total of both mobile and web signups

**Comment by mshmsh5000** [comment]
Sounds gorgeous :+1: :beers:

**Comment by angaither** [comment]
Leaving this issue open for now.

Currently implemented:
1. There is a signup count variable on the dosomething_helper_variable page on the campaign template.
2. That number is pulled from the total web signups
3. A cron runs every hour to update the number of signups within the past hour.
4. The number can be overriden manually (to allow for manual imports of mobile signups)

Left to build: 
Add a cron that updates this number from the Dosomething/dashboards/issues/37 repo

**Comment by angaither** [comment]
closing since dashboards have been down for a bit, and with data 2.0, this approach will probably change
