### ISSUE TITLE
rbid in the reprotbacks tab of campaigns needs to link to the admin view of the permalink

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4116]
on /node/[nid]/rb/reviewed the RBID column should link to the admin view of the rb permalink so that editors can quickly make updates to the status of individual reportbacks

![image](https://cloud.githubusercontent.com/assets/6330971/6509345/bc97b4f8-c32c-11e4-879a-0f609fc70545.png)

@angaither added this to the first milestone because we technically changed existing functionality and should update soon

**Comment by angaither** [comment]
@aaronschachter if I update that defaultURI will it break things? How can I override it so this page uses `/admin/reportback/[id]`

**Comment by aaronschachter** [comment]
Wouldn't we want it to default to the normal Reportback File's permalink though, as its set up now? There is no admin view of a Reportback File, only an entire Reportback, where you can review each Reportback File thru the Review Form.

The link is being set by the entity.tpl.php, as described here: https://github.com/DoSomething/dosomething/pull/4063#discussion_r25345487

**Comment by angaither** [comment]
sure there is, it's the flagging thing
![](http://cl.ly/image/0J0H0T3l3w1k/Screen%20Shot%202015-03-05%20at%2011.57.44%20AM.png)
vs 

![](http://cl.ly/image/2l101r0p2g1q/Screen%20Shot%202015-03-05%20at%2011.58.37%20AM.png)

**Comment by aaronschachter** [comment]
That admin link is not a permalink of a Reportback File, just a Reportback (displaying all its files).  The Reportback File needs its own URI (we saw that removing it in the ReportbackFileEntity broke things).

The review form already links to admin Reportback link (click the submitted timestamp). In order to remove the FID link, we'd have to override the entity.tpl.php for the Reportback File, or change the Reportback Review form to not return the Reportback File Entity's teaser, but instead a different theme function (which doesn't exist currently).  Does that make sense?

I think this would be simpler if we kept the Reportback File permalink the same as the URI. If the permalnk URL was something like `rb/[fid]` as is currently, if/when we add gallery functionality to viewing a reporbtack: could we switch out the [fid] in the address bar with JS ? SO the URL is changing from `rb/[fid1]` to `rb/[fid2]` instead of doing that with a query string (e.g. `reportback/[rbid]?fid=[fid1]`, `reportback/[rbid]?fid=[fid2]`) ?

**Comment by angaither** [comment]
using that `rb/[fid]` just seems wrong though, because you need things from the entire reportback, not just from that file.

**Comment by aaronschachter** [comment]
We can always load the Reportback associated with it.... this is being done in the full view of the Reportback File entity here: https://github.com/DoSomething/dosomething/blob/v0.4.22/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback_file.inc#L112

It's a 404 now because the `rb/[fid]` path was removed, but this view also displayed the impact from the Reoprtback.

**Comment by mikefantini** [comment]
@aaronschachter @angaither this issue is specifically for the reviewed tab of reportbacks. in the reviewed tab there is no hyperlinked timestamp.
