### ISSUE TITLE
original photo shows on confirmation page if user just updates submission w/o new photo

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4192]
steps to recreate:
- report back
- update your submission w/ a new photo
- update your submission a third time w/o a new photo

Do this and the original photo shows, which is slightly confusing. If this is more than like an hour to fix let's leave it, but if it's a quick fix, let's do it.

**Comment by sbsmith86** [comment]
@mikefantini @angaither This is sorta related to the issue I brought up in stand up about viewing a reportback and seeing the orginal file. You need to append the fid to the url to see the right one. So I _think_ this might be a bender task.

**Comment by angaither** [comment]
@mikefantini I just tried to replicate this and it worked as expected for me.
everytime you submit it should redirect you to the permalink page with the updated file id at the end. Perhaps the url you were looking at was without a query string?
If you view the reportback without a query string in it and have more than one image, it grabs the first image you submitted. 

If _that_ needs to change it's not a big deal, we can grab the last one submitted by default instead of the first submitted...

**Comment by sbsmith86** [comment]
@angaither Maybe it was becaues he updated the reportback without updating the image, so there was no new file id to append?

**Comment by angaither** [comment]
ahhhhhhhhh yes

**Comment by angaither** [comment]
@mikefantini So, would it make more sense to pull the most recent item submitted by default?

**Comment by mikefantini** [comment]
@angaither yeah I'd prefer to do that if it's easy enough.

**Comment by angaither** [comment]
:+1:
