### ISSUE TITLE
Campaign Sign-Up Event for SMS Games in GA

### ISSUE THREAD

**Issue by Bladt** [DoSomethingArchive/legacy-website#4355]
Need a new Google Analytics events that fires when a users successfully submits (signs-up for) an sms game form. 

Currently, sms-game sign ups are going uncaptured in GA. As we start to use tracking links for all marketing partners (including digital influencers) it would be beneficial to know which ones lead to high quality traffic/conversions. 

MF: assign as you see fit.

**Comment by mikefantini** [comment]
@angaither since you've been rocking GA events recently do you mind taking this one as well?

**Comment by angaither** [comment]
@mikefantini how important is this? I've been getting a bit behind on API work

**Comment by Bladt** [comment]
@mikefantini @angaither By end of month would be ideal. We are tracking conversions from traffic in monthly reports for the time being, so would love to be able to track for the complete month of May.

**Comment by angaither** [comment]
@mikefantini is this when people fill out http://staging.beta.dosomething.org//campaigns/sms-campaign that guy?

**Comment by mikefantini** [comment]
@angaither yup

**Comment by DFurnes** [comment]
Summary of an IRL conversation with @Bladt a minute ago –

We fire a `Form:Submitted` event whenever a form successfully submits, which you can probably use to figure out which percentage of users who hit the SMS form successfully submit it if you know the URL of the campaign you're tracking. 

One thing we can improve there is attaching the ID of the submitted form (in this case `#dosomething-signup-sms-game-form`) to the `Form:Submitted` event so that you wouldn't have to segment by URL.

**Comment by DFurnes** [comment]
@Bladt I just released a patched version of our validation package that correctly reports form IDs on form submissions/submission errors. You should see IDs in Google Analytics following the next deploy.

**Comment by DFurnes** [comment]
@Bladt You can see the [custom 'Form:Submitted' events](https://www.google.com/analytics/web/?hl=en#report/content-event-events/a493209w819276p798164/%3Fexplorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.eventCategory%3AForm%2Canalytics.eventAction%3ASubmitted/) registering in Google Analytics now. Successful SMS game signups are registered under the `dosomething-signup-sms-game-form` label.

Closing this issue for now. Let me know if you see any issues!
