### ISSUE TITLE
Change permalink Twitter share to be the Photo Card type

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4404]
This doesn't need to change the size of the image, it's just more performant to have them served through imagecache.

**Comment by mikefantini** [comment]
@sbsmith86 this and #4405 are so that for suspended for what we can have members share specific stories from their state.

Michaela is going to have a google sheet where users can find their state and will have a tweet speaking to a specific suspension that happened in that state.

example tweet: In AL black students are suspended 3X more than white @AlabamaDeptofEd #Suspended4WHAT https://dosomething-a.akamaihd.net/sites/default/files/Alexa_0.jpg

we want this to use the photo card from twitter https://dev.twitter.com/cards/types/photo

@angaither i'm not sure if using the akamai file vs. https://www.dosomething.org/file/103478 changes what you were thinking, but I don't think we can use the /file/ URL because users will then get 404'd if they try to clickthrough to it from the tweet.

**Comment by sbsmith86** [comment]
@mikefantini @angaither 

Just making sure I got all this down. 
- This issue is to create a new image cache preset so that each of these images can be served through a url like `sites/default/files/styles/300x300/public/images/ThumbWars_hero_square.jpg`? 
- Issue #4405 is to put metadata on that image page so that when the url is shared it looks like a twitter card? or is this the page we need to use `http://dev.dosomething.org:8888/file/2742`?

**Comment by angaither** [comment]
@sbsmith86 correct, I would test first, really quickly if you can add the correct metadata tags to image cached pages

**Comment by sbsmith86** [comment]
@angaither yea wasn't sure of that either. I will test it out.

**Comment by angaither** [comment]
@sbsmith86 at the very least we can check for `sites/default/files/styles` in the url of the page and add metatags based on that

**Comment by lkpttn** [comment]
Confirming that we should look at the photo card instead of the summary w/ large image card. That way we can get images into the timeline rather than just in expanded tweets.

https://dev.twitter.com/cards/types/photo

**Comment by sbsmith86** [comment]
Not sure if we are still doing this, but I don't think we are going to be able to get tags on the image url. It's not an html file that is being shown, it's a .jpeg, so there is no way to add meta tags. We can however add it to the file page in drupal, so something like `www.dosomething.org/file/{file id}`

**Comment by angaither** [comment]
@sbsmith86 yeah, but we 404 all those file urls for anon users.

**Comment by sbsmith86** [comment]
@angaither ooooo hmmm

**Comment by angaither** [comment]
@sbsmith86 so those image urls don't go thought `hook_preprocess_page` where most of the metatags are set, but we could get it from `hook_init` & checking the URL structure
I don't love that, but if we decide not to go the permalink route, we might need to do that....

**Comment by sbsmith86** [comment]
@angaither right, but it's not an html page, so where would the tags actually go?

**Comment by angaither** [comment]
@sbsmith86 wait, really? you can't even add headers to it?!

**Comment by angaither** [comment]
welllp

**Comment by sbsmith86** [comment]
yea pretty sure you can't do that since the browser is just rendering a .jpeg file at that point. Permalink might be our best/only bet here. Or, some other fancy solution.

**Comment by mikefantini** [comment]
@sbsmith86 @angaither @lkpttn let's go with the strategy of sharing permalinks rather than the akami files

**Comment by mikefantini** [comment]
so what we need to do is adjust the permalink twitter share to be https://dev.twitter.com/cards/types/photo. i'll update the description/title of this to reflect this

**Comment by mikefantini** [comment]
@sbsmith86 i'm seeing this when I share from production. Seems like something went wrong with the photo card implementation?

![image](https://cloud.githubusercontent.com/assets/6330971/7324532/41d823ee-ea85-11e4-998c-5c809b30b78a.png)

and when I click through to the individual tweet:

![image](https://cloud.githubusercontent.com/assets/6330971/7324554/6b52ff50-ea85-11e4-928e-2678c2ed9ae9.png)

**Comment by sbsmith86** [comment]
It's weird, I ran it through the card validator and the image is 404ing, but the image definitely exists. 

https://dosomething-a.akamaihd.net/sites/default/files/styles/480x480/public/reportbacks/7/uid_2137661-nid_7-0.jpg?itok=mdUJej_T

Maybe it's the akamai url that twitter doesn't like?

![screen shot 2015-04-24 at 2 00 34 pm](https://cloud.githubusercontent.com/assets/1700409/7325164/6bb0545c-ea8a-11e4-9a56-6b986c204453.png)

**Comment by mikefantini** [comment]
hmm yeah weird. the previous card was definitely showing images still so seems weird that this would be different

**Comment by sbsmith86** [comment]
alrighty, this should be fixed on staging now. 

![screen shot 2015-04-24 at 4 36 02 pm](https://cloud.githubusercontent.com/assets/1700409/7328035/17186932-eaa0-11e4-8750-1453d016ce45.png)
