### ISSUE TITLE
Modal flow prototype

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4417]
Create a prototype of a new modal flow that allows us to take a user from one screen to the next without a page reload or opening a new modal. 
- Example sign up flow: An anon user hits "sign up" button, a modal opens to allow them to login/register. When they hit login, they are signed up for the campaign, and brought to a second screen in the modal that allows them to share.

cc: @mikefantini @DFurnes

**Comment by DFurnes** [comment]
Woot woot!

**Comment by DFurnes** [comment]
Some questions raised at our check-in earlier this afternoon:

**How do we trigger the second modal on the backend?**
Because the login modal has side-effects (and depending on whether the user entered the right login/register information, may not be successful), we can't know for sure the contents of the second modal at page load.

The simplest solution seems to be dynamically loading either the second modal OR a login error page (using a [pjax](http://pjax.herokuapp.com)-like technique or using an `<iframe>`). Is it possible to get Drupal to return a different "partial" from the form submission depending on the campaign/submission status?

**How do we make sure this only happens on the "Sign Up" pitch page login, not all login forms?**
Currently, we use the same login/registration form for both the "Sign Up" button and the "Log In" button in the navigation bar. This means that users clicking the "Log In" button will also be signed up for the campaign though (see #2580) & be presented with the share or signup data form, which is like _rather surprising_ from a UX perspective.

Does it make sense to fix this by separating the signup form from the login form?

/cc @angaither @mikefantini

**Comment by angaither** [comment]
@DFurnes I think we can separate the login/signup forms but it might be kind of complex, since the sign up form still needs to act as a login form for unauthenticated users.

**Comment by DFurnes** [comment]
Follow-up on this from an offline discussion the other day –– this may be something that's worth revisiting if/when we refactor our Drupal login system to use Northstar (instead of Dr00p's stock authentication).

**Comment by DFurnes** [comment]
References #1289.

**Comment by angaither** [comment]
going to close this for now, we can revisit in vLater (when NS is our auth system)
