### ISSUE TITLE
IE 8 issues on campaigns template

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4430]
- [ ] modals on the action page aren't appearing. This is an issue because One in Three of Us launches on Friday with address collection that opens as soon as a user signs up for the campaigns. This modal does not open either after signing up or if clicking the link the Stuff You Need. Also all other links for FAQs, etc. do not open up either on the page.
- [ ] the tips in the do it section are not appearing:
  ![image](https://cloud.githubusercontent.com/assets/6330971/7372730/776d9f3e-ed96-11e4-83c8-0d6bda171fb0.png)

**Comment by DFurnes** [comment]
The issue seems to be caused by a call to [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) in the validation module's transpiled source. Not _entirely_ sure why that line is being introduced, but it's an easy fix.

![screen shot 2015-04-28 at 12 42 56 pm](https://cloud.githubusercontent.com/assets/583202/7375093/4f983baa-eda4-11e4-8409-f0b1391f88a3.png)

**Comment by DFurnes** [comment]
@mikefantini I've got an open pull request with a fix, tested on my local environment. I'll let you know when it's ready for re-testing on stage!
