### ISSUE TITLE
Goal share buttons

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4447]
Add twitter, facebook, and tumblr share buttons to the campaign template that share the goal statement.

**Comment by mikefantini** [comment]
meeting with Felicia and @lkpttn on Monday to review exactly what we'll be pulling into the shares. will update this after that meeting.

**Comment by mikefantini** [comment]
@lkpttn please add final mocks of what this should look like here for the first implementation.

**Comment by mikefantini** [comment]
also @sbsmith86 please advise if there are any updates to the copy we can include on FB shares

**Comment by mikefantini** [comment]
we also want to add UTM parameters to the links we use in these shares:

source = dosomething
medium = social media site (i.e. facebook, twitter, tumblr)
campaign = hot_share
so instead of the URL being https://www.dosomething.org/reportback/59985%3Ffid%3D78683?fid=78683 it'd be:
- https://www.dosomething.org/reportback/59985%3Ffid%3D78683?fid=78683?utm_source=dosomething&utm_medium=facebook&utm_campaign=hot_share for Facebook
- https://www.dosomething.org/reportback/59985%3Ffid%3D78683?fid=78683?utm_source=dosomething&utm_medium=twitter&utm_campaign=hot_share for Twitter
- https://www.dosomething.org/reportback/59985%3Ffid%3D78683?fid=78683?utm_source=dosomething&utm_medium=tumblr&utm_campaign=hot_share for Tumblr

The goal of this is to get better tracking of a. how users are getting to our site and b. which sources of traffic convert most effectively.

related to #4575 and #4610 and #4611

**Comment by sbsmith86** [comment]
@mikefantini @lkpttn So yea, looked into it. We have control of the "caption" and "description" that shows in the post. See below for an example of what the caption and description are. 
![screen shot 2015-07-01 at 10 49 33 am](https://cloud.githubusercontent.com/assets/1700409/8457398/22a4cf88-1fdf-11e5-99d8-dabcd0df3686.png)

**Comment by mikefantini** [comment]
and @sbsmith86 we can control this without messing up what gets shared it someone just straight posts the URL into a FB status?

**Comment by sbsmith86** [comment]
@mikefantini yea, we would pass them as custom params to the facebook feed dialog intent link.
