### ISSUE TITLE
Set animation file status to 1 when saved

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4461]
When animation files are uploaded and saved on the campaign configuration page, they have a status of `0` in the database so they will be removed when the next cron job runs. So we need to work out a way to set the status to 1. 

/cc @aaronschachter @angaither

**Comment by aaronschachter** [comment]
I believe this unfortunately needs to be done via a custom submit function for the form, where we manually save the file and set it status to 1 (similar code to the user submitted Reportback form).

It might make sense to strip out the Animation variables into their own Drupal Form function, to keep all of the other variables in the `system_settings_form`.

**Comment by aaronschachter** [comment]
Actually, second thought. What we used to do for the Alt BG file field on campaigns was have a text field where we'd manually enter the File fid (see #4382).

Since only admin's will be uploading these files, this approach would be a lot less code for us. It just means the files need to be uploaded and set to permanent manually: https://github.com/DoSomething/dosomething/wiki/Site-Guide#uploading-files

**Comment by mikefantini** [comment]
yeah +1 to this @aaronschachter

**Comment by sbsmith86** [comment]
@aaronschachter Oh sweet, that is easy enough. Looks like we also do that for default reportback images, so I will follow that model.
