### ISSUE TITLE
Under 13 User Flow

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4514]
Trello: https://trello.com/c/0movvETM/1376-under-13-account-sign-ups
Related: Issue #932 and Issue #931

**Users who are under 13 years old should:**
- be allowed to register for the site
- be given user accounts
- have their information stored in our database
- receive appropriate transactional emails
- should NOT have their information passed to MailChimp
- should NOT have their information passed to Mobile Commons

**User Examples:**
UID: 2389099

User showed up in Mailchimp (unsubscribed on May 6)
User never gave mobile number, so not in Mobile Commons.
For context, they are signed up for many campaigns - it is unclear how they initially joined DS.
++++++++
UID: 2392236

User shows up in MailChimp.
User entered in Mobile Commons and would receive next weekly broadcast.
For context, they are signed up for Comeback Clothes - it is unclear how they initially joined DS.
++++++++
UID: 2748641 (Nami test account)

User does not show up in MailChimp.
User receives transactional emails for signing up/reporting back for a campaign.
User entered in Mobile Commons and would receive next weekly broadcast.
For context, this account was created by clicking "log in" in the top right corner of the site, and on Chrome.
++++++++
UID: 2748914 (Nami test account 2)

User does not show up in MailChimp.
User never gave mobile number, so not in Mobile Commons.
For context, this account was created by signing up for Support Board on Safari.

**What Needs to Happen:**
- Under 13 users should consistently not be added to MailChimp
- Under 13 users should not be added to Mobile Commons

**Comment by mikefantini** [comment]
user 2392236 has been opted in to the general Mobile Commons subscription list AND into individual campaign specific subscriptions (see subscriptions table on https://dosomething.mcommons.com/profiles/173868141)

interestingly user 2748641 was created in Mobile Commons but was not added to any specific subscription lists. I would have expected her to be signed up to Do Something Master campaign as a General DoSomething Web Sign Up https://dosomething.mcommons.com/campaigns/5091/opt_in_paths/164905.

**update**: this user signed up for a campaign that is tied to a mobile commons opt-in path that has ended, which would explain why she was not added to any specific subscription lists https://dosomething.mcommons.com/campaigns/130689

anyways, if a user is under 13 s/he should never be passed into Mobile Commons or MailChimp

@angaither do you mind taking a look at this?

**Comment by mikefantini** [comment]
did a little more digging...

created user 1704889 on staging. that user is properly flagged as being "under 13".

when I just created an account for her from the homepage (not associated with any campaigns) everything worked properly (i.e. she was not added to Mobile Commons and therefore did not receive the new user text).

however, when I signed up for http://staging.beta.dosomething.org/campaigns/another-test-campaign which has an opt-in path associated with it through http://staging.beta.dosomething.org/admin/config/dosomething/opt_in the user was added to mobile commons and received the corresponding text.

mobile commons profile: https://dosomething.mcommons.com/profiles/176933128

that user also got added to MailChimp, but not sure if that was from general registration on a delay or because of the MailChimp Group associated with node 1617 on staging.

MailChimp profile: https://us4.admin.mailchimp.com/lists/members/view?id=64934941

for debugging purposes, it would be sweet if the MailChimp account creation happened because of the MailChimp group associated with node 1617 because that would seem to indicate that the campaign specific MailChimp/Mobile Commons opt-ins are ignoring the Under 13 flag.

**Comment by mikefantini** [comment]
for comparison, http://staging.beta.dosomething.org/user/1704890 signed up for a campaign that isn't tied to a specific MailChimp group (http://staging.beta.dosomething.org/campaigns/space-jam) and is not in MailChimp

**Comment by mikefantini** [comment]
i feel pretty confident that this is related to users signing up for campaigns that are connected to specific opt-in paths on https://beta.dosomething.org/admin/config/dosomething/opt_in

every user under 13 that we've found is tied to a campaign specific MailChimp Group or Mobile Commons opt-in path

**Comment by itsjoekent** [comment]
so far looks like Fantini is right, this line is why normal registration doesn't add under 13 members to messaging. https://github.com/DoSomething/dosomething/blob/5420d81df9cad01d0fe8a645fffedb503c1e303c/lib/modules/dosomething/dosomething_user/dosomething_user.module#L425

guessing this function isn't used in optin paths, going to check for that next

**Comment by angaither** [comment]
we should just be able to call that `under_thirteen` function before adding those kiddos

**Comment by itsjoekent** [comment]
yep, just finding all of the places where we forget it. I think this is one of them https://github.com/DoSomething/dosomething/blob/c6bd118d3c995011efb56b20604616d1ef10cb3d/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L516

**Comment by angaither** [comment]
:+1: yeah, there's probably a couple places in there

**Comment by mikefantini** [comment]
ok so i can confirm that under 13 users are no longer going into MailChimp and Mobile Commons.

However, under 13 users are no longer getting transactional emails either.

@marahml are you cool with that?

**Comment by marahml** [comment]
yes, totally cool with those users not getting emails - and think it better protects us for coppa law.
