### ISSUE TITLE
Forward campaign activity to northstar

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4571]
When a user signs up and reportsback on a campaign, forward that data into northstar

**Comment by angaither** [comment]
@chloealee

**Comment by chloealee** [comment]
just chatted with @uy and thought of a possible solution - since Northstar already has a signup/reportback endpoint that forwards information onto Phoenix, make Phoenix web submissions go through Northstar instead of straight into it's own database. @angaither @weerd would love your insight if this is the best way to proceed!

**Comment by angaither** [comment]
I'm not sure if we are quite at the point that we can remove drupal as a backend for these requests

@DFurnes might have more input on this when he returns...
but another possible solution is I have a [message broker campaign activity repo](https://github.com/DoSomething/mbc-logging) that takes campaign signups and reportbacks and stores them in mongo. since we already queue everything with mb, that might be a good thing to hook into and pass things into northstar

**Comment by chloealee** [comment]
@angaither awesome, thanks! Should I get started via that direction or wait for Dave's input?

**Comment by DFurnes** [comment]
Chloe & I just talked this over IRL. We're thinking the best course of action would be to try to mirror how we deal with users and see if we can create a synchronized copy of all this data in Northstar. The mobile app will only have a subset of campaigns so this hopefully shouldn't be _too_ heavy of a dataset, since I think we're still uncertain whether campaign activity should live in the user documents...

**Comment by chloealee** [comment]
I just noticed that there is already a check to see if a campaign signup already exists [here](https://github.com/DoSomething/northstar/blob/dev/app/Http/Controllers/CampaignController.php#L119) so I don't think we'll actually run into the infinite loop between ns and phoenix.

Another question I forgot about that we ran into when first discussing is creating a new function that forwards the signup from phoenix to drupal - to hit the `POST user/campaigns/:campaign_id/signup` endpoint, I'll need the session token in the header. To get this, will I have to sign in the user via the `POST /login` endpoint first? That seems a little messy though.

**Comment by chloealee** [comment]
@angaither @DFurnes whenever you get a chance for the above!

**Comment by chloealee** [comment]
@angaither @DFurnes the only other thing I can think of is to maybe update the `signup` function in the Campaign Controller to first check if there is a session token and if so, validate the request body, else sign user in?

**Comment by DFurnes** [comment]
We just talked about this IRL. We're thinking the best course forward is to add a new `POST forwardSignup/` endpoint that requires an "admin" Northstar API key and accepts a `source` and `signup_id`. This solves the issue of all the back-and-forth between Drupal and Northstar when trying to do this through the existing `POST /signup` endpoint.

**Comment by chloealee** [comment]
@DFurnes A question already! I'm trying to wrap my head around the new endpoint. All makes sense to me except I'm having trouble understanding how we know which user we're talking about to sign up for the campaign. 

Would an example of the endpoint would be `POST /campaigns/:signup_id/forwardSignup`? Then how would we know which user we want to sign up? Unless we did something like `POST /users/:term/:user_id/campaigns/:signup_id/forwardSignup`?

**Comment by DFurnes** [comment]
I think the most "correctly" RESTful way of doing this would be to add a new optional parameter `signup_id=###` to the `POST /campaigns/:campaign_id/signup` endpoint, and then use the current user's authenticated session (storing those session keys on the user object in Drupal like we'd chatted about). If the signup ID is explicitly provided, then we can infer that we don't need to talk to Drupal about it and skip all that business.

_That being said_, I also don't think it'd be a bad idea to just make a new `POST /forwardSignup` endpoint that just accepts a `user_id`, `signup_id`, and `campaign_id` as parameters since this is a sort-of temporary measure to try to get these two places in sync.

**Comment by chloealee** [comment]
ohhh I see what you are saying now, making these the parameters instead of apart of the endpoint! Makes so much more sense, thank you!

**Comment by chloealee** [comment]
hi @DFurnes ! Another road block. Since we last chatted IRL, we decided to use the `POST /user/campaigns/:campaign_id/signup` endpoint after all. 

Doing so on the phoenix side, we'd save session data to the user object in drupal and check if there is a session token and if not, sign the user in via the `POST /signup` endpoint. Then we'd move on to the `POST /user/campaigns/:campaign_id/signup` endpoint to sync the campaign activity. 

With the `POST /signup` endpoint, I'm now realizing that we need the email/mobile and password, which would mean yet another ns call, but I'm not sure we can get the user password through any of the endpoints right now. 

I'm thinking we should maybe just build out the `POST /forwardSignup` endpoint after all and update the logic in the signup function in ns? Let me know if I'm confusing this way too much in my head!

**Comment by DFurnes** [comment]
Oh, hmm. Yeah, that seems like it gets complicated... :+1: moving forward with `forwardSignup`.

**Comment by chloealee** [comment]
awesome, thanks Dave!

**Comment by chloealee** [comment]
@DFurnes here are my branches that have the code to sync signups! Last time I was working on this, I was double checking that I was sending the correct information from phoenix to the mobile app so just flagging that. Otherwise, signups sync should be functional and just need to sync reportbacks now. Thank you for wrapping this up!!!

https://github.com/chloealee/northstar/tree/user-activity
https://github.com/chloealee/dosomething/tree/user-activity

**Comment by angaither** [comment]
going to request the data from here instead
