### ISSUE TITLE
Tumblr Sharing from Permalink on IE 8

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4574]
TSG reported, DS verified. Pop up window opens but nothing ever loads.

Windows 7 / IE 8

**Comment by mikefantini** [comment]
@sbsmith86 marked as low priority since our IE8 traffic currently is pretty tiny and this is a pretty specific use case (being on IE 8/reporting back/sharing on Tumblr specifically), but if you have some downtime and have a second to check out this bug that'd be great.

Might just be browser stack acting funny?

**Comment by namimody** [comment]
Closing this actually -- it shows eventually! Just takes a hot 5 mins. Sorry!
