### ISSUE TITLE
members are not being subscribed to new campaign specific groups in MailChimp

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4595]
The following groups were created Sunday May 31st in MailChimp and were hooked up via https://www.dosomething.org/admin/config/dosomething/opt_in.
- Mic Check (nid 53)
- Thumb Wars (nid 1508)

However, those groups currently have zero subscribers in MailChimp. Users who sign up for these campaigns are still going into the general Do Something Members list in MailChimp, just not the campaign specific groups.

Mobile Commons seems to be working fine.

I Heart Dad (nid 13) seems to not be adding new members either, however there are around 12,000 subscribers in that group.

cc: @namimody @ArielSD @sheydari-ds @DeeZone

**Comment by namimody** [comment]
A couple other pieces of information:

Ariel figured out the reason people are in the I Heart Dad Mailchimp group: when a broadcast was sent out for Backseat Adviser, a keyword mixup caused people to be opted in to I Heart Dad during the flow. Because this was a broadcast, all were existing members (who seemed to have email addresses attached to their accounts) and therefore now appear in Mailchimp.

1 in 3 of Us has subscribers in MailChimp as well, but my email nami098@gmail.com (signed up on Friday) and Fantini's mfantini+micheck@dosomething.org (signed up today) have not been added to the group. 1 in 3 of Us may have subscribers for a similar reason as I Heart Dad -- if many existing members signed up for the campaign via text, they would have been added to the Mailchimp group directly regardless if the opt-in path on site was working or not. Checking with Sarah to see if their might be a reason for this -- but could that be the reason @mikefantini?

**Comment by mikefantini** [comment]
@namimody i don't believe that this would account for people showing up into that MailChimp group, but can you test by texting in an opt-in term for a campaign that also has a MailChimp Group set up?

**Comment by namimody** [comment]
@mikefantini I had Micah text in "1in3" to 38383 and her # showed up in Mobile Commons, and then she texted RESPECT and her email did not show up in Mailchimp, but moved correctly to the next group in Mobile Commons.

I texted in RESPECT directly, and my email was added to the mailchimp group, and my # was added to the second mobile commons group.

**Comment by deezone** [comment]
@mikefantini Reviewed the :
- Mic Check (nid 53)
- Thumb Wars (nid 1508)
  MailChimp interest groups. There was a small backup of the related queue due to the dev / bug fixing work this morning. Everything is back to normal with the MailChimp interest group populating as expected.

**Comment by namimody** [comment]
Just to follow up -- checked with I heart Dad and 1 in 3 of Us today -- all working. Closing!
