### ISSUE TITLE
Guzzle fails locally

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4616]
`GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 162 of /var/www/dev.dosomething.org/html/profiles/dosomething/libraries/guzzle/src/Handler/CurlFactory.php).
The website encountered an unexpected error. Please try again later.`

**Comment by mikefantini** [comment]
yeah this is happening on staging too fwiw

**Comment by sbsmith86** [comment]
@angaither Was working on #6170 and it looks like this error was happening because we were using 

`'base_url' => array($base_url . '/{version}/', array('version' => $version))` 

but it should be `base_uri` and the value has to be a string, but it looks like it was trying to assign it to an array to do the string replacement. 

Reference: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client

Anyway, guzzle seems to work for me locally when I create the client correctly. So it seems like we just need to fix that stuff up in the Northstar module.

**Comment by angaither** [comment]
@sbsmith86 ahh, awesome
