### ISSUE TITLE
enhanced FB/Tumblr share for hot module

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4643]
enhancement over #4447 this issue is to include the below image as the photo in FB/Tumblr shares

![image](https://cloud.githubusercontent.com/assets/6330971/8456336/be42799c-1fd8-11e5-9dc3-27fb971527e2.png)

this image would need to be updated as cron runs so that it shows updated numbers

**Comment by DFurnes** [comment]
Follow-up from our meeting this morning. I tried testing Facebook's caching by changing the header image on the test campaign on the website (while making sure to keep the file name exactly the same). They do seem to cache the images when loading them through their proxy:

![screen shot 2015-08-25 at 2 12 32 pm](https://cloud.githubusercontent.com/assets/583202/9475225/5efd89be-4b33-11e5-8d0f-59220359e67f.png)

**Comment by DFurnes** [comment]
From the expires header on the image that Facebook serves up, it looks like the cache lasts for 24 hours.

```
Expires Wed, 26 Aug 2015 18:25:12 GMT
```

This is backed up by a [Stack Overflow answer](http://stackoverflow.com/a/15682504) I found.

**Comment by DFurnes** [comment]
Testing the page in the [Open Graph Debugger](https://developers.facebook.com/tools/debug/og/object/) does allow me to manually bust the cache and update the images. When I hit the button to "fetch new scrape information", it shows the updated kitten in the debugger:

![screen shot 2015-08-25 at 2 30 27 pm](https://cloud.githubusercontent.com/assets/583202/9475634/e265427c-4b35-11e5-95af-9b6b0310131d.png)

Hoooooowever, that **doesn't** seem to have updated the images on previous shares of the page, only new ones made since clearing the cache (compare new post vs. older post below it):

![screen shot 2015-08-25 at 2 52 13 pm](https://cloud.githubusercontent.com/assets/583202/9476103/e676dc4c-4b38-11e5-9347-7212d5ed6284.png)

(╯°□°）╯︵ ┻━┻

**Comment by sbsmith86** [comment]
@DFurnes yea we had the an intern run through all the campaigns and manually bust the cache when we launch problem shares. it's stupid. But if the cache does clear every 24 hours...then including the "time left" to reach the goal on the image seems ok to me since previous posts are timestamped on the users profile anyway,

**Comment by DFurnes** [comment]
Ooof, yeah. It's frustrating that Facebook doesn't provide an API for clearing their cache automatically.

I think I agree that having older posts retain a cached version seems okay, as long as new posts get updated. @mikefantini Thoughts?

**Comment by mikefantini** [comment]
this sounds good to me @DFurnes @sbsmith86 

one other question:

is there anything we can do about the hierarchy of information?

It would be great to elevate the "800 modules hottened by August 27th? Let's make it happen." and the "DoSomething.org | Largest organization for teens.." switched if possible

I'm know we discussed this at some point, but can you remind me why we aren't going this route?

![image](https://cloud.githubusercontent.com/assets/6330971/9510208/07980e88-4c37-11e5-988f-5d4d6fc462f3.png)

**Comment by DFurnes** [comment]
Live on staging! See example share from the [test campaign](http://staging.beta.dosomething.org/campaigns/test-campaign?source=node/1165):

![screen shot 2015-09-01 at 11 34 14 am](https://cloud.githubusercontent.com/assets/583202/9608624/68980c00-509d-11e5-8fa4-cdfb48bea41c.png)
