### ISSUE TITLE
Array flip error on campaign nodes

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4689]
`Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 175 of /var/www/staging.beta.dosomething.org/releases/20150709174713/html/includes/entity.inc).`

Not sure what is causing this but seeing it a lot in stage
http://staging.beta.dosomething.org/campaigns/parents-ride-shotty

**Comment by itsjoekent** [comment]
I've been seeing this randomly occur on my local as well, ill look into it

**Comment by itsjoekent** [comment]
relevant SO issue, appears to occur on drupal 7 when someone uses a load function and passes in an array http://stackoverflow.com/questions/4798047/array-flipcan-only-flip-string-and-integer-values-in-drupaldefaultentitycont

going to debug further to see where its being called from (since a search for _load(array isnt returning anything useful and there is a lot of loads throughout the campaign module)

**Comment by angaither** [comment]
@deadlybutter [this](https://api.drupal.org/api/devel/devel.module/function/ddebug_backtrace/7) might be helpful for debugging

**Comment by itsjoekent** [comment]
yep thats what im using!

**Comment by itsjoekent** [comment]
alright, root of problem found. in dosomething_campaign.theme line 206 in dosomething_campaign_preprocess_hot_module is calling dosomething_image_get_themed_image_by_fid and passing in $author->picture->fid. The problem is many of us on our local box/staging don't have an author picture set, thus the FID being passed into the load function is NULL, which the core load function can't array flip. 

Two options we can discuss at next standup

1) Add edge cases to the code around all of the author pic uses. 
2) Add default image we can reference in the even an author pic is null.
