### ISSUE TITLE
can't submit initial photo for reportback

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4751]
http://screencast.com/t/xiDL5vntmP5D

to reproduce:
- go to campaign page
- sign up for campaign
- try to report back
- file upload dialog box opens up, but once you select a file cropping modal doesn't open

only happening on staging. seems to be working fine on production.

also adding another photo to an existing reportback seems to be working fine as well. it's just the initial photo that doesn't seem to be working.

cc: @julielorch

**Comment by angaither** [comment]
@sbsmith86 seeing this on the campaign page: `Uncaught TypeError: Cannot read property 'forEach' of null`

**Comment by sbsmith86** [comment]
@mikefantini @angaither hmmmmmm I was able to submit an intital reportback twice, once from an old account on a campaign I never reported back on. Then I created a new account, signed up for a campaign, reported back and was able to crop and everything. I'm on chrome. I'll try in other browsers...

**Comment by sbsmith86** [comment]
Having trouble reproducing this... I tried on Chrome, FF, and Safari. Going to ask Toyin to take a look...

**Comment by angaither** [comment]
I was able to reproduce on stage (and chrome), let me know if you wanna hang and work on this together

**Comment by sbsmith86** [comment]
So we are seeing this issue on http://staging.beta.dosomething.org/campaigns/hot-module this is because this is a new campaign with no reportbacks tied to it. So the graph data has null values for `quantity` and `dates`. The graph script is doing some iteration over these values and failing since the arrays are null causing the page to break. Need to add some checks for null arrays to the script so it doesn't break the page. GREAT FIND.
