### ISSUE TITLE
Flagged status should be null by default

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4756]
Before a reportback is reviewed the `flagged` and `promoted` status in the `dosomething_reportback` table should be `NULL`

Not sure what is causing newly submitted reportbacks to have a status of 0 by default, but that shouldn't be the case

**Comment by weerd** [comment]
Narrowed down the issue and working on a proper solution.

The issue seems to be that because the `$flagged` property is defined in the class:

![image](https://cloud.githubusercontent.com/assets/105849/9014080/0f0c12ee-378e-11e5-81ed-95ca96b1b34e.png)

Upon saving the RB and the slew of function calls that happen, when `entity->save()` occurs, for some reason it insists on setting the value to `0` in the DB even though it's `null` in the object passed around prior to saving it.

Aiming to find a solution that won't require to peacemeal add properties in class based on entity module behaving oddly.

**Comment by weerd** [comment]
It might not be Entity module behaving oddly, but maybe because the schema defines that column as having to be a boolean value.

So either Drupal or MySQL switches the type and makes `null` = `0` or false if the property is present when creating the DB row.

Solution may be to allow nullable field by updating the schema!

**Comment by angaither** [comment]
does it need to be defined as a public property here? is it because it's used later in the `build` method?? 
I wonder if we set the default value to null here if that changes anything?

**Comment by weerd** [comment]
Yeah, all the properties are use later. It's usually best to define them. I already tried setting the `NULL` value where the property is defined, but no dice (:no_entry_sign:  :game_die:).

I originally thought that maybe the table field for `flagged` in the DB was set to `NOT NULL` and so was turning the `NULL` value into a `0`, but it turns out there was a DB update a while back to make that field allow for `NULL` values.

I'm looking into where in Drupal it gets switched, to see if there's something I can pass to tell it not to switch it to `0`, which is a possible solution. Alternatively, as another solution, if the `flagged` property is `null` during creation of RB, then I could aim to `unset` the property which would ideally return to prior behavior...

**Comment by weerd** [comment]
So, turns out that Drupal when it requests the schema for the table using `drupal_get_schema()`, the field is shown as being `not null = true`, yet SequelPro says it's set to allow `null`...
