### ISSUE TITLE
new reportbacks are skipping the inbox

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4775]
example - nid 1667:

nothing in the inbox:
![image](https://cloud.githubusercontent.com/assets/6330971/9042286/b664337e-39db-11e5-9a4a-c8a291f1cd60.png)

and nothing reviewed, but quantity is 950:
![image](https://cloud.githubusercontent.com/assets/6330971/9042271/9b6db054-39db-11e5-9b69-5ef35d9abafc.png)

http://staging.beta.dosomething.org/admin/reportback/2820 and http://staging.beta.dosomething.org/admin/reportback/2821 are skipping the inbox but being counted (totals add up to 950)

related to #4756 and #4748

**Comment by angaither** [comment]
so I think the quantity getting added to the total should be fixed when @weerd fixes #4756

**Comment by mikefantini** [comment]
just recreated on nid 1617 with rbid 2839

also recreated on nid 1427 with rbid 2853 and nid 49 with rbid 2876

**Comment by mikefantini** [comment]
ongoing list of inbox status of staging campaigns https://docs.google.com/spreadsheets/d/1IPhVXwy-Ivi3Q7dZLMdCQHmiSYlimhqU858a17EniqY/edit#gid=0

**Comment by angaither** [comment]
this is b/c the query to get the total is joining on the reportback noun and verb. 
for all those campaigns where the reportbacks are 'skipping' the inbox it's because the campaign doesn't have the verb/noun set.
when the noun and verb are set, the reportbacks show up in the inbox properly 

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L1022-L1023

**Comment by angaither** [comment]
@weerd can you update the query so that reportbacks show up in the inbox regardless if the campaign noun/verb are set? 
Should be a left join (I am pretty sure)
