### ISSUE TITLE
Display finder content to users who visit a country's home page in the appropriate order

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#4886]
Users should see:
1. native campaigns in language
2. global campaigns in language
3. other global campaigns in global english (publish global campaigns initially)

This has to be changed in the finder code, and there may be changes that need to be made in the view.

**Comment by blisteringherb** [comment]
@julielorch Is the logic for #2 necessary for this iteration since we'll only have global campaigns in English for the launch?

**Comment by mikefantini** [comment]
@blisteringherb just chatted with @julielorch and let's just focus on:
1. campaigns that exist in user language (regardless of source language)
2. campaigns that exist in Global English

since it seems harder to add an extra layer of prioritization (campaigns that have source language as MX SP prioritized over campaigns with source language US EN that are translated into MX SP) let's just leave that out for now.

so the only prioritization would be show campaigns that exist in MX SP before showing campaigns that exist in GL EN.

anything else you need on that @blisteringherb?

**Comment by blisteringherb** [comment]
Based on the solution I put into #5123, adding the other global languages shouldn't be too heavy of a lift, but we will need to add "pt-global" and "es-global" as languages. The testing will probably be the hardest part because we'll have to have significant numbers of campaigns that are only translated into certain languages. I can expand on the dosomething_auto_translate() module to facilitate that if everyone thinks it's a good use of time.

**Comment by joolaay** [comment]
@mikefantini @blisteringherb ^ "pt-global" would be a global campaign, in portuguese, that hasn't yet been localized?

**Comment by blisteringherb** [comment]
@julielorch Yes, that sounds right to me.

**Comment by mikefantini** [comment]
as we talked about IRL let's hold on adding anything for pt-global or es-global. that will be work for future iterations when we decide we want to serve portuguese/spanish speakers globally
