### ISSUE TITLE
Thor Tumblr Problem Share Lags

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4892]
![image](https://cloud.githubusercontent.com/assets/12396076/9449714/6c665f0c-4a72-11e5-97d1-8bc84bd54bf4.png)

Still showing a "load" graphic after about 2 minutes.

**Comment by mikefantini** [comment]
this is most likely related to #4891

**Comment by sergiitk** [comment]
Works:
https://thor.dosomething.org/reportback/100072?fid=134628
![image](https://cloud.githubusercontent.com/assets/672669/9474560/12c82572-4b6a-11e5-955c-170ad973c454.png)

**Comment by namimody** [comment]
Still a problem seen on Thor on multiple browsers (Chrome, Firefox)

**Comment by sergiitk** [comment]
@sheyd @sbsmith86 Cron seems to work. Any other ideas? Could it be the job itself?

**Comment by sbsmith86** [comment]
@namimody This is related to the same thing we are seeing in #5482. Tumblr is lagging because it can't find the images. It can't find the images because the url where the images are located is being redirected to a url with the country prefix in it, resulting in an incorrect URL. I don't think we have assigned the work out to anyone to fix it. 

See the discussion here: 
https://github.com/DoSomething/phoenix/issues/5482#issuecomment-148789978

/cc @sheyd @sergii-tkachenko

**Comment by angaither** [comment]
I think we are ok with this one too, @namimody re-open if this is not true

**Comment by namimody** [comment]
All good on this @angaither!
