### ISSUE TITLE
Research CCtld domain availability and SEO implications

### ISSUE THREAD

**Issue by ghost** [DoSomethingArchive/legacy-website#4910]
Shire trip note, using ccTLD's has a large impact on SEO potentially. Research viability of ds domains available in other countries and actual impact.

**Comment by sheydari-ds** [comment]
I got a response back from Rank Above. Full response below, but TLDR: we should use hreflang tags instead of ccTLD's, since management overhead for ccTLD's is fairly high.

"ccTLD are a great signal to Google that a specific site is targeting a specific area, but you can achieve that same result using the hreflang tag. For example, you could tag www.dosomething.com/br to target Portugese speakers in Brazil (you need to target both language and location using the hreflang tag), by adding:
<link rel="alternate" hreflang="pt-br" href="http://www.dosomething.org/br"/> on the dosomething home page
<link rel="alternate" hreflang="en-us" href="http://www.dosomething.org/"/> on the BR home page
You can see more info at https://support.google.com/webmasters/answer/189077?hl=en.

Alternatively, you can also use different sitemaps, or HTTP server response code. Bottom line: ccTLDs help distinguish country-targeting pages or site automatically, but you can achieves the same effect with hreflang tags or other techniques."

Google Link: https://support.google.com/webmasters/answer/189077?hl=en

**Comment by ghost** [comment]
I got a response back from Rank Above. Full response below, but TLDR: we should use hreflang tags instead of ccTLD's, since management overhead for ccTLD's is fairly high.

"ccTLD are a great signal to Google that a specific site is targeting a specific area, but you can achieve that same result using the hreflang tag. For example, you could tag www.dosomething.com/br to target Portugese speakers in Brazil (you need to target both language and location using the hreflang tag), by adding:
<link rel="alternate" hreflang="pt-br" href="http://www.dosomething.org/br"/> on the dosomething home page
<link rel="alternate" hreflang="en-us" href="http://www.dosomething.org/"/> on the BR home page
You can see more info at https://support.google.com/webmasters/answer/189077?hl=en.

Alternatively, you can also use different sitemaps, or HTTP server response code. Bottom line: ccTLDs help distinguish country-targeting pages or site automatically, but you can achieves the same effect with hreflang tags or other techniques."

Google Link: https://support.google.com/webmasters/answer/189077?hl=en

Comments welcome @blisteringherb @angaither @mikefantini

**Comment by ghost** [comment]
I think we're pretty sure we know what to do from here. @mikefantini do we want to capture this as another implementation ticket anywhere (making sure hreflang tag) is on every affected page?

**Comment by ghost** [comment]
Actually, assigning to @mshmsh5000 to farm out to the engineering side.

**Comment by mshmsh5000** [comment]
https://www.drupal.org/project/hreflang
