### ISSUE TITLE
BR/MX admin need to to be able to edit content not created by them

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5020]
We'll need to add these permissions to BR/MX admin roles:
- [ ] Campaign: Edit any content
- [ ] Static content: Edit any content

keep in mind though, that Brazil admins should only have access to Brazilian Portuguese fields and Mexico admins should only have access to Mexican Spanish fields from @blisteringherb's [comment](https://github.com/DoSomething/phoenix/issues/4934#issuecomment-136467741) on #4934:

"I'm thinking that putting in a hook_menu_alter for node/%/edit that triggers the add translation chain if the allowed translation hasn't yet been created for that node and if it already exists it will send the user to node/%/edit/es-mx so they never actually get to the edit screen for the non-allowed translations.

For instance if a user with the Brazil admin role tries to visit `node/36/edit`, they'll be redirected to `node/36/edit/pt-br` if the translation already exists, and if not they'll go to `node/57/edit/add/en/pt-br`.  The other languages in the upper right corner of the node edit screen will be hidden except for those that they're allowed to see, and they won't have access to the translate tab."

note: whether or not they need access to `Home: Edit any content` is dependent on the decision made in #4968

**Comment by itsjoekent** [comment]
Just to clarify/update after talking w/ Fantini 

The problem this issue needs to solve is how the URL redirects when you click 'Edit' as a regional admin. Fields are already hidden on the node edit page due to this PR: https://github.com/DoSomething/phoenix/pull/5004

Also, the sub header fields need to display properly. EG: I'm currently a MX admin and I can click the PT/EN translations (should not be able too)-
<img width="347" alt="screen shot 2015-09-09 at 11 19 58 am" src="https://cloud.githubusercontent.com/assets/897368/9765977/c4a05744-56e4-11e5-92ae-4ce5fa1f53ae.png">

**Comment by itsjoekent** [comment]
~~Mapping the URL's will be based on the variables soon to be created in this PR:~~

~~https://github.com/DoSomething/phoenix/pull/5050#discussion-diff-39051771~~

Never mind, thats not happening yet. Just going to hardcode the values for now.

https://github.com/DoSomething/phoenix/pull/5050#discussion_r39073166
