### ISSUE TITLE
Reportback Count totals don't update

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#5047]
I'm generating Reportbacks for [Yeah, Science](http://staging.beta.dosomething.org/campaigns/yeah-science) and checking the pagination numbers in the API (and on the RB dashboard, /admin/users/rb).

Looks like the count totals (e.g. # of approved, promoted) never update upon reviewing reportbacks, which I believe is preventing the API response from updating with new reportbacks.

**Comment by weerd** [comment]
@aaronschachter 

So part of the issue may be that in the API I'm setting a default value for RB items to return as `approved`. So if no `status` url parameter is passed it defaults to `approved`. Not sure if @uy and I had made a decision to go with that as the default, but that's the current case. 

However, instead of making two API calls, the endpoint allows you to pass a CSV of statuses (stati?), so you can grab both `approved` and `promoted` with a single call:

```
/reportback-items.json?&campaigns=1377&status=approved,promoted
```

Maybe we update the endpoint in the future if having the default be `approved`... I believe the idea was default to `approved` so that it would not include `excluded` items off the bat in the response.

CC: @angaither

**Comment by weerd** [comment]
At least the above may be part of the issue and not the whole solution...

**Comment by aaronschachter** [comment]
This doesn't block us from launching on iOS because we didn't have time to build out infinite scroll. I haven't had time to investigate if it's a bug in pagination, but it sounds like the issue may have been because I wasn't passing a `status` parameter through the endpoint. 

Closing this for now if it doesn't seem to be affecting anything on the web. We can revisit if we get to building out infinite scroll and investigating whether or not this was even an issue.
