### ISSUE TITLE
RBs Submitted Via App Do Not Appear in RB Inbox

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5067]
Doing some testing on staging and noticed that reportbacks via the app don’t appear in the reviewing inbox currently. For example: http://staging.beta.dosomething.org/admin/reportback/3067 appears as PENDING in a SQL pull, but doesn't appear in the inbox (http://staging.beta.dosomething.org/node/955/rb). @aaronschachter notes this sounds like its a northstar/phoenix api issue.

![image](https://cloud.githubusercontent.com/assets/12396076/9794476/442d5df2-57b9-11e5-9096-bde613fbf3e9.png)

**Comment by aaronschachter** [comment]
@namimody The latest release of the iOS app posts reportbacks to staging, and I have confirmed they appear in the inbox. It seems reportbacks @jonuy is submitting from Android are making it there too.  Looking at the timestamps in your screenshot, it looks like this data could possibly be off because the submissions were made while we were developing functionality (could be a number of reasons, API development, or just general web development)

**Comment by namimody** [comment]
Thanks for following up on this @aaronschachter! Good to go ahead and close then?
