### ISSUE TITLE
Campaigns API returns solutions.support_copy as string instead of object

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5069]
I've only noticed it on one campaign:

http://staging.beta.dosomething.org/api/v1/campaigns/1261.json

Haven't seen it on any others, but I also haven't gone searching for problematic ones.

A typical response would be like from: http://staging.beta.dosomething.org/api/v1/campaigns/1663.json

```
...
solutions: {
  copy: {
    raw: "Disney is making movies to empower their princesses (heeey, Elsa!), and we're a;; for it. Promoting self sufficient and complex female characters leads to other similar representations of women in media.",
    formatted: "<p>Disney is making movies to empower their princesses (heeey, Elsa!), and we're a;; for it. Promoting self sufficient and complex female characters leads to other similar representations of women in media.</p> "
  },
  support_copy: {
    raw: "Use our templates to join Disney's promotion of strong female characters on screen:create new empowered princesses with unique traits and goals (that don't include finding a prince charming).",
    formatted: "<p>Use our templates to join Disney's promotion of strong female characters on screen:create new empowered princesses with unique traits and goals (that don't include finding a prince charming).</p> "
  }
},
...
```

**Comment by weerd** [comment]
So this happens because a format isn't used on the field AND Drupal hasn't created a `safe_value`, which it should have for the field in this campaign. The campaign has a **Text Format: Markdown** selected, but Drupal doesn't seem to have processed it properly; checking the returned node indicates it's set to `null`.

The logic [here](https://github.com/DoSomething/phoenix/blob/8c2abfe6f457187c9fcb141ef2e9294df879712e/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L176) is setup to extract `raw` and `formatted` if a `safe_value` exists. When it doesn't it just returns the `value`, which would be the case for other text fields that don't have a formatter. 

I did a bit of testing when creating this function for the API, and worked for the majority of cases, while also taking into consideration of generic text fields versus fields that can be formatted.

Changing the formatting for that field to **Plain Text** saving, and then back to **Markdown** then it seems to fix it.

**Comment by weerd** [comment]
If this happens more often on other campaigns, might need to look into why when specifying **Markdown**, Drooops isn't registering that properly.

**Comment by aaronschachter** [comment]
Just got an iOS app crash in v1.0.9(1) for Babysitters Club, nid 57, because i removed the conditional checking for a non-markdown value (https://github.com/DoSomething/LetsDoThis-iOS/pull/915/files)

@weerd -- What do you think about a long term fix where we return `raw` and `formatted` regardless of whether a `safe_value` exists? As a consumer of the API, it's seems weird that the format for these markdown properties can change (to not be objects at all).

**Comment by aaronschachter** [comment]
Created #6250 which should resolve.
