### ISSUE TITLE
Global MailChimp Settings

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5072]
Currently a MailChimp list ID (`mailchimp_list_id`: f2fab1dfd4) is set in the Drupal Third Part Opt-In -> General form: https://www.dosomething.org/admin/config/dosomething/opt_in. 
![image](https://cloud.githubusercontent.com/assets/2119264/9795878/21ab40e8-57c1-11e5-83c7-75303253a850.png)

This value is included in user_registration transactional message requests sent to Message Broker as a part of the `activity": "user_register` request payload:

```
"mailchimp_list_id": "f2fab1dfd4"
```

The form needs to be expanded to support `mailchimp_list_id` values for:
- Global
- US (United States)
- BR (Brazil)
- MX (Mexico)
- CA (Canada)
- UK (United Kingdom)

Perhaps support for the remaining affiliates should also be added:
- ID (Indonesia)
- etc.

**Related**:
- https://github.com/DoSomething/phoenix/issues/4955

**Comment by itsjoekent** [comment]
@DeeZone Do you also need me to add these new values into the MB payload or is that a separate issue?

**Comment by mikefantini** [comment]
@deadlybutter let's group them all with in general, and then have have subgroups within that for
- Global
- US
- Mexico
- Brazil

I'll make a separate future issue for Canada/UK because that's not within this first version of Global.

Let's also leave the Global, Mexico, and Brazil fields as unrequired for now (keep US ones required) and I'll make a separate issue for those to be required after we have values for them.
