### ISSUE TITLE
Country code hashing in Fastly

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5115]
Update Fastly config, first for Thor, to hash on country codes. While we're add it, use this space to discuss what else, if anything, we should be hashing on.

[Drupal-specific VCL docs](https://fourkitchens.atlassian.net/wiki/display/TECH/Configure+Varnish+3+for+Drupal+7) are a good place to look for other ideas.

**Comment by ghost** [comment]
I've thought of a whole lot of exotic things we could do with this going forward, but for v1, hashing on geoip.country_code, and since we're using unique URL structure per country-language, this should be the right way to go without making everything too complicated. 

Hashing on req.url, req.http.host, and geoip.country_code is now live in Thor.

**Comment by ghost** [comment]
Confirmed working in Thor env. Enabled in Prod.
