### ISSUE TITLE
Campaign Lead Name Alignment Off on Some Hot Module Campaigns

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5139]
Lizzy and Sam's names are just to the right of their photos, like so:

![image](https://cloud.githubusercontent.com/assets/12396076/9922551/0e625ff2-5cb8-11e5-8ad9-d9df5c846cde.png)

![image](https://cloud.githubusercontent.com/assets/12396076/9922581/6819768e-5cb8-11e5-9881-f971fddcdde6.png)

But Michaela and Adam's are moved over, like this:
![image](https://cloud.githubusercontent.com/assets/12396076/9922566/3c0be14e-5cb8-11e5-92a4-c5594dd955a0.png)

![image](https://cloud.githubusercontent.com/assets/12396076/9922575/5d5fc95a-5cb8-11e5-8c84-19a83a9e7713.png)

**Comment by DFurnes** [comment]
Oooof, I know what's going on here. :grimacing:

**Comment by DFurnes** [comment]
This was fixed in [Forge 6.6.1](https://github.com/DoSomething/forge/releases/tag/v6.6.1), which is now deployed to staging.

#### Before:

![screen shot 2015-09-17 at 12 55 37 pm](https://cloud.githubusercontent.com/assets/583202/9940140/f309f538-5d3b-11e5-9d19-d2f499319011.png)

#### After:

![screen shot 2015-09-17 at 12 57 48 pm](https://cloud.githubusercontent.com/assets/583202/9940143/f86e553c-5d3b-11e5-9f69-aedbcb0400db.png)
