### ISSUE TITLE
Ensure banner notifications are wrapped in t()

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5142]
All [drupal set message results]([https://github.com/DoSomething/phoenix/search?p=1&q=drupal_set_message&utf8=%E2%9C%93)

looks like standout ones we need to update
- [x] [reward confirmation*](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_reward/dosomething_reward.forms.inc#L61)
- [x] [shipment confirmation](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_shipment/dosomething_shipment.forms.inc#L128)
- [x] [signup form](https://github.com/DoSomething/phoenix/blob/b8ff63e4419c362f9c2862fc9230203523721e75/lib/modules/dosomething/dosomething_signup/dosomething_signup.forms.inc#L71)
- [x] [reset password copy](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/themes/dosomething/paraneue_dosomething/includes/auth/login.inc#L135)
- [x] [~~user profile save~~](https://github.com/DoSomething/phoenix/blob/d965ac9a8a4774a34ed5cf0401ca645cb3045a03/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1166)

**Comment by angaither** [comment]
meh, found another old issue we might need to look into @weerd

**Comment by weerd** [comment]
Yeah, this related to the issue I found with wrapping Drupal messages in `t()`. Didn't seem to take the translation from the .po file, but I can keep trying.

Some additional info: https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_set_message/7

**Comment by weerd** [comment]
After a bit of digging while trying to get this content to output and translate,  found out that the entire function that encompasses the output message of ["User information saved"](https://github.com/DoSomething/phoenix/blob/d965ac9a8a4774a34ed5cf0401ca645cb3045a03/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1166) is not called by anything; it is entirely defunct. It's likely supposed to work as some form of hook function, but since it doesn't use the actual module name `dosomething_user_info` vs `dosomething_user` (which is the actual module name), I don't think it's ever firing. We should likely remove this code.

The language used when profile is saved is "The changes have been saved." which is part of the Drupal core **User** module and already has the `t()` wrapped around it.  It's likely we can import core Drupal translations, but not sure if it's worth it, or just add this string to our own POT file...

cc: @mikefantini

**Comment by angaither** [comment]
user info save is from `user/%user/info`
