### ISSUE TITLE
Yahoo 11 facts prototype 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5203]
The basic functionality should remain the same for larger (desktop sized) screens
On mobile sized screens we want to serve a different yahoo-theme CTA, as well as the 'explore campaigns button' point to a yahoo link with a [pre-filled search query](https://search.yahoo.com/do?p=animals)

![desktop](https://slack-files.com/files-pub/T024GV2BW-F0B56R1PD-3cb5b03471/big-screen.png)

![mobile](https://slack-files.com/files-pub/T024GV2BW-F0B592QTG-86a1287c75/small-screen.png)

I nominate the 11 facts about volcano page, because it has the same nid on dev/stage/prod

`node/176`

cc @mshmsh5000 @namimody

**Comment by namimody** [comment]
Hi @angaither! Behavior sounds correct. Just a couple of clarifying points because I just want to make sure I fully understand --

this will only happen on staging for tomorrow and both the top and bottom CTA link will change on the smaller screen? 

Thanks!

**Comment by sbsmith86** [comment]
@namimody yep. it will be up on staging by tomorrow and we will switch out the top and bottom CTA's on mobile.

One question - what's the rule for the pre-populated search link, is it the cause term?

**Comment by namimody** [comment]
Amazing -- thanks for the clarification @sbsmith86! The rule for the pre-populated link is a bit up in the air because a few approvals have yet to be given -- but what is guaranteed is that we'll know which keyword is associated with each facts page (they vary based on what keyword will yield results with few ads) and how all the URLs are configured. Is that helpful?

**Comment by sbsmith86** [comment]
@namimody hmm i guess i mean how do i know how to build out the custom cta link for this prototype i.e. https://search.yahoo.com/do?p=animals

Does the `p=animals` correlate to the cause term on the node? So if we do volcanos, it would be `https://search.yahoo.com/do?p=environment`?

**Comment by namimody** [comment]
@sbsmith86 for the prototype, you can link to: https://search.yahoo.com/search;_ylt=A0LEV1PdFwNW2ukAuyel87UF;_ylc=X1MDOTU4MTA0NjkEX3IDMgRmcgMEZ3ByaWQDMHVnUmhsV0lSMi5WWFZ1NWhWQVE2QQRuX3JzbHQDMARuX3N1Z2cDOQRvcmlnaW4Dc2VhcmNoLnlhaG9vLmNvbQRwb3MDMARwcXN0cgMEcHFzdHJsAwRxc3RybAM3BHF1ZXJ5A3ZvbGNhbm8EdF9zdG1wAzE0NDMwNDMyOTg-?p=volcano&fr=sfp&fr2=sb-top-search&iscqry=

for the entire partnership, we'll have a spreadsheet like this (not final): https://docs.google.com/spreadsheets/d/18XMsv8MGZlP1t2gTWumpCdfj24h8yvJHkccSjZ0hfZw/edit#gid=1825152800 that each page will need to pull from accordingly. let me know if you want to chat in person at all!

**Comment by sbsmith86** [comment]
@namimody makes sense. thankkks!

**Comment by angaither** [comment]
@namimody looks like it's just searching for the title, correct?

**Comment by namimody** [comment]
@angaither for the title of the 11 Facts page? not always. generally, the Yahoo team suggests querying things like "facts about volcanoes" because that yields searches with less ads. Then, there are some pages, like ones about women in tech (oh heyyy) which are going to throw to search results for Megan Smith. Long and short -- the logic will need to consult the list for each fact page.

**Comment by mshmsh5000** [comment]
**And** it's captured in a feature flag! :100:
