### ISSUE TITLE
URL for en-global campaign is in spanish

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#5252]
URL for node 5624 is in spanish 

https://thor.dosomething.org/campanas/making-campaign-hello

(/campanas/..)

however, there is no spanish translation and the source is global. 

https://thor.dosomething.org/node/5624/translate

This is the cause of https://github.com/DoSomething/phoenix/issues/5199

User: https://thor.dosomething.org/user/2632038/edit
(Administrator, Global EN)

**Comment by itsjoekent** [comment]
cc: @angaither

**Comment by angaither** [comment]
@deadlybutter what was the author's lang/user role? can you add that above?

**Comment by itsjoekent** [comment]
@angaither added

**Comment by mshmsh5000** [comment]
This issue was created before we deployed all of the changes for #5130. Worth noting that now, with Thor updated to the latest version of `dosomething_global` (7.x-1.1), the `/campanas/` pattern doesn't exist:

![url-patterns](https://cloud.githubusercontent.com/assets/149811/10105312/06a03026-637c-11e5-975f-76e08d021755.png)

Consider any URL on Thor with `/campanas/` suspect, as it's pre #5130. Sorry for the confusion here.

Now that Thor is up to date, I deleted the [previous URL aliases](https://thor.dosomething.org/us/admin/config/search/path/list/making-campaign) for this campaign. Noting that `Generate automatic URL alias for all languages` is selected for this content:

![auto-generate](https://cloud.githubusercontent.com/assets/149811/10105459/c54f1424-637c-11e5-94d9-9e3ec8a3363b.png)

I went back and saved the campaign. Now, this is the URL for Global English:

https://thor.dosomething.org/campaigns/making-campaign-hello

[These patterns](https://thor.dosomething.org/us/admin/config/search/path/list/making-campaign) have been generated, even though the translations haven't been created yet:

![new-url-patterns](https://cloud.githubusercontent.com/assets/149811/10105533/256ec80e-637d-11e5-8ec8-a18bf48c88d1.png)

Note that the patterns are absent the language prefixes, which aren't set in the aliases table (because they're dynamically assigned elsewhere, like [here](https://thor.dosomething.org/us/admin/config/regional/language/edit/pt-br) and [here](https://thor.dosomething.org/us/admin/config/regional/language/edit/en-global)).

**Comment by mshmsh5000** [comment]
Because #5130 changes are deployed on Thor and not on production, we should see correct behavior on Thor, but not on production.

If we see the correct behavior on Thor, we should close out this bug. @deadlybutter I leave this to you to confirm and close.

**Comment by itsjoekent** [comment]
Sure thing

**Comment by itsjoekent** [comment]
yep everything works now, tested mx & en campaigns and everything seems to be :ok: 

thanks matt!
