### ISSUE TITLE
GL: USER REG: User registration email is not sending to global users

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5288]
Per testing with @sergii-tkachenko, no user reg email was trigged upon registration. 

He is testing from Ukraine, so this affects GL users.

**Comment by deezone** [comment]
![image](https://cloud.githubusercontent.com/assets/2119264/10170725/5638ff02-66a4-11e5-8bd6-7ff956cb06ca.png)

**Comment by marahml** [comment]
This template should actually look like the Niche.com template

**Comment by deezone** [comment]
@marahml Note the example registration is from CZ (Czech Republic) which is considered a "global user" and thus will get the US templates. The original bug issue says" He is testing from Ukraine, so this affects GL users." thus the use of a global user to confirm the bug was fixed.

A test with a Brazilian user produces the template you're looking for:

![image](https://cloud.githubusercontent.com/assets/2119264/10198774/8a432454-676b-11e5-8523-26fa22f63c9d.png)
