### ISSUE TITLE
clean up content tab for regional admins

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5297]
- [ ] hide drupal's default content tab (using hook_menu_alter())
- [x] expose `admin/content/search` view
- [x] add a `language` option to that view
- [x] allow that option to be exposed

**Comment by itsjoekent** [comment]
Also update the /search page. The title got messed up by the translation status page

**Comment by itsjoekent** [comment]
Talked with Fantini, we're not going to hide the content tab because 

1) we can't recall why it was suggested here
2) it does this to the admin menu

![screen shot 2015-10-07 at 4 28 10 pm](https://cloud.githubusercontent.com/assets/897368/10350202/9ed630b4-6d10-11e5-8bc9-f9861f36e348.png)

when it should be this

![screen shot 2015-10-07 at 4 28 22 pm](https://cloud.githubusercontent.com/assets/897368/10350210/abfa2c6e-6d10-11e5-83a5-35ecfa0039d9.png)

3) there doesnt appear to be anything destructible (taken as a mx admin)

![screen shot 2015-10-07 at 4 28 22 pm](https://cloud.githubusercontent.com/assets/897368/10350237/d8b41db4-6d10-11e5-8ec6-92e54ae6096e.png)
