### ISSUE TITLE
Updates to Global Admin permissions

### ISSUE THREAD

**Issue by mnelson338** [DoSomethingArchive/legacy-website#5347]
@angaither Need to create a translator role that allows external translator to: 
Access content in Global English
Create Spanish and Portuguese translations of campaigns 

And that's pretty much it.

**Comment by angaither** [comment]
I think we are safe giving them the global admin role so that they can see/confirm the language of the node they are creating, if we do that we should remove these permissions, we can do this in prod if they need access today, and then export these to features. and deploy
- [x] edit any reportback
- [x] edit user info
- [x] view user profiles
- [x] add partner terms

cc @mikefantini

**Comment by mnelson338** [comment]
Great - so to confirm: We I can create a user role now with global admin permissions and send over now. But we'll edit those to remove the indicated permissions that will go live later today.

**Comment by angaither** [comment]
@mnelson338 I removed those permissions in production, so go ahead and send them over logins. 

@deadlybutter can you update the `global admin` role to remove those permissions in features?

**Comment by mikefantini** [comment]
@deadlybutter this is now blocking prod deploy, so let's make sure to get this done in time for a Monday deploy.

**Comment by itsjoekent** [comment]
@mikefantini im blocked on getting my local environment running right now, see #phoenix
