### ISSUE TITLE
Enable CSP (Content-Security-Policy) Within Phoenix

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5392]
X-Frame-Options is deprecated per various sources. Good round-up here:
https://appsec-labs.com/portal/anti-clickjacking/

Cobalt report highlighted this. We need to figure out exact policy, and enable as features within Drupal SecKit:

https://www.dosomething.org/admin/config/system/seckit

@sergii-tkachenko I'll focus on making sure the security policy part is correct, and then I'll assign to you to put into features.

**Comment by sheyd** [comment]
The following fields need to be set under `Content Security Policy`:

`default-src: 'self' *.dosomething.org`
`frame-src: 'self' *.dosomething.org optimizely.com`

Remaining tasks before pushing to Prod:
1. Deploy to Staging. 
2. Create an Optimizely test in for staging that includes use of a frame element.
3. Test Optimizely A/B test, and confirm all functionality.

@sergii-tkachenko assigning this to you to implement as part of Global 1.1. One you're done, assign it back to me, and I'll coordinate testing with @namimody.

**Comment by sergiitk** [comment]
Reference: https://cobalt.io/dosomething/reports/59

**Comment by sergiitk** [comment]
To record: staging and prod are desynchronized in `X-Frame-Options` settings.
`X-Frame-Options` returned `SameOrigin` on stage and `Allow-From: http://optimizely.com` on prod.
Hence provided clickjacking html example doesn't work on stage and works on prod.

**Comment by sergiitk** [comment]
Note: `frame-src` direcrtive has been replaced with `child-src`.
http://www.w3.org/TR/CSP/#frame_src

**Comment by sergiitk** [comment]
Chat log of @sheyd and myself:

​[11:32 PM] I did enable and tuned up csp
​[11:32 PM]  it took more rules to make it work
​[11:33 PM]  but it turned out that `frame-src` is a directive that regulates frames embedded into our page
​[11:33 PM]  not pages our page is embedded into
​[11:34 PM]  withregard X-Frame-Options
​[11:34 PM]  https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options
​[11:35 PM]  it does work as intened
​[11:35 PM]  but, allow-from isn’t supported in chrome and safari
​[11:36 PM]  CSP proposes the feature to solve it
​[11:36 PM] called `frame-ancestors`
​[11:36 PM] but only in v2
​[11:37 PM]  so 1) we better bring back /X-Frame-Options
​[11:37 PM]  2) implement `frame-ancestors` in scp for future (edited)
​[11:39 PM]  unfortunately `frame-ancestors` isn’t supported by the module yet

**Comment by namimody** [comment]
@sheyd just circling back and making sure you don't need me to test anything -- thanks!

**Comment by sergiitk** [comment]
@namimody We're good for now, it's enabled in Report-Only mode. It will be enabled in #5783.
