### ISSUE TITLE
unpublishing a translation of a campaign doesn't actually unpublish it

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5469]
https://thor.dosomething.org/mx/node/36/translate shows that the MX SP version of the campaign is Not Published, however if you go to https://thor.dosomething.org/mx/voluntario/bailando-con-las-personas-mayores as an anonymous user you're able to see the campaign.

Possibly related to #5260? not sure, I _thought_ I saw this working recently.

**Comment by angaither** [comment]
@deadlybutter can you take a look at this today?

**Comment by itsjoekent** [comment]
sure

**Comment by itsjoekent** [comment]
So the status in the translations object is actually being set to 1 when you publish a translation (and its 0 when not). That works fine.

I think the problem is our logic ignores whether a translation is published or not, and just works off whether it exists or not. I'll update the redirect logic to also make sure a translation not only exists, but it's been published.

**Comment by mikefantini** [comment]
as we discussed IRL you're also able to directly hit the URL even if it's unpublished as an anonymous user which should not be the case.

i.e. if I'm anonymous and /mx/voluntario/whatever is unpublished, I should not be able to see the content when I go directly to that URL
