### ISSUE TITLE
Fractions Not Pulled Into Problem Share Image

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5481]
Seems if a fraction is present in a problem statement, it doesnt get pulled into the FB and Tumblr Share images:

Problem listed on site:
![image](https://cloud.githubusercontent.com/assets/12396076/10497249/e985bfda-7292-11e5-818c-466bb0ebfcd8.png)

Facebook Share:
![image](https://cloud.githubusercontent.com/assets/12396076/10497141/5c4c8d10-7292-11e5-84a9-8bb4c8379d04.png)

Tumblr Share:
![image](https://cloud.githubusercontent.com/assets/12396076/10497149/6944f98a-7292-11e5-8a3f-3c574ea7fd40.png)

(twitter just pulls in text)

**Comment by chloealee** [comment]
@namimody @angaither how are people writing fractions in the proper form in this field? I'm trying to replicate but having a difficult time. 

Also - how do new facts get assigned an id? It looks like the number behind the fact is an id of some sort and then it saves the fact to be edited elsewhere? I'm trying to edit slightly and it says it saves but when I go to edit again, it reverts back to what it was before with fractions looking like `1/4` instead of `¼`.

**Comment by namimody** [comment]
Here is one example @chloealee! https://www.dosomething.org/us/campaigns/out-closet-cards

And new facts get created on their own nodes on this form: https://thor.dosomething.org/us/node/add/fact

**Comment by chloealee** [comment]
Thanks @namimody ! Looks like that one is working now? 
![screen shot 2016-02-25 at 3 24 50 pm](https://cloud.githubusercontent.com/assets/9019452/13333237/01d86ba0-dbd4-11e5-82f8-82baf3c13576.png)

**Comment by namimody** [comment]
Oof, well that's great/sucks! I'll close then @chloealee -- so sorry you spent time on this!

**Comment by chloealee** [comment]
No worries @namimody! Glad it works :)
