### ISSUE TITLE
Long RB Image Captions Do Not Wrap on iPhone

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5589]
Note that 60 character limit _seems_ to be applying on the field, but text is then not wrapping when a user goes back to action page. Happening on at least global EN, US, and MX.

![image](https://cloud.githubusercontent.com/assets/12396076/10673952/6e597024-78c6-11e5-924f-47698853ac49.png)

Ew.

**Comment by DFurnes** [comment]
This is happening because it's one uninterrupted 60 character string & the browser doesn't know where to break to a new line. Adding at least one space allows it to break properly:

![screen shot 2015-10-22 at 5 36 07 pm](https://cloud.githubusercontent.com/assets/583202/10678938/64fba02a-78e3-11e5-8b58-39c1ebe31196.png)

![screen shot 2015-10-22 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/583202/10678884/0fe77f46-78e3-11e5-9147-f466380ef9f0.png)

**Comment by DFurnes** [comment]
Adding [`word-wrap: break-word`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap) to the container should fix things up, but this is probably very unlikely to happen to a typical user.

**Comment by weerd** [comment]
^^ indeed.

**Comment by namimody** [comment]
Brilliance!

On Thu, Oct 22, 2015 at 5:44 PM, Diego Lorenzo notifications@github.com
wrote:

> ^^ indeed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/phoenix/issues/5589#issuecomment-150365047
> .

## 

Namita (Nami) Mody

Junior Product Manager
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255
