### ISSUE TITLE
Broken Image on Re-Poppin Bottles

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5680]
Campaign Page: 
![image](https://cloud.githubusercontent.com/assets/12396076/10890221/c24ebf76-8164-11e5-830f-162ed8c64786.png)

Search:
![image](https://cloud.githubusercontent.com/assets/12396076/10890231/d3e2ffd6-8164-11e5-96bf-4d2c282e7207.png)

Finder:
![image](https://cloud.githubusercontent.com/assets/12396076/10890246/e88096c4-8164-11e5-86b0-b9ea3022dc0e.png)

Back End:
![image](https://cloud.githubusercontent.com/assets/12396076/10890251/f175b4d0-8164-11e5-8675-475641627c2d.png)

Unsure why this image is broken on the backend, but it may have to do with importing prod data?

**Comment by angaither** [comment]
@namimody yeah, if you look at the page in prod the images referenced have changed, since we are using stage file proxy it's referencing an image that was removed from prod, I wouldn't worry about this too much. 
you can update the image to use something else and it should work

close if you agree :smile:

**Comment by angaither** [comment]
note the title of the images changed
![image](https://cloud.githubusercontent.com/assets/645205/10890617/e8b77b88-8166-11e5-91fa-c42794dcbbf0.png)

**Comment by namimody** [comment]
Sounds good to me @angaither!
