### ISSUE TITLE
Add load_user parameter to the retrieve operation for RB and RB Items endpoints

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5707]
We allow specifying to `load_user=true` for the **index** collection API operation, but not for when showing individual **retrieve/show** for Reportbacks and ReportbackItems.

**Comment by chloealee** [comment]
notes from slack convo: realized that for an individual RB or RBitem, we probably ALWAYS want to load the user since it's only 1 item when we do a retrieve. So instead of doing a bunch of code to update the resource in services etc, we just pass `TRUE` at this point to the build function: https://github.com/DoSomething/phoenix/blob/29373fa2ba9e67f33e4c7e5aa7f26fdb0aa4bd2c/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L99
