### ISSUE TITLE
Why are API Calls Failing in Prod?

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5718]
@tongxiang Can you add any problematic API calls here?

**Comment by angaither** [comment]
@sheyd is this still happening?

**Comment by tongxiang** [comment]
I think we can probably close this issue. 

We weren't able to access the prod API from within the office. 

It seems like a lot of [these issues](https://github.com/DoSomething/LetsDoThis-iOS/issues/612) were caused because of some namespacing issues from an old windows server in our office also named "dosomething.org". We fixed this by changing the default DNS server used by our local machines.
