### ISSUE TITLE
GL EN translations should show up in /campaigns

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5793]
If a campaign has a GL EN translation published but no Regional translation published (i.e. MX SP), then GL EN translation should show up on /campaigns after all of the campaigns that do have MX SP translations published.

I.e. /campaigns should follow the same rules as the finder.

![image](https://cloud.githubusercontent.com/assets/6330971/11218611/f04a6fe0-8d23-11e5-87df-c3b6e4491039.png)

**Comment by blisteringherb** [comment]
I've got this mostly working, with one caveat. The global campaigns show up interspersed with all of the other campaigns instead of "filling in" at the end. This is because /campaigns is using Views, and we don't have quite as much control as we would with the campaign finder. 

@mikefantini Is it fine to ship this with the global campaigns interspersed with all other campaigns on the /campaigns page?

**Comment by mikefantini** [comment]
@blisteringherb yup that works for me. Thanks!

**Comment by mikefantini** [comment]
@blisteringherb can we ship this to prod and close this out?

**Comment by angaither** [comment]
closed with #6147
