### ISSUE TITLE
CMS admin form content getting escaped each time form is saved.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5819]
Drupal keeps escaping `&` every time you hit save on the CMS form @_@... so it goes from `&quot;` to `&amp;quot;` to `&amp;amp;quot;` for example, after 3 saves... :scream:

![image](https://cloud.githubusercontent.com/assets/105849/11286115/29a2017c-8ee1-11e5-8c19-8607e6f7a0a6.png)

Occurring on form here: `admin/config/dosomething/dosomething_user` (within the **School** section), but doesn't happen with this form: `admin/config/dosomething/dosomething_settings`

For the time being I've updated content in the School field across the sites to only escape the characters once.

**Comment by angaither** [comment]
this is because we are using a token replace in those values
https://www.drupal.org/node/1446350

[school text](https://github.com/DoSomething/phoenix/blob/d47f12091b8e8da378b1e0fb3a5f593a68aeac00/lib/modules/dosomething/dosomething_user/dosomething_user.admin.inc#L190)

```
  $var_name = 'dosomething_user_school_finder_help_text';
  $form['school'][$var_name] = array(
    '#type' => 'textarea',
    '#title' => t('School Finder Help Text'),
    '#description' => t("Text displayed if User needs help finding school.  Markdown supported."),
    '#default_value' => t("@value", ['@value' => variable_get($var_name)]),
  );
```

[vs about text](https://github.com/DoSomething/phoenix/blob/d47f12091b8e8da378b1e0fb3a5f593a68aeac00/lib/modules/dosomething/dosomething_settings/dosomething_settings.admin.inc#L15)

```
  $var_name = 'dosomething_settings_copy_about_ds';
  $form['copy'][$var_name] = array(
    '#type' => 'textarea',
    '#title' => t('About DoSomething'),
    '#default_value' => t(variable_get($var_name)),
  );
```

**Comment by angaither** [comment]
@weerd this may be a larger issue than just that form it's anytime we use a `system_settings_form` with the token replace

`htmlspecialchars_decode` seems to fix the issue, but I'm not sure if the translation will still work
`'#default_value' => htmlspecialchars_decode(t("@value", ['@value' => variable_get($var_name)])),`
