### ISSUE TITLE
Add toggle to enable/disable Hot Module per campaign

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5827]
Currently, the hot module is switched on when the current date is between the high season dates set on the back end of a campaign. 

While we will be using the hot module more ubiquitously going forward, there are instances where we would like to set a hot season to get the perks of inputting a high season (like appearing higher in the finder) but without showing the module (because the campaign is a more sensitive rapid response, for example).

Just wanted to create an issue as I know we briefly discussed this possibility and @angaither said it was doable :)

**Comment by angaither** [comment]
this should be a custom setting in the `goals setting` section on `/node/[nid]/custom-settings`

**Comment by mikefantini** [comment]
Also note I _think_ we'd want the rule to be if the current date is within the high season _and_ hot module is enabled, then display the hot module.

Otherwise we'd have to manually shut off the hot module every time which we don't want.

This may also impact the win module, we'd only want that to display for 30 days after the high season end date _if_ the hot module is enabled.
