### ISSUE TITLE
User object in GET /reportback-items response is null

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5885]
#### Example call

https://www.dosomething.org/api/v1/reportback-items
#### The result

```
user: {
  id: null,
  first_name: null,
  photo: null,
  country: null
}
```

This seems to currently be happening on both staging and production.
#### The expectation

There should at least be a value for `id` and `first_name`.
#### What've we looked into so far
- Checked Northstar settings and they seem :ok: (/admin/config/services/northstar)
- Flushed Redis cache on staging. Didn't seem to do anything
- The depths of Diego's eyes. It's magical.

cc: @angaither @chloealee @DFurnes

**Comment by angaither** [comment]
@weerd mind taking a look at this one?

**Comment by weerd** [comment]
righty-o

**Comment by weerd** [comment]
"The depths of Diego's eyes. It's magical." :eyes: :wink:

**Comment by mshmsh5000** [comment]
![diego-clip-art-diego_pulando](https://cloud.githubusercontent.com/assets/149811/11572657/59e5502e-99d0-11e5-90e9-485339d60705.gif)

**Comment by weerd** [comment]
LOL

**Comment by weerd** [comment]
So this is a simple fix!

`https://www.dosomething.org/api/v1/reportback-items?load_user=true`

Because we were dealing with expensive calls, we decided to use the `load_user` URL param and pass `true` if we wanted user data included in index collection views; otherwise it's ignored and `null` is passed since we want to keep the properties present. ;)

So the following will load with users:
https://www.dosomething.org/api/v1/reportback-items?load_user=true
