### ISSUE TITLE
update hot module query that outputs the json

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5919]
when the hot module runs for more than a month, the dates on the graph get all sorts of funky
![image](https://cloud.githubusercontent.com/assets/645205/11660817/dcdde5ac-9d9c-11e5-9f6f-fe60536e86a3.png)

[this query](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L295-L298) needs to be updated to grab only the current months so it doesn't look so ~WILD~

**Comment by sbsmith86** [comment]
This is appears to be happening when a campaign has a hot module running on it for a month, and then the hot module timing gets extended another month. However, I am not sure that should cause any issues with the graph. 

From an array of data (from the query above) over all time, the JS creates a separate array of dates and quantities between the start and end date specified in the CMS. To create the four hightlighted dates, it divides the number of days between the start and end date into 4.

So, it _shouldn't_ matter that the hot module runs more than a month or gets extended and we shouldn't have to worry about what that query specifically is bringing back, as it doesn't really determine the data that gets displayed.

I am not sure what the culprit is of the behavior being illustrated in the image above. 1) Considering there is more than 4 highlighted dates being displayed, it seems something more funky is going on than that query returning data from other months, since that doesn't affect what gets displayed on the graph. 2) I remember seeing similar display issues when we were having issues with the timing logic a couple of weeks ago, so it could have been from that. 

As for now, the issue has seems to resolved itself with the new year. If this is in fact tied to hot module dates being extended to the next month, then we should check back in February to make sure everything looks ok. 

/cc @angaither
