### ISSUE TITLE
Cleanup build errors

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5921]
##### `ds build --install`
- [x] `WD Apache Solr: HTTP Status: 404; Message: Not Found: Not Found; Response: [error]
  Error 404 Not Found`
- [x] `WD Apache Solr: HTTP 404; Not Found: Not Found in apachesolr_cron [error]`
- [x] `WD Apache Solr: No Solr instance available during indexing. [error]`
- [ ] `WD varnish: Unable to connect to server socket 127.0.0.1:6082: Connection refused [error]`
- [x] `npm WARN engine dosomething-validation@0.2.2: wanted: {"node":"0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})`
- [x] `npm WARN engine dosomething-modal@0.3.0: wanted: {"node":"0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})`
- [ ] `npm WARN engine @dosomething/forge@6.6.2: wanted: {"node":"0.12.x"} (current: {"node":"4.4.0","npm":"2.14.20"})`
- [x] `npm WARN optional dep failed, continuing fsevents@1.0.5`
- [ ] `npm WARN prefer global babel@5.8.34 should be installed with -g`
##### `ds build; ds pull stage --db`
- [ ] `Drush status:
  <h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.blocked_ips&amp;#039; doesn&amp;#039;t exist: SELECT 1 FROM {blocked_ips} WHERE ip = :i`
- [ ] `exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dosomething.system' doesn't exist' in /var/www/dev.dosomething.org/html/includes/database/database.inc:2171`

**Comment by deezone** [comment]
`$ ds build`

```
...
Found makefile: services.make                                                         [ok]
Invalid argument supplied for foreach() make.utilities.inc:101          [warning]
```

**Comment by DFurnes** [comment]
> npm WARN engine dosomething-validation@0.2.2: wanted: {"node":"0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
> npm WARN engine dosomething-modal@0.3.0: wanted: {"node":"0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

These can both safely be ignored (especially since they're browser packages), although we should really remove the version constraint from each of these.

> npm WARN optional dep failed, continuing fsevents@1.0.5

This is an [optional dependency](https://www.npmjs.com/package/fsevents) (of one of our build tools) for an OSX-specific file watching API, so it's expected to fail on Linux. I don't think there's much we can do to "prettify" this.

> npm WARN prefer global babel@5.8.34 should be installed with -g

We're including a local version of Babel (and running it via our Webpack build) so that we can version it with our application (rather than relying on the virtual machine having it installed). I _think_ we might be able to replace our `babel` dependency with `babel-core` to silence this warning.

I can look into this at some point later on.
