### ISSUE TITLE
Revise API Reportback Item accessibility based on user permissions + status

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5929]
For the mobile app, want to allow users to see their RBs (including pending, flagged, excluded) and other user's public profiles (which includes excluded). Thus the API needs to allow more fine-grained permissions access to reportback items.

Part of the issue seems to be that Northstar uses a single authenticated admin user to hit the Phoenix API, which complicates the capacity to determine proper permissions... although not 100% sure about this.

@aaronschachter @DFurnes

**Comment by DFurnes** [comment]
Can we only authorize against the currently logged-in user, or is it possible to provide a UID with the request?

**Comment by weerd** [comment]
For the currently logged-in user, you'd need to have Northstar authenticate with Phoenix using that user for such calls, but there are other calls that I suspect NS would need to make as an authenticated admin... so it would have to be able to flip-flop between calls to Phoenix as user or admin.

**Comment by DFurnes** [comment]
So the only way to authorize a request is against the current session token? Bummer, that makes things a bit more complicated.

**Comment by aaronschachter** [comment]
Any update on this? If anything, returning all statuses would at least unblock any Profile development in LDT. cc @marahml @jonuy

**Comment by weerd** [comment]
I believe @jonuy had mentioned the possibility of, for the time being, on the app to just have both an NS auth user and then the anon user (possibly managing two tokens) and using the NS auth user to get all the RB items regardless of status... but not sure if that was going to be an attempted experiment first?

**Comment by jonuy** [comment]
To get to our ideal solution for this, it sounds like we'll need to revamp our user authentication so that user's can auth against Northstar and Phoenix in a similar manner.

I think the work involved for that is [here](https://github.com/DoSomething/northstar/issues/202) @DFurnes? And it could take a while until we get to that point.

In the meantime, from the mobile app, we really might just have to separately authenticate with the Phoenix API and manage multiple sessions (Northstar and Phoenix).

**Comment by DFurnes** [comment]
@jonuy Yup, that's probably the best course of action for now.

**Comment by aaronschachter** [comment]
The big blocker right now in mobile app is the self can't see their own reportbacks regardless of status. Isn't this just a bug since the Northstar endpoint the mobile app is using should be authenticated as an admin?

I'm wondering if a compromise would be to just keep the reportbacks public regardless of status for now as far as the public profile, instead of each mobile app maintaining two separate authenticated sessions...

**Comment by jonuy** [comment]
@aaronschachter Hm, maybe we can dive into it a little more offline, but I think the Android app is at least able to get a user's own reportback by going straight to the Phoenix API with the `rbid`. I'm assuming this is the case after a test where I logged out, cleared the local cache of data for the app, and then signed in again with that user to find the reportback info and photo listed in the user's profile.

**Comment by weerd** [comment]
I had thought that on the mobile app we were only authenticating as the user to log them in, but from that point on keeping a record of their `user_id` and then the rest of the activity on the app is done as the NS Admin user...

I'd like to avoid having to backtrack on all of the security stuff I recently added to the RBs & RB Items access for the Phoenix API. I fear changing it up will lead to other unexpected issues (potentially). 

Instead, I feel managing auth token stuff or switching the token (from user auth to NS admin auth) would be a better approach, cause once a better solution with that gets resolved the RBs & RB Items access wouldn't need to get touched again to re-enable security; it's just the resolved solution for how the app manages access the data.

**Comment by aaronschachter** [comment]
Sounds like it'd be good to have a meeting on the minds on this one. The iOS app isn't ever pinging at Phoenix `reportbacks` endpoint for the sake of keeping API requests to a minimum - a single request to `user/:user_id/campaigns` Northstar endpoint returns all of the data we need to display a user's profile.

**Comment by jonuy** [comment]
Oh right! I'd forgotten that endpoint's what's available. And... from what I can tell from briefly looking at code, it looks like that's what the Android app is doing. But you're saying this endpoint isn't giving you the reportback data?

**Comment by aaronschachter** [comment]
In the Northstar `user/:user_id/campaigns` endpoint, `reportback_data` is only included for Reportback Items which are `approved` or `promoted` - which seems to suggest that Northstar user isn't logged in as an admin (or something's buggy somewhere)

**Comment by angaither** [comment]
@aaronschachter @jonuy the is to pick this issue up after campaign run stuff is all buttoned up, which I would imagine to be next sprint!

**Comment by marahml** [comment]
Hey @DFurnes and @weerd. After following up w/ @jonuy and @aaronschachter post-API convo last week, this seems to be most pressing / high-priority launch-blocker. Based on our estimates, looks like wrapping this up by EOD thursday would allow us to hit our target launch week w/ app store submission happening in 1.5 weeks from now.

I know the first next step was discussing a solution in person. Have you two had a chance to sync?

Thanks!

**Comment by DFurnes** [comment]
@marahml I'm going to try to wrap up work on DoSomething/northstar#269 today (which should handle Northstar's part in all this). Then @weerd, @chloealee and I are going to sync tomorrow morning to make sure everything's :sparkles: stellar :sparkles:.

**Comment by aaronschachter** [comment]
Deep dive into code with @weerd, @DFurnes, @chloealee, and @jonuy today uncovered that Northstar User Campaigns endpoint (`user/:id/campaigns`) was making anonymous requests to Phoenix, which is why the `reportback_items` wouldn't exist for non-approved/promoted RB items (https://github.com/DoSomething/northstar/issues/270).

The Northstar `user/:id/campaigns` endpoint is now deprecated (https://github.com/DoSomething/northstar/pull/273). Closing this issue as it should be resolved when we include the Reportback for a given Signup within the Signups endpoint: https://github.com/DoSomething/phoenix/issues/6151
