### ISSUE TITLE
Removing Sponsor Logo Results in Error Page

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5968]
#### Current Behavior

When a campaign's sponsor is removed from the "name" field of a campaign (under edit > sponsors and partners), the "view" tab shows an error like the one shown below, for both logged in admins and unauthorized users.
#### Desired Behavior

Removing content from any previously populated field should not produce an error.
#### Steps to Replicate

Go to a campaign with a sponsor in the sponsors and partners field. Remove by deleting the text in the "name" field. Save the campaign.
#### Why This Matters

Most pressingly, a suite of campaigns is no longer sponsored, and the sponsor's logo needs to be removed.
#### Relevant Screenshots

Field:
![image](https://cloud.githubusercontent.com/assets/12396076/12072459/956a32e2-b0ad-11e5-8ad2-ab60c53d2780.png)

After content is removed from field:
![image](https://cloud.githubusercontent.com/assets/12396076/12072480/bc731e4e-b0ad-11e5-9c07-0c749360e405.png)

**Comment by namimody** [comment]
Currently seen on prod on:
https://www.dosomething.org/campaigns/not-same-old-story and https://www.dosomething.org/us/campaigns/past-picture-perfect

**Comment by namimody** [comment]
Possibly related to: https://github.com/DoSomething/phoenix/issues/4916 and https://github.com/DoSomething/phoenix/pull/4917

**Comment by angaither** [comment]
also potentially related to this bug we have with video fields #949

when field collection fields are removed the actual values in the db remain causing a an `is_empty` check to pass when it shouldn't

**Comment by sergiitk** [comment]
So the issue there was that @namimody should've clicked 'Remove' button instead of just deleting everything in the "Name" field, see at the bottom of the screenshot:

https://staging.dosomething.org/us/node/1173/edit/
![image](https://cloud.githubusercontent.com/assets/672669/12097292/90317b28-b323-11e5-9afc-f6c8bc9376e0.png)

However, now when few nodes are broken and I can't fix the partners fields on them:
https://www.dosomething.org/node/5565/edit/
The edit page fails for me on production (similar works on staging though).

I will push the a code change that prevents this from happening once and for all.
