### ISSUE TITLE
user profile campaign title updates

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5975]
ensure the user profile pulls correct campaign titles in 'doing' and 'done' sections 

![image](https://cloud.githubusercontent.com/assets/645205/12099865/42781dee-b2f9-11e5-8c78-eec0464a50fc.png)

**Comment by itsjoekent** [comment]
Should I be updating `dosomething_campaign_get_campaign_block_vars` to use campaign run titles or this _just_ for the user profile? @angaither ?

**Comment by itsjoekent** [comment]
blocked: https://github.com/DoSomething/phoenix/pull/6001#issuecomment-169714999

**Comment by mikefantini** [comment]
@deadlybutter for this, let's make sure we're sticking to campaign title and not showing campaign run title to users in the profile: https://github.com/DoSomething/phoenix/issues/5961#issuecomment-170926109

**Comment by itsjoekent** [comment]
https://github.com/DoSomething/phoenix/pull/6001#issuecomment-171330591

**Comment by angaither** [comment]
we still want to remove the campaign run titles that are currently shown on the profile

**Comment by itsjoekent** [comment]
i just checked on my user profile in Thor https://thor.dosomething.org/us/user/2632038 and I don't see where campaign run titles are being used. I even edited the run for Incognito cleanup and Trashy Treasure to make sure.

**Comment by angaither** [comment]
@deadlybutter I believe it's when a campaign has been closed

**Comment by itsjoekent** [comment]
I ended the run for Trashy Treasure (heres the run https://thor.dosomething.org/us/node/6292) and the profile still doesn't display it https://thor.dosomething.org/us/user/2632038

**Comment by mikefantini** [comment]
@deadlybutter see Teens for Jeans 2015 as an example where the profile is using the campaign run title in the profile you linked below.

![image](https://cloud.githubusercontent.com/assets/6330971/12560139/0ace6226-c367-11e5-9aa8-b7c404e8bdfe.png)

https://thor.dosomething.org/us/user/329195

**Comment by chloealee** [comment]
I'm also having a hard time replicating this one. Went to the same URL in @mikefantini 's screen shot and not getting those campaigns anymore: https://thor.dosomething.org/us/user/329195

**Comment by chloealee** [comment]
The only reason I can think of why it pops up as "Teens for Jeans 2015" is based on the placeholder I was working with before we decided on what the title of the nodes should be (https://github.com/DoSomething/phoenix/issues/5961#issuecomment-170926109).  

The placeholder was title of campaign + current year (which is also outdated in [this comment](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign_run/dosomething_campaign_run.install#L39)). You can see me fidgeting with these values [here](https://github.com/DoSomething/phoenix/commit/bd1eab33056a903260841100a748eec558be3e69) when I was testing. I've made this change on my branch but will wait to push up for PR until we solve what's going on here.

Not sure if this makes sense though because with the new code that is merged now, "Teens for Jeans 2015" shouldn't have appeared for @mikefantini 3 days ago...

**Comment by angaither** [comment]
@chloealee there's a show more to view older reportbacks, and when you click that as many times as it lets you, these campaigns appear and the title is the run title, not the campaign title. 
![image](https://cloud.githubusercontent.com/assets/645205/12679609/0fd12e16-c673-11e5-90d6-8884219867ef.png)

**Comment by chloealee** [comment]
ah I see now - thanks for the clarity @angaither !

**Comment by angaither** [comment]
Oy, there's been an understanding with this one. 
The title only updates to the run title when campaign data is archived. So, since we are unarchiving all data, this won't be a problem anymore. 
closing this issue meowt.
