### ISSUE TITLE
Facts - multiple sources

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#598]
When entering a fact into the database, an editor should be able to attribute the fact to multiple sources.

These sources should be listed individually in action page or 11 facts pages.

i.e. Puppies are awesome and make people happy [1][2].
1. Ben Kassoy. Foundation of the foundation of foundations.
2. Google. www.google.com

**Comment by aaronschachter** [comment]
Our best bet here is to implement this as a Field, to easily account for multi-value.  It does beg the question of whether or not a custom entity is worth at at this point, since we'll be adding a field. If we created a Fact as a node, we could use EntityConnect for easy fact creation/editing from within the Campaign and Fact Page forms.

**Comment by aaronschachter** [comment]
Depends on #606 -- Source will be a multi-value longtext field.  Will remove "Source URL" field as per discussion with @mikefantini this morning.

**Comment by aaronschachter** [comment]
This was resolved by #612
