### ISSUE TITLE
update goals counters

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6004]
custom settings page on nodes, have a goals section where it runs totals for impact and reportbacks, these need to we re-written to only include the impact of the current run
it also needs to be updated to deal with multiple translations of the node. see #6065

**Comment by mikefantini** [comment]
Note https://github.com/DoSomething/phoenix/issues/6065#issuecomment-173263557 from @angaither

**Comment by itsjoekent** [comment]
sorry I'm not entirely sure what you are asking for @angaither

**Comment by angaither** [comment]
@deadlybutter the things that calculate the total quantity [here](https://github.com/DoSomething/phoenix/blob/6b5a9db99de9725ced28ea70527236e4e26fa234/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.cron.inc#L11)

@mikefantini I think the progress update is the only place the campaigns team checks for impact, correct?

**Comment by mikefantini** [comment]
@angaither I think they actually mainly look at it in the /rb/reviewed section

**Comment by angaither** [comment]
ok, that's fine I think `dosomething_reportback_get_reportback_total_plus_override` still gets the total from that cron function above

**Comment by itsjoekent** [comment]
I thought using DISTINCT might fix it but no luck there. Regardless I've fixed the run issue, just need to get the other half (duplicates due to translations)

**Comment by angaither** [comment]
@deadlybutter you can join on two things so both id & language
you can just do the source language of the node since we aren't totally different totals for different translations

**Comment by itsjoekent** [comment]
ok

**Comment by itsjoekent** [comment]
that did it

```
SELECT n.nid, SUM(rb.quantity) as total, run.field_current_run_target_id as run_nid
FROM node n
INNER JOIN field_data_field_campaign_status s on n.nid = s.entity_id AND n.language = s.language
INNER JOIN dosomething_reportback rb on n.nid = rb.nid
INNER JOIN field_data_field_current_run run on n.nid = run.entity_id
WHERE n.type = 'campaign'
AND s.field_campaign_status_value = 'active'
AND rb.flagged = 0
AND rb.run_nid = run.field_current_run_target_id
GROUP BY n.nid
```

**Comment by mikefantini** [comment]
Hmmm @deadlybutter I'm a little confused by some of the stuff i"m seeing here:

Obviously the data is a bit out of sync at this point, but I find it odd that thor and prod are so off between, especially because for 3755 and 1144 have the same number of rb images:
- https://www.dosomething.org/us/node/3755/rb/reviewed and https://thor.dosomething.org/us/node/3755/rb/reviewed
- https://www.dosomething.org/us/node/5775/rb/reviewed and https://thor.dosomething.org/us/node/5775/rb/reviewed
- https://www.dosomething.org/us/node/1144/rb/reviewed and https://thor.dosomething.org/us/node/1144/rb/reviewed

Also bizarre that https://thor.dosomething.org/us/node/362/rb/reviewed has 0 for Total Reportback Quantity...

**Comment by itsjoekent** [comment]
talked w/ Fantini -- problem is we didn't add run nid's to all the signups / reportbacks

this line in the code in the cron job

```
INNER JOIN field_data_field_current_run run on n.nid = run.entity_id
```

was added because we assumed all reportbacks would have a run_nid by now.

the reason prod has higher numbers than Thor is because since the DB import on Thor, people have been reporting back on Prod whereas Thor has remained unchanged. The numbers are low because only the most recent reportbacks have a run nid attached.

**Comment by itsjoekent** [comment]
yeah, now that I know this code is only on thor, this makes a lot of sense.

**Comment by mikefantini** [comment]
Before we deploy this to prod we need to remove the progress override on https://www.dosomething.org/us/node/1144/custom-settings

**Comment by angaither** [comment]
@mikefantini the fix for this is already on prod

**Comment by mikefantini** [comment]
@angaither there is a discrepancy between what I'm seeing in SQL and what the site is showing.

Are you saying that we fixed in prod that all reportbacks have a run_nid by now?

**Comment by angaither** [comment]
@mikefantini I'm saying the cron that gets the numbers is correct, and is in production. 
But reportbacks don't all have `run_nid`s so it appears lower.
I think this issue can be closed
