### ISSUE TITLE
Add ability to close campaign groups

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6119]
#### Current Behavior

Currently there is no way to close a Campaign Group. Instead, in order to summarize what happened while a Campaign Group was live we unpublished the group, create a dummy campaign, close the dummy campaign, and create URL redirects.
#### Desired Behavior

The ideal is that we could summarize what happened while the group was live by closing the group itself. It would look exactly like a closed campaign looks and would be able to use the same info that we have on runs.
#### Why This Matters

The current method for closing groups is hacky, confusing, and takes way too many steps to complete.

**Comment by mikefantini** [comment]
#### Current Behavior

Currently there is no way to close a Campaign Group. Instead, in order to summarize what happened while a Campaign Group was live we unpublished the group, create a dummy campaign, close the dummy campaign, and create URL redirects.

#### Desired Behavior

The ideal is that we could summarize what happened while the group was live by closing the group itself. It would look exactly like a closed campaign looks and would be able to use the same info that we have on runs.

#### Why This Matters

The current method for closing groups is hacky, confusing, and takes way too many steps to complete.
