### ISSUE TITLE
Embed Reportback and Reportback Items within Signup response

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6151]
Now that we're using Phoenix as the source of a new Signups endpoint (#6110), it'd be great to include a Signup's corresponding Reportback if it exists.

This could allow a client to render a User Profile in a single API request (like how the `user/:id/campaigns` Northstar endpoint currently does).

**Comment by aaronschachter** [comment]
We'll need to make sure admin's have access to all Reportback Items regardless of status, so clients can render an authenticated user's Self Profile when accessing this endpoint (non-approved Reportback Items like `pending` or `excluded` or anything should be visible). (refs #5929)

Example response:

```
{
  "data": {
    "id": "2",
    "created_at": "1393010906",
    "campaign_run": {
        "id": "1982",
        "current": true,
    },
    "campaign": {
      ...
    },
    "reportback": {
      // Make sure to include reportback_items here so we have access to the media.uri, caption, status
    }
  }
}
```

**Comment by jonuy** [comment]
@weerd @chloealee @aaronschachter Thoughts on also including the tagline/call-to-action in the `campaign` object that's returned in the signups call? Asking because it looks like we should be including it when displaying campaigns in a user's profile on the mobile app.

![screen shot 2016-02-17 at 3 08 54 pm](https://cloud.githubusercontent.com/assets/696595/13123202/30a52d34-d589-11e5-9b9a-afeca76165cc.png)

It goes along the same lines as this issue with only wanting to make a single API call to get all the stuff we need to render a profile.

(Let me know if this should be a separate issue)

**Comment by aaronschachter** [comment]
:+1: for adding `campaign.tagline`! That us gets closer to avoiding loading all 250+ campaigns upon app startup in iOS (which is only way we're currently able to display it -- unless we made more queries to GET  `campaigns` :no_good:  )

**Comment by aaronschachter** [comment]
While we're in the `campaign` object -- we need the Campaign `status` as well in order to render the User profile within a single API request. We need to filter any Doing campaigns that have a status of `closed`.

Actually, we'd need the Campaign `type` exposed as well so we can filter out SMS games too: On the web, we write a Signup to the database if an authenticated user signs up for a SMS game.

**Comment by chloealee** [comment]
Great, will work on adding that too! @aaronschachter I think it makes sense to create a new issue and PR for the additions? I'll create the issue now and tag you and @jonuy to make sure I got everything correct!
