### ISSUE TITLE
Competitions signup popup

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6169]
### signup form updates
- add 'competition' type to signup data form
- don't display this link in the from `stuff you need section` if competition, by making link text not required
- add fields to customize the submit and skip button text
### db updates
- add a col to `dosomething_signup` to have competition

this could be either boolean value, or a boolean and when the user actually gets divided into a group, it updates to the gladiator competition id

**Comment by angaither** [comment]
Here's what the signup data form looks like without any work for my beautiful competition.

At minimum we need to be able to customize the `submit` and `skip` text
![image](https://cloud.githubusercontent.com/assets/645205/13091711/83b956a4-d4ca-11e5-98ef-16bc795b1ec9.png)

we also probably need to add a 'competition' type to the data form so we can do #6170 

because it's impossible to tell that this was a competition signup
![image](https://cloud.githubusercontent.com/assets/645205/13091818/f70be09a-d4ca-11e5-83c7-4bdd274d3295.png)

**Comment by sbsmith86** [comment]
@angaither just double checking this "type" field that we need to add doesn't exist right?

**Comment by angaither** [comment]
@sbsmith86 correct

**Comment by sbsmith86** [comment]
@angaither sorry one more ?.. are there any other types of forms besides competitions?

**Comment by angaither** [comment]
there's currently no type on the signup form. I think the type doesn't really need to be a dropdown, it could just be a checkbox 
![image](https://cloud.githubusercontent.com/assets/645205/13117995/2b1b9b6e-d570-11e5-8b43-28603a9a5cf5.png)

**Comment by sbsmith86** [comment]
got it got it . thanks.

**Comment by angaither** [comment]
@aaronschachter do the changes outlined in this issue above make sense? 
we need most of the functionality of the signup form, but it's a different type.

**Comment by sbsmith86** [comment]
I actually have some more Q's:
- autofill form header and copy based on a formula
  Is this formula created already or coming soon?
- maybe save `why_signed_up` to `competition` ? 
  I see the option to add a sign up reason field. But not sure what is meant by save it to `competition`

**Comment by aaronschachter** [comment]
Makes sense :+1:. What would the default `type` be set to?

@weerd and I were chatting about adding a Competition ID column to the `dosomething_signup` table too - but maybe that's a separate issue? To store whatever competition the user is in. Although not sure if we need that in Phoenix

**Comment by sbsmith86** [comment]
@aaronschachter @angaither maybe the default type is `campaign`?

**Comment by angaither** [comment]
@aaronschachter @sbsmith86 maybe the term `type` is misleading, I mostly just meant a checkbox under `prompt after signup` that says `competition signup` 

as far as a comp id on the signup, the way we are building it now, I don't _think_ it will be needed in phoenix

> @weerd and I were chatting about adding a Competition ID column to the dosomething_signup table too - but maybe that's a separate issue? To store whatever competition the user is in. Although not sure if we need that in Phoenix

**Comment by sbsmith86** [comment]
@angaither ya ya just talked with @aaronschachter and we are all on the same page now

**Comment by sbsmith86** [comment]
@angaither @mikefantini  I'm trying to think of a solution for the use case when we run a competition on a campaign like thumb wars, were we need the competition prompt as well as a form to collect user data. 

I think we can either 

a) make the competition sign up form a separate form from the signup_data_form so that we can like link from one form to another. i.e. a user is prompted to enter a competition, they accept or decline and are taken to another screen where they can enter their address or whatever is needed for the campaign.

b) If the `competition signup` checkbox is checked, then we display a checkbox with some copy about what the competition is on the data collection form that allows the user to also sign up for the competition.    So we sorta combine the two.

**Comment by mikefantini** [comment]
@sbsmith86 @angaither we actually have something sort of for this already because for Teens for Jeans previously we needed to both collect school and user address so @aaronschachter added the Shipment Form to Custom Settings as well. This may still need to be reworked a bit from an experience stand point and refactored accordingly, but we should have most of the pieces in place to allow for this.

**Comment by mikefantini** [comment]
Also for the sake of trying to keep things simple I'm ok with just using the Shipment Form in this scenario without any refactoring and the user won't be prompted to give their address so much as the option will just be available to them in the Stuff You Need section.

If this eventually becomes an issue we can always try to address it then?

**Comment by angaither** [comment]
okay, we will want to test for that and refactor if needed
