### ISSUE TITLE
Allow admin API users to see all reportbacks on index endpoint

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#6176]
References discussion in DoSomething/northstar#279 and "background context" from #6174:

> This only works for the show endpoint and doesn't work for the index collection endpoint. We would need to do some further work to allow unreviewed RBs to show if querying via the /reportbacks index collection endpoint do the the array of params that need to be accounted for (ie: such as the status param).

While updating the "show" endpoint should fix the biggest issue here, it'd be good to get around to updating the `/reportbacks` index so we don't have the weird UX situation of a user submitting a reportback and not seeing it on their profile gallery.

/cc @weerd @aaronschachter

**Comment by chloealee** [comment]
@weerd sorry I think I'm getting a little confused again for this! Is it correct to change [this](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.query.inc#L49-56) block to something like: 

```
  if (user_access('view any reportback') && isset($params['status'])) {
    if (isset($params['status'])) {
      if (is_array($params['status'])) {
        $query->condition('rbf.status', $params['status'], 'IN');
      }
      else {
        $query->condition('rbf.status', $params['status']);
      }
    }
  }
  else if ((is_array($params['status'])) && ((in_array('flagged', $params['status'])) || (in_array('pending', $params('status'))))) {
      if (is_array($params['status'])) {
        $query->condition('rbf.status', $params['status'], 'IN'); // omitting pending and flagged 
      }
      else {
        $query->condition('rbf.status', $params['status']); // omitting pending and flagged 
      }
  }
```

**Comment by weerd** [comment]
I don't think so. user access shouldn't affect which statuses they can request, just which get shown... I think the logic is getting a bit convoluted there and having trouble following. Can we chat through in comments in this issue what we're trying to achieve again? I think I'm lost and might help chatting it through...

**Comment by chloealee** [comment]
@weerd yeah I think I'm misunderstanding as well! Looping in @DFurnes who might be able to help clarify? 

As I understand, we want admins to be able to view `flagged` and `pending` reportbacks on the index view of `/reportbacks` - is this correct? 

I'm also confused why this would only work for the `show` since it looks like the `index` follows the same rules that was made in @weerd 's previous fix in #6174?

**Comment by weerd** [comment]
> I'm also confused why this would only work for the show since it looks like the index follows the same rules that was made in @weerd 's previous fix in #6174?

I was going to look into that this morning and then had the whole `global $language` fiasco... I know there's a very specific reason; will look again during lunch! :smile:

**Comment by chloealee** [comment]
thanks @weerd !

**Comment by weerd** [comment]
ok, so I think it actually turns out to be much simpler than I thought entirely @_@

**Comment by weerd** [comment]
The issue was that on index collections we have to account for other things in the url params etc. On the show method, we only deal with one parameter the specified `rbid` and then if we want to restrict flagged ones from showing up, we add an extra params before the query starts to indicate `$params['flagged'] = FALSE;` which is nice and simple.

But on the index, there's a bunch of params set, including the `flagged` one... so to allow access to admins, we can actually just remove it so admins can access all:

``` php
function dosomething_reportback_filter_flagged_reportbacks($params) {
  if (user_access('view any reportback')) {
    if (isset($params['flagged'])) {
      unset($params['flagged']);
    }

    return $params;
  }

  // Only show reviewed and/or un-flagged Reportbacks.
  $params['flagged'] = FALSE;

  return $params;
}
```

Then if request is from admin, they just ask for everything like this:

```
/api/v1/reportbacks?status=pending,flagged,excluded,approved,promoted
```

**Comment by weerd** [comment]
A couple side notes:

It's a little confusing that Reportbacks have a `flagged` status and ReportbackItems have a `pending,flagged,excluded,approved,promoted` (which includes flagged also)...

@DFurnes @chloealee upon further inspection I don't actually know how this issue would have actually affected the own user's gallery. The `/reportbacks` endpoint index collection doesn't actually let you do a query for a specific user's list of reportbacks... Instead, via the `/signups?user=:id` endpoint I believe that happens by collecting all the individual `rbid`s and then running a `Reportback::get(:id)` on each of them and since it's being done as an admin via DS app, that should have still collected flagged RBs since that was adjusted via the show method.

**Comment by angaither** [comment]
@_@

**Comment by chloealee** [comment]
@weerd thank you for doing all of this investigating and describing things so clearly! Makes sense what you're saying about `/reportbacks` and how you can't actually query by `user`. 

So in order to close this issue, do we just need to add the fix you mentioned in [this commen](https://github.com/DoSomething/phoenix/issues/6176#issuecomment-187906285)t?

**Comment by weerd** [comment]
@chloealee yep, I think so. But make sure to throughly test. It _seemed_ to work when I tried it, but I didn't do extensive test. I was just trying to remember what the core issue was :)

**Comment by chloealee** [comment]
cool, thanks @weerd !
