### ISSUE TITLE
500 Error when posting signup to Treat Yo Friends

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6251]
#### Current Behavior
- i’m getting a 500 error when posting a signup to Treat Yo Friends on prod (ID 5646). shot in the dark is that maybe it’s because there are two different Run id values for `global-en` and `en`: https://www.dosomething.org/api/v1/campaigns/5646. Only campaign i’ve been getting the 500 error on.

Signing up for Yo Teach worked fine (has a `global-en` and `en` — but both are the same run ID (https://www.dosomething.org/api/v1/campaigns/6621)
#### Desired Behavior
- We should receive a 200 success code back, the campaign status is set to `active`.
#### Steps to Replicate
- in mobile app: Actions > Mental Health > Treat Yo Friends. Tap "Do This Now"
#### Relevant Screenshots + Links

![img_0317 png](https://cloud.githubusercontent.com/assets/1236811/13618177/8e52aac0-e537-11e5-8197-ce4631fce6a5.jpeg)

**Comment by aaronschachter** [comment]
cc @jonuy (or any Android users) -- as a sanity check -- do you get same error?

**Comment by angaither** [comment]
@aaronschachter I think the language of the admin user that posts the request from NS was set to the wrong thing. [global english] 
I set it to english please try again!

**Comment by angaither** [comment]
actually, I just tried this and still got the "oops" message :cry:

**Comment by jonuy** [comment]
Sanity check confirmed. We get the 500 on Android too.

**Comment by angaither** [comment]
Northstar sends requests as the api user. (northstar-api)
that [user's lang was `global english`](https://thor.dosomething.org/us/user/2800057/edit)
the [global english run of yo teach was closed](https://thor.dosomething.org/node/6621/edit/en-global)
the signup failed in the access check if the node is active [here](https://github.com/DoSomething/phoenix/blob/9abb92e54f08fe7849f694f201a16bdb19dc6c0e/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L191)

Since we are showing only english content/nodes in the api
I changed that user's language to `english`
and the signup works.

ideally if we open the app up to move languages we will need to change the check for `is_active` & `is_closed` should take a uid argument so you can pass the user in the api's language, instead of using global user if there's a user passed.

**Comment by aaronschachter** [comment]
@angaither We're requesting the GET campaigns as an anonymous user in iOS, and use the `status` value returned to render a closed state if `closed`.  What language does the API use to determine the Campaign status for anonymous requests? 

Question came up while documenting this convo in the [iOS wiki](https://github.com/DoSomething/LetsDoThis-iOS/wiki/DS-API#current-user-language--campaign-status)

**Comment by angaither** [comment]
@aaronschachter the API returns all content in `english`
