### ISSUE TITLE
Rearrange RB Admin Interface for Incremental UX Enhancement

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6327]
#### User Story

Reviewing reportbacks is something we want to rehaul, to make the experience more fun for admins (should be the best part of their job), more user friendly, and the process more accurate. Until we take the time to fully revisit the experience, there are a few small enhancements we can make:

Currently, the view looks like this:
![image](https://cloud.githubusercontent.com/assets/12396076/14080919/deee1200-f4d5-11e5-8ff0-3169438888d8.png)

We propose changing the column arrangement to the following, like the drawing below:
- campaign name
- ROTATE radial buttons
- photo (placement of caption and answer to "why is this important to you" will stay where they are)
- impact quantity, bolded
- OP (approval) radial buttons

and removing the RBID: FID column on the far left.
#### Additional Information (optional)

@angaither could you explain a bit here about where all this view appears and if the code we would change on this view: https://thor.dosomething.org/us/node/5411/rb would affect any other parts of the site/experience?
#### Why This Matters

There are over 36,000 reportbacks that are currently unreviewed. Additionally, the current set up does not place enough prominence on the reportback quantity, making it easy to overlook when you have a lot of reportbacks to review.
#### Relevant Screenshots and Links

![image](https://cloud.githubusercontent.com/assets/12396076/14080505/940b3ff8-f4d3-11e5-89c8-2aebd7d69385.png)

cc @lkpttn @mikefantini

**Comment by chloealee** [comment]
@namimody do we want to get rid of the `SUBMITTED` column as well? Also, for this PR, I'm going to add the User's First Name as well (Refs #6323). Maybe this should go between `QUANTITY` and `OP` like the below?
![screen shot 2016-04-11 at 3 30 57 pm](https://cloud.githubusercontent.com/assets/9019452/14439685/6f277d1e-fffa-11e5-8f95-ce433a29eaae.png)

**Comment by namimody** [comment]
Hi @chloealee! A few thoughts, and cc @aaronschachter:
- I do think that adding the first name is a nice addition, I think it would also help reviewers see that one person uploaded multiple photos more easily! We should just keep #6323 open, because we still would not be showing the avatar. However, I _think_ that @angaither was wary about making changes outside of removing and rearranging columns because of the finicky nature of the RB admin tool. Thoughts?
- As for placement -- I think it would be best to have the Name appear in a column between the campaign name and the rotate radial buttons. (One of the things we are hoping to accomplish with this set up is to move the quantity as near to the approval choices as possible, so that the quantity is more easily visible and therefore more accurately factored into the reviewing decision.)
- My bad! Let's keep the submitted timestamp column, that helps leads know how far back the reportbacks are that they are looking at. I think that could be the left-most column.
- Could we bold the impact quantity too? :)

**Comment by chloealee** [comment]
thanks @namimody ! I think the first name shouldn't be a big deal because I'm just loading the user from the uid of the reportback. Confirming with @aaronschachter that shouldn't be that big of a deal re: @angaither 's concern of the finicky nature of the RB admin tool, right? 

Will fix the placement and boldness - thanks @namimody !

**Comment by aaronschachter** [comment]
I think @angaither has good reason for concern -- loading the User could throw an unexpected wrench into this form which has historically inflected some dev pains. 

Since we're looking to remove this form out of Phoenix and into a new app anyway, it's probably a little bit safer to hold off on adding the first name @chloealee.

**Comment by chloealee** [comment]
okay sounds good, thanks @aaronschachter !

**Comment by namimody** [comment]
Thanks @chloealee and @aaronschachter! Chloe, when you have a new screenshot of what this would look like, could you share it here? THanks!

**Comment by chloealee** [comment]
sure thing! here you go @namimody ! Let me know if this is okay and I'll submit the PR!
![screen shot 2016-04-12 at 12 46 48 pm](https://cloud.githubusercontent.com/assets/9019452/14468207/af251b9e-00ac-11e6-815f-c1b359e8a125.png)

**Comment by chloealee** [comment]
@namimody  - @aaronschachter had a good suggestion to make the quantity even bigger since the bold doesn't stand out that much - here's an updated screen shot! 
![screen shot 2016-04-12 at 1 02 05 pm](https://cloud.githubusercontent.com/assets/9019452/14468699/deec6b1e-00ae-11e6-8c4c-efc6a545fc1f.png)
