### ISSUE TITLE
Patch international branch with security updates

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#6331]
See DoSomething/devops#87

**Comment by sergiitk** [comment]
## _Patch international branch with security updates_

Current [International branch](https://github.com/DoSomething/phoenix/tree/7e32c6bb143bf3abb8f122fa3847ee13872b9d64) is outdated.
- [x] <del>Make a list of updates to include</del> https://github.com/DoSomething/devops/issues/87#issuecomment-212490792
- [x] Patch the branch
- [x] Test the branch
- [x] Deploy to production

**Comment by sergiitk** [comment]
Hi @andrea! Need your opinion. I’m patching international with security fixes. I cherry picked relevant version updates from the main branch (see #6386).

And everything is fine, except I don’t know what should I do with Features module patch. Because it needed an update for 7 minor versions (7.x-2.2 to 7.x-2.9), there are some changes in the export syntax. Normal procedure is to recreate all feature based modules, so I did it for `dev` branch, see #6382.

However, features `intl-sites` branch is outdated and feature modules are significantly behind `dev`. It's not possible to easily cherry pick this updates from #6382. I can recreate feature modules in `intl-sites` branch the same way I did in `dev`, but it'll take some time and it's risky.

Alternatively, we can leave it all like this. Feature modules should work fine, except they will be displayed as 'Overridden'. So the question is — does it really worth it and should invest my time in it?

cc @sheyd

**Comment by angaither** [comment]
@sergii-tkachenko let's go with the `overridden` route

**Comment by Andrea** [comment]
Hi, wrong handle

**Comment by sergiitk** [comment]
Wrong handle?

**Comment by sergiitk** [comment]
Ah, sorry @Andrea, confused this with Slack. My apologies.
