### ISSUE TITLE
Inverse banner padding on mobile sized browsers.

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6363]
#### Current Behavior

On mobile, the Step 4 inverse banner pattern has incorrect padding.
![screen shot 2016-04-11 at 11 55 39 am](https://cloud.githubusercontent.com/assets/1865372/14433586/da7594fc-ffdc-11e5-92f5-987b5c09c1f0.png)
#### OS/Browser (optional)

Mobile sized browsers, all

**Comment by DFurnes** [comment]
Tricky! So this is happening because we switched container spacing to use margins rather than padding. On mobile, the [container block's margin is collapsing and being lost outside the container](https://cloud.githubusercontent.com/assets/583202/14434806/d104209a-ffe2-11e5-8c25-8ab73f73b875.png)... on desktop, this doesn't happen because the `float: left;` on the `.container > .wrapper` creates a new block formatting context.

I think a good fix would be to add a universal `float: left` or `overflow: hidden` to all `.container > .wrapper`s, regardless of breakpoint.

/cc @weerd Does that sound reasonable?

**Comment by DFurnes** [comment]
@weerd @sbsmith86 I put up a quick fix for this in #6365. Let me know if either of you can think of any better solutions!
