### ISSUE TITLE
Users aren't (always) getting ported to NS 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6406]
#### Current Behavior

seeing a few (3) users who aren't being ported into gladiator for competitions and it looks like that's b/c the user doesn't exist in NS. (UIDS: `3812330`, `3814753`, `3844143`)
#### Desired Behavior

people should exist in NS after their accounts were created. 
#### Steps to Replicate

no idea.
#### Why This Matters

people can't live the lives they choose, and do things like sign up for the app, or get competitions messaging. 
#### Countries Affected (optional)

the whole damn 🌍

**Comment by DFurnes** [comment]
Super weird. I see `3812330` and `3844143` in the request log with two 404s because it couldn't update a Northstar record with that UID... no records of having any issues migrating or creating them.

The first two accounts were registered on 04/08/2016, and the third on 4/17/2016... so they _should_ exist in the logs (although I did clear out a bunch of 200s at one point since the table was getting super large).

Hmmmm.

**Comment by DFurnes** [comment]
And none of those Drupal IDs or emails exist in Northstar. I think it'd be a good idea to try to manually re-migrate each of those records to see if anything goes wrong, but I'm still at a bit of a loss for the root issue.

**Comment by angaither** [comment]
I thought the update in northstar also created a new user if on didn't exist?

**Comment by DFurnes** [comment]
@angaither We've been using the `POST users/drupal_id/:uid` route to explicitly update that particular Northstar account from Phoenix if their profile changes, so it doesn't "upsert" if the given UID isn't found.

**Comment by angaither** [comment]
@DFurnes should the catch handle if the UID isn't found?

**Comment by DFurnes** [comment]
Yeah, that'd probably be a good idea.

**Comment by DFurnes** [comment]
When a user tries to update their profile, Phoenix will now catch 404s and try to create that missing Drupal ID (see #6411). I'm going to keep this open since we've probably got other root causes to patch up for this.

**Comment by angaither** [comment]
@DFurnes I'm still seeing lots of 404s in the `gladiator_failed_task_log` 
I'm wondering if we do need to handle this is another way. those users aren't updating, they are normally either registering or signing up for a campaign and they are now always stuck in the failed log, unless we manually port them over.

**Comment by angaither** [comment]
actually looking into these users I might have found a pattern they all have registration from niche
additionally these bugs are true for everyone I've checked so far
- they all are `en-global`users even though the address is United states (#6159)
- they have random strings instead of usernames set (#2753)
- the user isn't getting ported to northstar

**Comment by DFurnes** [comment]
Users should now be saved with the correct language based on their provided `country` code (#6463). And users registered via the API will now have their UID saved as their "name" as well (#6502).

The last issue is potentially a bit trickier, since we hit this endpoint _from_ Northstar when setting up a new mobile app user's Phoenix account. Maybe a good interim fix (until all users can be created through Northstar) would be to add an optional query param that can allow Northstar to opt-out of forwarding users back to itself?

**Comment by DFurnes** [comment]
Users created through the API should be getting forwarded to Northstar once #6510 is deployed, with one additional request being made from Phoenix to Northstar each time a Northstar user is created with the `create_drupal_user=true` parameter (until DoSomething/northstar#360 is merged).

**Comment by angaither** [comment]
@DFurnes just took a look at the failed task log again and it seems like we have a bunch of these from this AM

**Comment by DFurnes** [comment]
Oooof, will take a look! 😬

**Comment by DFurnes** [comment]
All the failed tasks in the log share the same value for the `timestamp` column, which is a bit of a head scratcher. They all started as `1465481367`, and switched to `1465484700` a little later! 💭 ⌚ 

It looks like Gladiator had a fatal error of some kind for _some_ of these requests, since 13 of those users are showing `500 Internal Server Error` as the error response. These users all exist in Northstar with the correct profile information, so retrying these may get things back on track.

The remaining 11 users have entries in the Northstar request log, with a couple of different errors:
- One was an old sync issue that hasn't gotten resolved by [the error handler](https://github.com/DoSomething/phoenix/pull/6411/commits/94927874146979b5eadfdcd208f1f7c5c28c9b4b) we added. Not sure why that is, but can continue to look into it. (`3824208`)
- 4 don't exist in Northstar because they registered on Phoenix using an existing user's phone number, so Northstar refuses to register the account when forwarded from Phoenix. (`3897272`, `3909908`, `3933862`, `3937525`)
- The remaining 6 don't have _any_ entries in the Northstar request log, even though their UIDs indicate they registered pretty recently, which is really strange. Not sure what to think about these ones. 😕 (`3902230`, `3908161`, `3911084`, `3911730`, `3912408`, `3823604`)

**Comment by DFurnes** [comment]
Logs are [now working](https://git.io/voKf4) on Gladiator, and it seems like [this](https://github.com/DoSomething/gladiator/blob/56b5b01af45eaa7a597763cf8b69e441f1c5a965/app/Services/Manager.php#L87) might be the line that's causing the 500s:

```
2016-06-21 13:59:41] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/gladiator/releases/20160620142908/app/Services/Manager.php:87
Stack trace:
#0 /var/www/gladiator/releases/20160620142908/app/Services/Manager.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/gladia...', 87, Array)
#1 /var/www/gladiator/releases/20160620142908/app/Http/Controllers/CompetitionsController.php(140): Gladiator\Services\Manager->exportUsersCsv(Array)
#2 [internal function]: Gladiator\Http\Controllers\CompetitionsController->export(Object(Gladiator\Models\Competition), Object(Illuminate\Http\Request))
```

That error only occurs once in the logs though (and is the only fatal error). I wonder if failed jobs aren't being re-triggered successfully since there _should_ be 13 of those right? 😕 

/cc @weerd @angaither

**Comment by angaither** [comment]
I'm going to "well actually" and say it doesn't look like that's the issue :neckbeard: 
it _seems_ like the `500s` in the failed jobs [are getting re-triggered](https://jenkins.dosomething.org/job/Cron-Production/9875/console) you can see each user not making it in on every cron.

but for all of these people who are currently in the log didn't make it fall into two cases
1. people opted into birthday mail, which is now closed
2. people opted into thumb wars, which is open, but they are global users and the `run_nid` doesn't match what we are running the competition on.

**Comment by DFurnes** [comment]
I may be being stupid here, but shouldn't 500s that are occurring hourly on Gladiator be showing up in the logs there? Why would a closed Phoenix campaign cause a 500 response from Gladiator?

**Comment by angaither** [comment]
@DFurnes probably, yes it should be showing up more than one time. 
and sorry the campaign isn't closed (I mean it might be) but the competition waiting room is closed

**Comment by DFurnes** [comment]
> and sorry the campaign isn't closed (I mean it might be) but the competition waiting room is closed

Ohhhhh, I see. That makes sense.

**Comment by angaither** [comment]
ANNYYYWAYS I'm going to clear out those users and leave this open and check back in l8r.

**Comment by angaither** [comment]
Still seeing people 404 b/c they don't have NS accounts, but I think that's b/c we are still in the process of fixing up duplicate accounts. uids (`3897430`, `1899157`, `3990990`, `3993996`)

**Comment by angaither** [comment]
Seeing something strange here
people who are successfully auth'ed against NS (getting a `200` response in the log) do not have a NS id saved to their account

seems we have about ~2 million records with `NONE` or `null` as the NS id

```
select count(*)
from users u
inner join field_data_field_northstar_id ns on ns.entity_id = u.uid
where (ns.field_northstar_id_value is null or ns.field_northstar_id_value = 'NONE');
```

I was stumbled upon this by running a query to figure out why people are missing from compeitions.
Since we have truncated the `dosomething_northstar_request_log`  it's hard to tell how many people are in this situation.
from running this query below, there are people who have a successful `200` response from NS, but no id. 
There are also people who got a `400` from the migrate script due to an upsert conflict

```
select s.uid, ns.field_northstar_id_value, u.mail, u.language, from_unixtime(timestamp), nsl.op, nsl.response_code, nsl.id
from dosomething_signup s
left join users u on u.uid = s.uid
left join field_data_field_northstar_id ns on ns.entity_id = s.uid
left join dosomething_northstar_request_log nsl on nsl.uid = u.uid
where (s.nid =2710 and s.run_nid = 7066
and s.competition = 1)
and (ns.field_northstar_id_value is null or ns.field_northstar_id_value = 'NONE')
```

**Comment by DFurnes** [comment]
I'm hoping that this should be less of a problem once we finish this latest pass of the export script.

So far 1,344,369 users have been successfully processed, and we have 1,354,047 users with Northstar IDs in the `authmap` table (including values inserted on login/register). Only 3,808 users returned a non-successful status code when trying to sync their profile. And 2,175 of those are because of invalid email addresses.

We should definitely think about checking and re-saving the Northstar ID on profile updates, but it is probably unlikely to be as much of an issue in the future...? 😬

**Comment by DFurnes** [comment]
To double-check that we're not still writing nulls – here's a check for inconsistent data between `authmap` and `field_northstar_id`... none so far! :v: 🔀

``` sql
SELECT * FROM authmap a
LEFT JOIN field_data_field_northstar_id n ON a.uid = n.entity_id
WHERE a.authname != n.field_northstar_id_value;
```

**Comment by angaither** [comment]
who cares, we are SET with oauth.
