### ISSUE TITLE
Expose Action Guide fields for the mobile apps.

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6412]
#### User Story

We only display the problem and solution fields in the mobile app so there are some[ campaigns that you can't complete](https://docs.google.com/document/d/1M6OZbu45B-dKGWtjKRBffdEFDpAE6G08Dw_9mu0t_ig/edit) due to a lack of information or the inability to download PDFs and templates. This is not only confusing for users, but limits the actions we can feature in the app.
#### Current Workaround w/o Feature (if applicable)

We're not pushing people to the campaigns from the news feed, but users can still wander into them.

---

There was some discussion about this in issue #6388 but no solid conclusion has been reached about what to actually do with Action Guides. The only things we have to make sure stays are:
- Able to be displayed in a modal
- ~~Translatable~~
- Editable my campaigns team

@aaronschachter @angaither @weerd

**Comment by angaither** [comment]
Ignoring the `field_gallery` massive group field, it seems like we actually use most of the fields on the action guides. so we need to decide if we are exposing all of these, some of these and or depreciating fields on this content type to make it easier to expose. 

query: 

```
select n.nid, n.title, d.field_description_value, s.field_subtitle_value, it.field_intro_title_value, i.field_intro_value, ii.field_intro_image_target_id, att.field_additional_text_title_value, at.field_additional_text_value, ag.entity_id as 'node this is refed on'
from node n
left join field_data_field_description d on d.entity_id = n.nid
left join field_data_field_subtitle s on s.entity_id = n.nid
left join field_data_field_intro_title it on it.entity_id = n.nid
left join field_data_field_intro i on i.entity_id = n.nid
left join field_data_field_intro_image ii on ii.entity_id = n.nid
left join field_data_field_additional_text_title att on att.entity_id = n.nid
left join field_data_field_additional_text at on at.entity_id = n.nid
left join field_data_field_action_guide ag on ag.field_action_guide_target_id = n.nid
where n.type = 'action_guide';
```

[results](https://dosomething.slack.com/files/andrea/F17CWTGJH/action_guide_content.csv)

**Comment by weerd** [comment]
Turns out it's a bit easier than expected. The campaign node (with a bit of help from our custom field data extractor functions) provides us the ids for the action guides. Then, we can just use `node_load_multiple()` pass the ids, and we get _most_ of the data we really need. Not sure about the galleries b/c I don't know of local examples where I could see action guides w/ galleries in them? But I presume the galleries data would be it's own array of ids.

Anyhoo, just tried it out locally and using the `node_load_multiple()` makes it really easy to get the majority of what we need, then it's just a matter of filtering/processing to prep it for the `Campaign` class and then the `Transformer` 😉

**Comment by angaither** [comment]
@weerd we don't use the `gallery` field on those nodes, so no worries there

**Comment by weerd** [comment]
Cool! Well, the nice thing is _if_ we ever decide to use them, it'd just be a simple update to grab those and attach to the object/array that gets sent to the transformer, and bingo!

**Comment by weerd** [comment]
@lkpttn @angaither 

Here's a list of the items I'm leaving out and not exposing (partly cause I don't think we use them, but feel free to correct me!):
- `field_intro_image`
- `field_gallery`
- `field_additional_text`
- `field_additional_text_title`
- `translations`

cool?

_Note_ `translations` are excluded because in this action guide node "type", translations are not handle (data structure-wise) with how other things are translated (like campaigns & campaign runs and fields for those).

**Comment by angaither** [comment]
me thinks `field_additional_text` & `field_additional_text_title` are actually used

**Comment by lkpttn** [comment]
Yeah a quick spot check revealed at least a handful that use `field_additional_text` and `title`

https://www.dosomething.org/node/6708/edit
https://www.dosomething.org/us/node/4945/edit

The usage of the fields seems to be pretty inconsistent from campaign to campaign but I think we need those fields for sure.

**Comment by weerd** [comment]
Okie doke, thanks for the input!
