### ISSUE TITLE
Expose Download field for mobile apps

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6413]
#### User Story

We only display the problem and solution fields in the mobile app so there are some[ campaigns that you can't complete](https://docs.google.com/document/d/1M6OZbu45B-dKGWtjKRBffdEFDpAE6G08Dw_9mu0t_ig/edit) due to a lack of information or the inability to download PDFs and templates. This is not only confusing for users, but limits the actions we can feature in the app.
#### Current Workaround w/o Feature (if applicable)

We're not pushing people to the campaigns from the news feed, but users can still wander into them.

---

There could sometimes be multiple downloadable templates/files for a campaign so something to watch out for.

@aaronschachter

**Comment by weerd** [comment]
> There could sometimes be multiple downloadable templates/files for a campaign so something to watch out for.

@lkpttn can you provide me a link to a campaign that you know of that has multiple so I can test this out properly?

**Comment by lkpttn** [comment]
@weerd Lemme look around. I know it's _possible_ but not sure if we actually use it anywhere.

**Comment by weerd** [comment]
@lkpttn @angaither "translatable" is mentioned in #6412 however apart from providing global related data concerning a campaign's `campaign_runs`, available `translations` and the `language` for the current campaign node, `/api/v1/campaigns/1283` we don't provide any translations regarding the field data. None of the other properties show what a translation for that field is or defines how to make that available. All the API stuff was done before #Global really took hold.

I've had some thoughts about this regarding maybe it's a URL param passed when requesting a campaign like `/api/v1/campaigns/1283?language=es-mx` or something, and the returned data would be for that campaign but the mexican spanish translations, otherwise _all_ the fields would be crazy arrays of the field data and the translations for the items in the field data.

I'm going to continue the pattern we have and not provide the translated field info otherwise it'll mean reworking a bunch of functions etc.

**Comment by aaronschachter** [comment]
@lkpttn Would you mind adding Thor/Production campaign id's to this issue and #6412 we can use for testing?
