### ISSUE TITLE
Increase Max Width on Sponsor Logos in Campaign Template

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6433]
#### User Story

Recently, several sponsor logos have appeared smaller than preferable on the campaign header. This mostly happens when logos are long and skinny vs. square/circular logos. How can we change the current dimensions on the site to work better for all logos and still work within the constraints of the template on web and the mobile app?
#### Why This Matters

Sponsors should be happy with how their logo is appearing!
#### Current Workaround w/o Feature (if applicable)

We're hacking it in Optimizely by increasing the max width. :(

`window.jQuery(".promotion--sponsor .__image").css("max-width", "175px");`

cc @DFurnes

**Comment by DFurnes** [comment]
Yeah, this is a tough one. 😞 I wonder if an okay solution would be keeping sponsor logos below the campaign title/subtitle (like we do on mobile) for "tablet" width devices as well?

**Comment by namimody** [comment]
@DFurnes good thing your :brain: is on this! What would happen if we increased the max width to 175 or 190 px for certain logos? Like, add another image type for long logos? Could that work?

**Comment by DFurnes** [comment]
I think the problem is specifically with sponsor logos on evergreen campaigns (where the sponsor logo is directly to the right of the tagline, rather than being below it). If we're okay with sponsor logos always being below the tagline, I think we could definitely increase the max-width.

Without a end date to push it down:
![screen shot 2016-05-13 at 12 01 53 pm](https://cloud.githubusercontent.com/assets/583202/15253954/80284bd6-1902-11e6-8730-fa15be233682.png)

But with a end date set (which pushes the sponsor logo below), it's all cool:
![screen shot 2016-05-13 at 12 02 40 pm](https://cloud.githubusercontent.com/assets/583202/15253983/9c2dd792-1902-11e6-98f4-fa7079c3e6e1.png)

If we always had the sponsor logo floated to the right on a second "row" like it does in the second screenshot, I think we could safely increase the max dimensions across the board.

**Comment by namimody** [comment]
Hmmm I feel like sponsors almost always (really can't think of an exception) come on for "limited time only" campaigns, so that might work! Thoughts @mikefantini?

**Comment by lkpttn** [comment]
I think we're going to have a really good opportunity to solve this when redesigning the header with the campaign template updates. Overall I want to move a lot of stuff out of the photo area and I think we could get multiple birds with one stone moving the corporate logos out too.

**Comment by namimody** [comment]
For sure, but thoughts on the immediate future @lkpttn?

**Comment by lkpttn** [comment]
How immediate is immediate? After we do the initial onboarding work, we're planning on doing changes that could encompass the header in Template 2.2 or 2.3 which could be 2-3 sprints away. If that's an accurate time frame it might not be worth it to invest anything more than the optimizely hack now and change it then too.

**Comment by namimody** [comment]
I'm currently hacking this one two campaigns @lkpttn and just got requests to hack it on two more, both launching late June/early July. Because of the manual work + back and forth required as well as the tax on the site, I'd love to just make this work within the system, even if that is for the next six weeks.

@DFurnes -- from what I understood above, and assuming all sponsored campaigns are timeblocked, they have an end date that appears on the pitch page. The end date pushes the sponsor logo to the line below. therefore, the only change that would need to be made in the code would be increasing the pixel number to a higher maximum, which is a small change?

**Comment by DFurnes** [comment]
@namimody Yep, that's probably not a huge lift. I don't think we should assume that all sponsored campaigns will have end dates unless that's enforced in the CMS, but it looks like it'd be easy enough to fix it for everything (as described above!).

**Comment by mikefantini** [comment]
The issue with this solution might be closed campaigns where we lose the end date?

Example: https://www.dosomething.org/us/campaigns/world-recycle-week-close-loop-0.

I do agree that it's worth thinking of a short-term solution for this so that we can ideally stop hacking away at it. @lkpttn @DFurnes is there any solution you two can think of we can get in before the next two campaigns we need to fix this for? Possibly @DFurnes's original idea of treating tablet the same way we do mobile for now?

**Comment by namimody** [comment]
Ah! Closed sponsored campaigns @mikefantini, great point.💃

Though -- I _think_ that we are still covered in this scenario because the NOTIFY ME button always forces the sponsor logo to underneath the campaign title, like so: 

![image](https://cloud.githubusercontent.com/assets/12396076/16286626/b6bf00f4-38ab-11e6-9aaa-d3e021d7ced6.png)

Also, I _think_ we can also safely say that all sponsored campaigns are either timeblocked with an end date or closed.

Thoughts, team?

**Comment by mikefantini** [comment]
Yeah I mean in this case then the scenario where we would run into issues is:
- closed campaign
- member has clicked notify me
- member is viewing on tablet sized screen

IMO running into this issue here is enough of an edge case for this temporary fix that I can live with it.

@DFurnes @lkpttn please let us know your feels and if we can get a fix in.

**Comment by DFurnes** [comment]
I still think we should just _always_ have the sponsor logo on a row below the title/subtitle, regardless of what other content is on the page (so it'd look like it does when there's an end date). Then we could safely increase the width to whatever we want.

**Comment by namimody** [comment]
Sounds good to me @DFurnes! @lkpttn @mikefantini -- sound good?

**Comment by mikefantini** [comment]
👍

**Comment by DFurnes** [comment]
Self-assigning by @mikefantini's request. Will get this fixed up this sprint! 😄

**Comment by DFurnes** [comment]
This is deployed on staging now, for review by @namimody and @DoSomething/design. There's also a few screenshots in the PR above. 🎨

**Comment by namimody** [comment]
Tested on Thor for Context Clues, Birthday Mail, and Thumb Wars (unsponsored) across Chrome, Safari and Mobile Web on all pitch and action pages and it looks good to me! Thanks @DFurnes!
