### ISSUE TITLE
Display different info for people of different ages

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6554]
## _FEATURE OVERVIEW_

Based on the user's birthday send the user to the appropriate experience 
- 18+ gets the registration form
- Under 18 gets the social declaration

**Comment by sbsmith86** [comment]
If they are under 13 we still need to do the GET to the postal code endpoint?

**Comment by angaither** [comment]
@sbsmith86 I think the goal with people under 13 is to just send the user to the share link, but I think it's  still TBD

**Comment by angaither** [comment]
@ngjo I think we still need to decide who we want to show the form to, based on birthdate

**Comment by ngjo** [comment]
@angaither 
- 18+ gets the registration form
- Under 18 gets the social declaration

**Comment by chloealee** [comment]
@ngjo @mikefantini Question: on the user flowchart, it looks like if a user is under 18, they get taken to this view instead of the registration form: 
![screen shot 2016-06-13 at 1 53 20 pm](https://cloud.githubusercontent.com/assets/9019452/16017506/40f9e652-316e-11e6-8500-a71de00d818a.png)

I was looking at the [API docs](http://docs.fiftythree.apiary.io/#reference/profile/declaration/post) and [Organize's FAQs](https://organize.org/faqs/) and it seems like they have a database to POST to and save user's info if they want to make a social declaration. Do we want to POST to this too? 

If so, I was thinking we could have a blurb to explain what a social declaration, what database their info would be saved, the short form (email, first name, last name, postal code), and then after this is submitted, will go to the last screen of the modal with custom share links, just like we have now after the registration form?

**Comment by ngjo** [comment]
Ahhh, I see -- so the "social declaration" isn't just the literal social share language (i.e., "#ISupportOrganDonation) -- so that's why in part ORGANIZE has the user fill our the form and then finds out their age.

So to confirm, the only data that ORGANIZE needs for the social declaration is:
- email
- first name
- last name
- postal code

Is this information required by ORGANIZE? 

@angaither @sbsmith86

**Comment by sbsmith86** [comment]
I don't think anything is "required" per say...but there is definitely a [declaration](http://docs.fiftythree.apiary.io/#reference/profile/declaration) endpoint in their api. I think we just need some clarification on what this endpoint is and/if we **need** to use it. That being said, all the information that they are asking us to post to that endpoint we already have and probably don't need to collect it explicitly (i.e. no form needed) again.

**Comment by ngjo** [comment]
Kk -- will add this question to the #organize slack channel for Dana to clarify.

If we don't need it, let's not send the info to ORGANIZE then -- it'll simplify the language on the social declaration page.

**Comment by ngjo** [comment]
From Dana in #organize: "Declaration endpoint (I believe we discussed this on the call) was for use in an old version of 53. Its no longer in use and is scheduled to be retired shortly"

So we can ignore that and continue with sending them to the social declaration view w/o the additional form.

**Comment by ngjo** [comment]
@angaither can't remember if we talked about this or not, but would it be possible for the people who get the social declaration (under 18) to be granted a unique sharing link too? or does it generate only when you submit the form?

**Comment by sbsmith86** [comment]
@ngjo they would get the unique link as well, we generate it on page load.
