### ISSUE TITLE
Update facebook api calls

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6622]
Facebook API is updating, and it seems we are several versions behind. We need to update to `v6` by Aug 8th before it breaks
 from @sbsmith86  

> we were using the `feed_dialog` url but now we should use this [`share_dialog` url](https://developers.facebook.com/docs/sharing/reference/share-dialog#advancedtopics) 

![](https://files.slack.com/files-pri/T024GV2BW-F1K8NG8AC/pasted_image_at_2016_06_22_11_00_am.png?pub_secret=f2a9bedb71)

**Comment by sbsmith86** [comment]
I've been digging more into this issue and it actually still doesn't make a lot of sense to me. 

1) we don't specify this permission anywhere in Phoenix so I have no idea what it is referring to.

2) More digging has revealed that the `feed_dialog` is still ok to use. In fact, the permission that the facebook upgrade tool is referring to only relates to using the `share_dialog` method, which we don't use anywhere. [here are docs on the different types of share URLs](https://developers.facebook.com/docs/sharing/web) 

3) We don't use the `share_dialog` web sharing functionality because this is only available in the Facebook SDK which we don't have implemented in phoenix..

So, is it possible that this is referencing a different app other than phoenix? the mobile app? Is there anything else in the DoSomething.org world that is using the Facebook SDK and the share dialog method?

**Comment by angaither** [comment]
@sbsmith86 I wonder if the email from greg had which app this was on 🔍

**Comment by DFurnes** [comment]
I wonder if this is from when we used to have Facebook integration on the old site?

**Comment by angaither** [comment]
@DFurnes it seems like either that or pics for pets.

**Comment by sbsmith86** [comment]
@angaither can this be closed?

**Comment by angaither** [comment]
Documenting here for the future: 

The email Greg Thomas got was from an old facebook app that was no longer in use (though it mysteriously had 11 users) I turned off the app, so we no longer need to worry about v2.0 being depricated in August.

The screenshot @sbsmith86 posted here is for the current app, and that version of the api will expire eventually, but not anytime soon
