### ISSUE TITLE
Disable Signup Email on SMS Games for logged in members

### ISSUE THREAD

**Issue by jamjensen** [DoSomethingArchive/legacy-website#6635]
#### Current Behavior
- A member received a transactional email after signing up for context clues. 
- The message they received was our standard signup template, meaning it should have provided three steps to help complete the campaign.
- However, since it is an SMS nudge/game and not a DS campaign, there are no tips. 
- This email is incredibly misleading for two reasons (1)  the "Get Started” button leads them back to the webpage, when the entire experience is meant to be via SMS and (2) we ask them to “snap a pic” which results in the member being completely confused as to what type of campaign it is 
#### Desired Behavior
- They should receive clear instructions on how to complete the SMS Game or no email at all (to prevent them from bouncing between platforms)
- As discussed in Slack, the interim solution is to disable all SMS Game signup emails. 
#### Steps to Replicate
- Sign up for an SMS Game while logged in to your DS account
#### Why This Matters
- The email creates a poor user experience by confusing the member on how to report back. 
#### Relevant Screenshots + Links

![screen shot 2016-06-23 at 5 53 54 pm](https://cloud.githubusercontent.com/assets/19572934/16322181/5fcd8bfc-396f-11e6-8879-fa4d32dd0846.png)

https://www.dosomething.org/us/campaigns/context-clues

**Comment by angaither** [comment]
hmm, it seem like we actually [already did this](https://github.com/DoSomething/phoenix/commit/0ad46b569a61a4ba4c4f17262bc177ffc62727db)
since it was an issue #2315

currently it looks like [we aren't sending transnationals for sms games, and the functionality that is referenced on signup for sms games no longer exists](https://github.com/DoSomething/phoenix/blob/a3d9c0fc6de55ceafd386ccfae03fab4cdb0099b/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L515-L518)
