### ISSUE TITLE
Kudos: Heart image is broken -- only see boxes

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6643]
#### Current Behavior

When clicking 'view more' on the gallery, the new images that appear do not have kudos hearts. Instead, a box is shown.
#### Desired Behavior
- Hearts should appear for all images. 
#### Steps to Replicate
1. Navigate to a campaign - https://www.dosomething.org/us/campaigns/shower-songs
2. Scroll down and click 'view more'
#### Why This Matters

This is a bad experience for the users and could decrease are amount of kudos interaction.
#### Relevant Screenshots + Links

![screen shot 2016-06-27 at 4 24 51 pm](https://cloud.githubusercontent.com/assets/14931921/16394665/581c7a0e-3c84-11e6-9b00-465a7d86fa4d.png)

**Comment by itsjoekent** [comment]
Have we deployed the fix I made earlier?

edit: no, deploying it now.

**Comment by angaither** [comment]
that was on the user profile

**Comment by itsjoekent** [comment]
view more functionality/code is the same everywhere I thought?

**Comment by itsjoekent** [comment]
yeah i just checked, what I fixed locally is on the campaign template. the show more on my user profile is still broken however

**Comment by itsjoekent** [comment]
I think this is the problem for user profiles.

When you click "Show more" it looks like this with the buttons detached from the gallery item.
<img width="968" alt="screen shot 2016-06-28 at 10 37 33 am" src="https://cloud.githubusercontent.com/assets/897368/16419615/64303216-3d1c-11e6-9d67-5ed8e4de3bf0.png">

I believe its because in this line of code,

https://github.com/DoSomething/phoenix/blob/b2706b012d415a2d94796bb6df776da538dcd2e4/lib/themes/dosomething/paraneue_dosomething/js/patterns/Gallery.js#L34

we treat each list element as a tile and the Kudos heart is also an li.
