### ISSUE TITLE
Display campaigns to signup for on the onboarding experience

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6665]
#### User Story

As a user on the first screen of onboarding I can sign up for other campaigns
#### Additional Information (optional)

Use solr to grab the campaigns
- display open, published campaigns
- boost staff pick campaigns
- boost if has a partner that is a sponsor  
- boost by `field_active_hours` (smallest values first) 

Do not display campaigns that user has already signed up for

**Comment by jessleenyc** [comment]
Update: we're debating on whether to boost by field_active_hours before/after boosting by sponsor. Will keep you posted.

**Comment by angaither** [comment]
@jessleenyc feel free to edit the issue description once the decision has been made!

**Comment by weerd** [comment]
I wanted to provide an alternative approach that could help save some time, at least for a v1 rollout.

We could gather info on user's signups from Drupal and add it to the `Drupal.settings.dsUser.activity` object, so it's available for us in React.

Instead of using Solr (which I've heard can be rather complicated, but I don't know offhand other than some of the stuff I worked with during the campaign finder), and having to process that data in a fashion that is ready for use in JavaScript easily, we use the `/campaigns` endpoint instead, which responds with a ready to use JSON response, that is fully formatted and ready to use for JS.

I understand that it will _not_ be nearly as smart as a Solr search, but we could grab all staff pick campaigns and then filter out the ones that match IDs from the signups the user already has (which would be found in `Drupal.settings.dsUser.activity`).

Just a suggestion, but could make things easier, particularly for a v1 build.

Thoughts?

**Comment by itsjoekent** [comment]
we could also sort the results locally if `field_active_hours` and `sponsor` are in the API response

edit: so active hours does not appear to be in the API response, but sponsor is

edit 2: oh wait it is. its called `time_commitment`

**Comment by weerd** [comment]
yeah... `field_active_hours` was renamed to `time_commitment` cause the term "active hours" made no sense to me. And sponsor info is in the `affiliates` object :)

**Comment by jessleenyc** [comment]
Let's sort by: staff pick -> sponsored -> active hours

**Comment by angaither** [comment]
@jessleenyc can you update the order in the issue?

**Comment by jessleenyc** [comment]
Updated ^

**Comment by itsjoekent** [comment]
some useful links

https://gist.github.com/deadlybutter/c3577c9690e6af93297306bc66d6a072
https://gist.github.com/mankyKitty/5905740

**Comment by jessleenyc** [comment]
@deadlybutter When ready, please send over the list of campaigns (in the order they're displayed) based on the logic we're using. Want to confirm it's pulling the right ones.

**Comment by angaither** [comment]
@jessleenyc this won't be the same list from staging/production

**Comment by jessleenyc** [comment]
@angaither got it -- as long as we have the feature flag -- we can test in staging without worrying the feature gets deployed into production the next day, right?

**Comment by angaither** [comment]
@jessleenyc yes, that's the idea. however if we launch the second screen, and then merge this, we either need to write new logic to turn just this part off, or fully test this before deploying

**Comment by jessleenyc** [comment]
@angaither assuming there are no major bugs, we can test in one day on thor if we merge early. but if there's a big bug, would we be able to rollback to get more time to test the next day?

**Comment by angaither** [comment]
@jessleenyc yeah, though rolling back should only be used in extreme cases

**Comment by itsjoekent** [comment]
sorry want to make sure im following this right -- we want to be able to merge code related to the feature card / campaign signup without showing it to users? 

easy! the array in onboarding.js just needs to be changed from `const slides = [ContextSlide, InstructionSlide];` to `const slides = [InstructionSlide];`

as for the API call, I can give you the production list since thats the only one which really matters

**Comment by jessleenyc** [comment]
@angaither the 'staff pick' checkbox is not a good indicator of which campaigns are staff picked because the campaigns team uses it to toggle the 'staff pick' label. We generally have all staff picks + more campaigns on the home page. Since we don't want an overwhelming number of 'staff pick' labels on the homepage, certain staff pick campaigns are not marked in drupal. 

Are we able to 1) change the way the labeling works or 2) create an additional checkmark box that's used for our actual staff pick campaigns for us to pull into the suggested campaigns?

**Comment by angaither** [comment]
@jessleenyc I'm more interested in changing the way the label works. 
Is it something we only want if there's a partner who is also sponsor?
