### ISSUE TITLE
Reportback gallery sometimes not loading new items!

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6681]
#### Current Behavior

On [thumb wars](https://www.dosomething.org/campaigns/thumb-wars), and [happy howlidays](https://www.dosomething.org/us/campaigns/happy-howlidays) `view more` reportback items call isn't returning new results. 
#### Desired Behavior
- People can view all the gallery items.

**Comment by weerd** [comment]
Turns out it was just a caching issue. The `/reportback-items` endpoint gets cached, and after the changes the Kudos object was significantly changed, however the cache still had the responses from the old object. 

After clearing the cache on Prod, the galleries are working again.

@angaither @mikefantini @jessleenyc ^^
