### ISSUE TITLE
Add signup and impact goal fields on runs 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6699]
#### User Story

As an admin, I want the option to add signup goals, new member goals, and impact goals for each campaign. 
#### Additional Information (optional)

These should be three backend fields that are non-required. 
#### Why This Matters

Pulling these numbers directly from Phoenix will give us on-demand access to see whether or not each campaign is meeting their signup, member, and impact goals through our new visualization tool. The current process is not streamlined and leaves more room for human error.

**Comment by jessleenyc** [comment]
@angaither: how feasible is this type of request & is there room to pull it into our current sprint?

**Comment by angaither** [comment]
@jessleenyc do these need to be translatable? do we want them displayed anywhere?

There's a few issues that are updates to campaign run nodes. It's something we retro-fitted for the what they are being used for now, so I would love to bundle updates together
#6177 #6235

**Comment by jessleenyc** [comment]
@angaither we're not looking for these to be translatable at the moment and we don't need the numbers to be displayed -- internal use only.

**Comment by angaither** [comment]
@jessleenyc hm I think if they aren't translatable, it might cause some issues on how we are counting numbers if the runs themselves are translated.

**Comment by jessleenyc** [comment]
@angaither we actually need 3 additional fields, here are all 6 in total:

external signup goals
external new member goals
external impact goals

internal signup goals
internal new member goals
internal impact goals

These numbers will not be displayed. 

Translatable: can we talk about this irl?

**Comment by sbsmith86** [comment]
@mikefantini do you have thoughts on the translatable thing here?

**Comment by jessleenyc** [comment]
@sbsmith86: i'm not sure i have the fullest understanding on the implications of how this will effect our numbers. can you give me some examples? or can we talk about this in person tomorrow?

**Comment by mikefantini** [comment]
Oh global runs...

Hopefully we don't run into a counting issue since we're not calculating what the actual quantity is here but rather are just stating what the goal is. In that case if we are merely translating a run I don't think we'd need to have it translated because the goal for that run would be cumulative across translations of the run, not distinct per translation.

Example:

We want to hit 100,000 signups for Birthday Mail. We don't want to say that we want 90,000 of those coming from the US translation and 10,000 coming from GL EN. Instead we want 100,000 total and don't have a preference on where they come from.

Does that make sense @sbsmith86 @angaither @jessleenyc?

**Comment by sbsmith86** [comment]
yup yup!

**Comment by sbsmith86** [comment]
Re-opening because I mis-read this issue and added fields per campaign NOT per run.
