### ISSUE TITLE
Staff Pick label not showing up on unfiltered homepage

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6724]
#### Current Behavior
- Campaign tiles on the homepage don't have the "Staff Pick" banner on them until they're filtered by the Action Finder.
#### Desired Behavior
- Staff Picks should have the banner on them at all times.
#### Steps to Replicate
- Replicated on Chrome and Safari, just loading the homepage.
#### Why This Matters

We want to make sponsors happy!
#### Relevant Screenshots + Links

![screen shot 2016-07-18 at 11 03 14 am](https://cloud.githubusercontent.com/assets/1865372/16919356/5511b0e6-4cd7-11e6-96b2-24e679dcc093.png)
![screen shot 2016-07-18 at 11 03 23 am](https://cloud.githubusercontent.com/assets/1865372/16919366/5dfe7a18-4cd7-11e6-810d-aef85c9e4970.png)

**Comment by angaither** [comment]
I think this is probably due to #6535 
it seems like the field wasn't translated correctly since sometimes it shows "all languages" for older nodes 
![image](https://cloud.githubusercontent.com/assets/645205/17142719/2710cddc-531f-11e6-9c62-653de33579d9.png)

but for new ones, it shows correctly translated 
![image](https://cloud.githubusercontent.com/assets/645205/17142742/43368ad8-531f-11e6-8d25-ccd4c2b71680.png)

might also be related to #6735

**Comment by angaither** [comment]
oh also staging says the field is not translatable 🆒 
![image](https://cloud.githubusercontent.com/assets/645205/17149670/4f2161fe-533a-11e6-9a37-04488e55f115.png)
