### ISSUE TITLE
Update layout styles for Onboarding component

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6725]
Adjust the layout styles to match those of the design.

**Comment by weerd** [comment]
![image](https://cloud.githubusercontent.com/assets/105849/16922770/08eefdaa-4ce5-11e6-9057-d971ea98ae03.png)

@lkpttn @jessleenyc thoughts on this at "tablet" size. It would help moving forward if we all 3 "sizes" (or approximations) are accounted for when passing along designs. Sometimes we can infer what a design could look like on tablet just based on seeing mobile and desktop designs, but other times we are just left with a bunch of questions.

@lkpttn we chatted with @DFurnes about the cards not having a fixed max-width and it being determined more by the size of the container they sit in. But I feel there are a few exception like in the situation above for tablet size. Thoughts? Maybe it's exclusive to just the onboarding card, or maybe there's a max-width up until it get to desktop and then the layout changes dictate its width?

**Comment by DFurnes** [comment]
It might make sense to have a container variation that has `2/3 - 1/3` columns on desktop, `1/2 - 1/2` on table, and stacked on mobile. It seems like an option we might use elsewhere. I definitely think the layout concerns should be handled by some sort of "layout" pattern, rather than baked in to the card.

(Or maybe this is a `.figure.-right` and the card is always a certain fixed-width on the right, and then stacks on mobile?)
