### ISSUE TITLE
Campaign: Confirmation template

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#679]
Create a page callback for confirmation of reportback submission.

Update Campaign's reportback submission to redirect user to this page upon success.

**Comment by mikefantini** [comment]
This confirmation page should have 3 campaigns it suggests.

We'll show:
- hero image
- title
- call to action

This will look like the gallery on static content: https://docs.google.com/a/dosomething.org/viewer?a=v&pid=sites&srcid=ZG9zb21ldGhpbmcub3JnfGRvc29tZXRoaW5ndXh3aWtpfGd4OjNkNGY1ODQyODE2MDMwMmM

We need to have 4 campaigns the confirmation page can select from and add logic so that it doesn't suggest the campaign the user just reported back on.
