### ISSUE TITLE
Blank onboarding experience, for experienced users 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6818]
#### Current Behavior

Onboarding experience appears blank if user is signed up for all staff picks
![image](https://cloud.githubusercontent.com/assets/645205/17408192/440a3c14-5a38-11e6-95e0-59d506e1f506.png)
#### Desired Behavior

During the onboaring experience if a user is is signed up for all staff pick campaigns, pull in other non staff pick campaigns in the order described in #6665
- display open, published
- boost staff pick campaigns
- boost if has a partner that is a sponsor  
- boost by `field_active_hours` (smallest values first) 
#### Steps to Replicate
- check on staging on an account you've used a couple times.

**Comment by itsjoekent** [comment]
Just noting, we currently boost by all of the values described, but only on the list _of_ staff pick campaigns. We just need to look at the larger list.

For the sake of performance / load time, I think the best approach is to only retrieve the staff pick campaigns to _initialize_ the card. After the card is initially rendered, we can then do a larger pagination to retrieve all non staff pick campaigns & apply the same boost logic. Since most users are not going to be signed up for every staff pick campaign, this should be incredibly seamless.
