### ISSUE TITLE
Feature card not appearing on Firefox 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6853]
#### Current Behavior

Feature card w/ multi-campaign signup is not appearing on firefox. 
#### Desired Behavior

Feature card should appear!
#### Steps to Replicate

1) Navigate to thor.dosomething.org
2) Login & Signup for a campaign
3) Observe
#### Why This Matters

We should have an onboarding experience across all browsers we support so all our members can be onboarded. 
#### OS/Browser (optional)

Firefox v47
#### Relevant Screenshots + Links

![screen shot 2016-08-10 at 12 39 24 pm](https://cloud.githubusercontent.com/assets/14931921/17562395/b93dbb7c-5ef8-11e6-8ed9-17cdaa68e96b.png)

**Comment by weerd** [comment]
There was a bug that was creating a similar affect in IE10 that was caused by an error in the OrganDonation script. Since removing it helped with IE10 it may also have helped resolve it in Firefox. I've check it a bit and haven't seen it in Firefox so removing that script may have resolved it here too!
