### ISSUE TITLE
White line showing up between homepage tiles on Safari

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6885]
#### Current Behavior

if you go to the DS homepage on safari, this white line is showing up between the campaign squares
#### Desired Behavior

no white lines (see chrome homepage -- there isn't a white line)
#### Steps to Replicate
1. open safari
2. go to DS homepage
3. see the white line (screenshot below)
#### Why This Matters

because the white line is distracting and doesn't look right
#### OS/Browser (optional)

reported on:
- MAC OS X 10.11.5 Safari v. 9.1.1
- MAC OS X 10.11.6 Version 9.1.2 (11601.7.7)
#### Relevant Screenshots + Links

thor.dosomething.org 
![screen shot 2016-08-16 at 10 22 01 am](https://cloud.githubusercontent.com/assets/2658867/17702391/b0586776-639b-11e6-8e28-41f7d7e4a7c2.png)

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;exxUj0YD&#x2F;1592-homepage-video-tile-bug-white-lines"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Homepage Video Tile Bug (White Lines)</a>

**Comment by weerd** [comment]
We've encountered an issue like this before on the homepage tiles and was resolved but it's due to a sub-pixel rendering issue with how the browser renders the tiles, especially with its responsive nature. The white line goes away if you make the browser window smaller or larger and the rendering fixes itself.

One solution could be to make the container background (or whichever container/item has a background of white) to be darker, so when the spacing issue happens, it's more discreet.

**Comment by angaither** [comment]
closing because of reasons from @weerd 

> Just a matter of browser size and you sometimes see it. Quickest fix is to make the background color black, but then it would just be a black line. I feel on a future Safari update the subpixel rendering will ideally get resolved. 
> 
> we have bigger 🐟  to 🍳

**Comment by weerd** [comment]
😈
