### ISSUE TITLE
Send reportback to rogue

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6960]
#### User Story

On submission of reportback form, send it to rogue. Deal with good/failures

**Comment by sbsmith86** [comment]
@angaither I was talking to @chloealee yesterday and I think there are some things we need to consider here. 

I was thinking through the flow of events and in the case of reviewing a reportback. We need to be able to specify which reportback item needs to be updated but phoenix doesn't have any idea about rogue identifiers. Because we are going to be storing the reportbacks in two different places drupal will still reference a reportback by it's own `rbid` and the item's`fid` but those won't correlate with rogue ids.

So two options: 

1) we store rogue ids and which `rbids` they correspond to in drupal. So the flow would be: 
-> user submits reportback form or review form
-> phoenix sends reportback to rogue 
-> rogue stores or updates reportback 
-> rogue sends response back to phoenix with rogue reportback `id` and the item `id`
-> **Drupal stores those ids in a new table that has the drupal `rbid` and the rogue ids.** (we might need two separate tables for reportbacks and items)
-> anytime drupal makes a request to rogue, it looks up the corresponding `rogue_reportback_id` to the `rbid` that it knows about and sends the request with the `rogue_reportback_id` 

2) Flip it so the flow would be: user submits reportback form 
-> user submits reportback form or review form
-> phoenix sends reportback to rogue 
-> rogue stores or updates reportback 
-> **phoenix sends response back with the `rbid` and `fid` it stored in phoenix** 
-> rogue stores that in it's own tables
-> anytime drupal makes a request to rogue, it sends the drupal version of the ids over and rogue looks them up that way.

Both of these options would take a little bit more work and probably the same amount of time, but I am partial to the first option. One, I don't think we want to spend too much time on having rogue be aware of anything drupal is doing since if we really separate this out as a service it shouldn't matter what an `rbid` is. Also, if we did #2, we would have to update the response that drupal sends back when you POST to the reportback endpoint, because it only returns `rbid` right now and we would also need `fid`. Not sure if doing that would mess with anything else using the endpoint at the moment. 

Sorry for the essay, but wanted to document this here in case you had thoughts.

**Comment by angaither** [comment]
@sbsmith86 hm
1. this idea makes sense, however I wonder if we could do secret idea 3 


3. enable rogue across campaigns and set the index in rogue/phoenix to something to match so that `id` in rogue == `rbid` in phoenix? 
that was our original goal I think?

**Comment by angaither** [comment]
@sbsmith86 hm
1. this idea makes sense, however I wonder if we could do secret idea 3 
2. ... 
3. enable rogue across campaigns and set the index in rogue/phoenix to something to match so that `id` in rogue == `rbid` in phoenix? 
    that was our original goal I think?

**Comment by sbsmith86** [comment]
@angaither ah ya we could do that to, but wasn't sure how safe we felt with doing that on the first iteration of the project. 

Also there is still the case of rb items, which are currently identified by `fid` in drupal, but we don't really need to know about `fid` in rogue and in fact, we won't know about `fid` until after it gets stored in drupal (in which case we will still need to update the phoenix response to tell us what the `fid` is). I did set up a `file_id` column in rogue, but i was thinking we could just get rid of that now that rogue does it's own file storage.

The rb item thing becomes important when updating the status of reviewed rb items since we will need to pin point which rb item to update and what status to give it.

**Comment by sbsmith86** [comment]
orrr could drupal store the rogue item id as the `file_id`? hmmmm

**Comment by sbsmith86** [comment]
Update: Talked with the team and we are gonna go with option 1

We are going to create a table in phoenix that tracks `rbids` and the corresponding rogue `id` so phoenix is responsible for keeping track of where it stored stuff and where rogue stored stuff and can make requests to rogue appropriately.

I think we will need two tables, one to track reportback ids and one to track item ids because one reportback could have multiple items. 

@ngjo @chloealee @angaither

**Comment by angaither** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ar6hiN33&#x2F;1-as-a-developer-i-want-to-be-able-to-send-rbs-from-phoenix-to-rogue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As a developer I want to be able to send RBs from Phoenix to Rogue</a>
