### ISSUE TITLE
 Adding redirect option to take the user to the campaign page

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7027]
#### User Story

As a user, when I click the sign-up magick link, I want to be taken to the appropriate campaign page.
#### Why This Matters

So the user can see the campaign that they just signed up for.

**Comment by weerd** [comment]
@ngjo @angaither been playing around with this a bit. I got the redirect working, but now trying to set a message. Seems like I can't use the top status message that we use for a lot of other things if I'm coming from a redirect via the API; `drupal_set_message()` doesn't seem to pass the message along to the redirect via sessions or DB.

So alternatively we could go the message in a modal route? The modal is easy to pop up...

I'm looking into allowing access when anon to the campaign "action" page, instead of only the pitch page... I'm not sure how that'll affect other thinks throughout the site or externally though. If prior links in other venues to our site would have normally expected the "pitch" page, but now it'll take you to the action page... I'm a bit concerned about the repercussions here.

**Comment by weerd** [comment]
There may be a reasonable way to get around this by modifying when [this check](https://github.com/DoSomething/phoenix/blob/aac08a551d112eba8b21e5ef896d5044b99ad2f5/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L830-L831) happens in the `dosomething_campaign_is_pitch_page()` function. Since the user _will_ have a signup, _but_ is anonymous, we could let them through to the action page somehow (will need to modify this function to maybe allow passing the UID or something)... just a thought, not sure yet if this would work.

**Comment by ngjo** [comment]
Hey @weerd yeah, we could go the modal route if necessary. Let's sync about that after we can see if the action page anonymous viewing works or not. thanks!
