### ISSUE TITLE
Text in RB gallery cutting off on iPhone 5S

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7031]
#### Current Behavior

On the Iphone 5s some of the text in the RB upload area is being cut off (see screenshots)
#### Desired Behavior

Text shouldn't cut off
#### Steps to Replicate
1. Log into DS on an Iphone 5s
2. Go to the RB upload area
3. See text being cut off 
#### Why This Matters

So the user knows what it says there
#### OS/Browser (optional)

iPhone 5s
#### Relevant Screenshots + Links

![img_2460](https://cloud.githubusercontent.com/assets/2658867/18395393/447a6fe6-768c-11e6-966e-3668b9585712.PNG)
![img_2459](https://cloud.githubusercontent.com/assets/2658867/18395394/447d79ca-768c-11e6-80a4-8ab89f6c5d2b.PNG)

**Comment by angaither** [comment]
lol I just closed this #5588

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to see the helper text on reporting back on my iphone 5s so that I know how to reportback.](https://trello.com/c/kEFqxsyL/88-as-a-user-i-want-to-see-the-helper-text-on-reporting-back-on-my-iphone-5s-so-that-i-know-how-to-reportback)

**Comment by itsjoekent** [comment]
Part 1 of solving this requires a fix in Forge: https://github.com/DoSomething/forge/pull/563
Part 2 is going to be updating the Forge version in Phoenix
