### ISSUE TITLE
Experiment with new slide type

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#7041]
_TASK_
Let's see if it makes sense to create a new slide type that shows three featurecards, instead of changing our current slide type.

**Comment by itsjoekent** [comment]
Looking through the code,

I'd agree a new slide is the simple way to go. The real issue is everything else!
- Need to extract the functionality out of the feature card so multiple card types can share this (Or other things? eg: Galleries)
- In doing that we would also fix the logic problem of fetching more, as this new layer wouldn't care about auto updating or not.
