### ISSUE TITLE
voluneer pages borked

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#7089]
#### Current Behavior

all `/volunteer/` (term pages) are throwing a fatal error 

```
TypeError: Argument 2 passed to dosomething_global_get_language() must be an instance of stdClass, boolean given, called in /var/www/www.dosomething.org/releases/20160927134042/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module 
on line 845 in dosomething_global_get_language() (line 522 of /var/www/www.dosomething.org/releases/20160927134042/lib/modules/dosomething/dosomething_global/dosomething_global.module).
```

which seem to be due to [this commit](https://github.com/DoSomething/phoenix/commit/78239361dbc7425b9a5763edc714285a00fa57a1)
[this line](https://github.com/DoSomething/phoenix/blame/be4a145fd1a442fcdcf204ad4fedd61c3724ec60/lib/modules/dosomething/dosomething_global/dosomething_global.module#L522)
#### Desired Behavior

the pages loads and shows stuffs
#### Steps to Replicate
- go to any term page
#### Why This Matters

... it breaks the site
#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/645205/18881982/59cd8298-84ab-11e6-9014-f380c0d38519.png)

**Comment by itsjoekent** [comment]
@angaither so my initial findings have this not related to the global commit linked

`dosomething_global_get_language` is being called by `dosomething_campaign_is_closed` and is passing `false` as the node parameter (which based on the type hint is expecting an actual node). Anyway, `dosomething_campaign_is_closed` is firing because of the node preprocess, specifically `paraneue_dosomething_add_info_bar`. We can further see this function causing a problem in the first error message in that screenshot above ^ -- So the problem here seems to be `preprocess_node` is running on term pages?

**Comment by itsjoekent** [comment]
This is where the function is being called from, https://github.com/DoSomething/phoenix/blame/b2706b012d415a2d94796bb6df776da538dcd2e4/lib/themes/dosomething/paraneue_dosomething/includes/preprocess/preprocess_taxonomy.inc#L23

I think the best path forward here to support this & actual node preprocessing would be wrapping this block of code https://github.com/DoSomething/phoenix/blob/dev/lib/themes/dosomething/paraneue_dosomething/includes/preprocess/preprocess_node.inc#L86 in a null check for `$vars['nid']`
