### ISSUE TITLE
rogue failed log table is slow to load

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#7210]
_BUG_
-------------------
#### Current Behavior
The table is soooper slow when you try to look to see what failed. 

#### Desired Behavior
Things load speedy quick, like a fox or a cheetah. 
https://trello.com/c/C7QRBwUf/213-as-a-dev-i-want-to-add-database-indexes-to-the-rogue-failed-task-log-table-so-that-i-can-run-faster-queries

#### Steps to Replicate
take a gander at the data in `dosomething_rogue_failed_task_log`, wait forever. realize there must be a better way. 

#### Why This Matters
time = money
money = power
power = pizza

therefore
time = pizza

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) As a dev, I want to add database indexes to the rogue failed task log table so that I can run faster queries.](https://trello.com/c/C7QRBwUf/213-1-as-a-dev-i-want-to-add-database-indexes-to-the-rogue-failed-task-log-table-so-that-i-can-run-faster-queries)

**Comment by angaither** [comment]
fixed with #7211
