### ISSUE TITLE
User: Partner term field

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#772]
- [x] Add the existing field_partner onto the User, to associate a user with a partner term(s).
- [x] Only staff can view and edit the User's field_partner values.

This allows us to track activity for sponsors, e.g. 
- Did they even login and look at the action page? 
- Did they reportback?

As far as giving Sponsor/Partners access to campaigns before they are published, we'll use staging and publish a campaign there.

_Original Description_

Create "sponsor" and "press" roles, with same permissions as generic member role. 
When a sponsor like H&M wants to view their site that's behind the gate, we can create them a login.

**Comment by aaronschachter** [comment]
I think we'll need to add a field onto the campaign to track these specific users, as only specific users would be able to view specific campaigns.  e.g. A user with a "sponsor" or "press" role should not be able to see ANY unpublished campaign, only campaign nid = X that they are sponsoring.

**Comment by aaronschachter** [comment]
Thinking through this more, and fighting with the `view_unpublished` module to allow a user to see 1 specific unpublished campaign does not sound like a fight worth fighting.  

Perhaps this is implemented as a role after all, and it has access to "view any unpublished campaign."  The "risk" here is that they could guess a node nid of an unpublished campaign and view it, but does anyone care if they do?

@barryclark What is the purpose of 2 different roles if they do the same thing?

**Comment by barryclark** [comment]
Yea, I'm not sure about the difference between "sponsor" and "press" roles, I think they'd be the same. @mshmsh5000 ? 

I don't think we care if they guess a nid and view an unpublished campaign.

**Comment by angaither** [comment]
Instead of opening up all content, we could use a 'sponsored' flag on campaign nodes and only allow content of that type to be seen by a 'sponsor' role.
Alternatively, we could introduce another state to nodes, like 'moderation' that allows people of a certain role to view the nodes.  
We can use workflow/workbench/workbench access as a guide

**Comment by aaronschachter** [comment]
Renaming this issue as per discussion with @barryclark and @mikefantini and updating the description.  As far as a sponsor/press viewing anything behind a gate, we'll publish a campaign on staging and direct them to it in order to view campaign flow, vs allowing them to view anything unpublished on production.

**Comment by barryclark** [comment]
:thumbsup:
