### ISSUE TITLE
Fatal error: Mobilecommons not found

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#810]
1. Went to http://stage.dosomething.org/node/19/pitch 
2. Clicked the signup button
3. Pitch page reloaded with the status message: You're signed up! Get started with School Standstill below!

I should have been redirected to the action page instead.

**Comment by aaronschachter** [comment]
Will take a look tomorrow, but it seems like something's up with the Mobilecommons module, which could cause the error because the signup isn't going through.  Did you see the error below?

Fatal error: Class 'MobileCommons' not found in /vagrant/lib/modules/dosomething/dosomething_signup/dosomething_signup.module on line 288

**Comment by barryclark** [comment]
@aaronschachter I don't remember that error appearing on the page for me.

**Comment by aaronschachter** [comment]
Renaming this issue because the "Fatal error not found" is not a good thing.  Determined that Barry was testing from the /pitch test page, which will always redirect you to /pitch -- it only exists for staff to view the pitch page regardless of signup status.

**Comment by aaronschachter** [comment]
This was occurring because the library needed to be renamed: #656.  Seems like we haven't run ds build for a while on stage.  I've manually renamed the directory in staging and the error is no longer occurring.  I'm keeping this issue open to add a check that the `libraries_load` returns an object where loaded=TRUE, as per https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module#L48

**Comment by aaronschachter** [comment]
FYI - Barry did not get this error because he didn't add his mobile into his user profile (shame shame)

**Comment by barryclark** [comment]
Haha, I'm added to the mobile commons DB on another account.
