### ISSUE TITLE
Campaign: Mobile Commons ID for Staff Picks

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#859]
Staff Picks need their own individual Mobile Commons ID.

This will allow us to put users into specific messaging paths for staff pick campaigns (i.e. H&M).

All of the same shit should happen as with non-staff pick campaigns except instead of being put into ID: 164951\* they would be put into the ID specified by this field / variable.

See #450 #759 #858 for related issues.

cc: @jonuy @barryclark 

*note updated to new Mobile Commons ID

**Comment by aaronschachter** [comment]
@mikefantini Where on the form should this go?  Currently "Is Staff pick" is located in the "Taxonomy & Discovery" group, should it go there below that checkbox?

**Comment by mikefantini** [comment]
@aaronschachter yeah that makes sense.

Field name: Mobile Commons Opt-In Path ID

Help text: Get the Mobile Commons ID from Alysha. Make sure to test signing up for the campaign to confirm that you get the appropriate text message.

**Comment by aaronschachter** [comment]
As discussed with @angaither and @mikefantini today -- instead of adding a new field, we're going to store opt-in paths for Staff Picks in a Drupal variable.  Because the majority of campaigns will not need their own opt-in path, it's not worth the overhead of creating an additional field.  

We'll do the same for Mailchimp Group ID's -- create a variable to store all Mailchimp ID's for Staff Picks vs. creating a field on the campaign node.
